import type { AppCategory } from "./categoryTokens";

export interface DefaultAppMapping {
  name: string;
  category: AppCategory;
}

export const DEFAULT_APP_MAPPINGS: Record<string, DefaultAppMapping> = {
  "chrome.exe": { name: "Google Chrome", category: "browser" },
  "msedge.exe": { name: "Microsoft Edge", category: "browser" },
  "firefox.exe": { name: "Firefox", category: "browser" },
  "opera.exe": { name: "Opera", category: "browser" },
  "brave.exe": { name: "Brave", category: "browser" },
  "vivaldi.exe": { name: "Vivaldi", category: "browser" },
  "arc.exe": { name: "Arc", category: "browser" },

  "code.exe": { name: "VS Code", category: "development" },
  "codex.exe": { name: "Codex", category: "development" },
  "vscodium.exe": { name: "VSCodium", category: "development" },
  "cursor.exe": { name: "Cursor", category: "development" },
  "alma.exe": { name: "Alma", category: "ai" },
  "antigravity.exe": { name: "Antigravity", category: "development" },
  "idea64.exe": { name: "IntelliJ IDEA", category: "development" },
  "pycharm64.exe": { name: "PyCharm", category: "development" },
  "webstorm64.exe": { name: "WebStorm", category: "development" },
  "clion64.exe": { name: "CLion", category: "development" },
  "goland64.exe": { name: "GoLand", category: "development" },
  "rider64.exe": { name: "Rider", category: "development" },
  "devenv.exe": { name: "Visual Studio", category: "development" },
  "sublime_text.exe": { name: "Sublime Text", category: "development" },
  "notepad++.exe": { name: "Notepad++", category: "development" },
  "vim.exe": { name: "Vim", category: "development" },
  "nvim.exe": { name: "Neovim", category: "development" },

  "wechat.exe": { name: "微信", category: "communication" },
  "weixin.exe": { name: "微信", category: "communication" },
  "qq.exe": { name: "QQ", category: "communication" },
  "qqnt.exe": { name: "QQ", category: "communication" },
  "discord.exe": { name: "Discord", category: "communication" },
  "slack.exe": { name: "Slack", category: "communication" },
  "telegram.exe": { name: "Telegram", category: "communication" },
  "lark.exe": { name: "飞书", category: "communication" },
  "dingtalk.exe": { name: "钉钉", category: "communication" },
  "teams.exe": { name: "Microsoft Teams", category: "meeting" },
  "zoom.exe": { name: "Zoom", category: "meeting" },
  "todesk.exe": { name: "ToDesk", category: "utility" },
  "teamviewer.exe": { name: "TeamViewer", category: "utility" },
  "anydesk.exe": { name: "AnyDesk", category: "utility" },

  "wps.exe": { name: "WPS Office", category: "office" },
  "wpsoffice.exe": { name: "WPS Office", category: "office" },
  "et.exe": { name: "WPS 表格", category: "office" },
  "wpp.exe": { name: "WPS 演示", category: "office" },
  "winword.exe": { name: "Word", category: "office" },
  "excel.exe": { name: "Excel", category: "office" },
  "powerpnt.exe": { name: "PowerPoint", category: "office" },
  "onenote.exe": { name: "OneNote", category: "office" },
  "obsidian.exe": { name: "Obsidian", category: "reading" },
  "notion.exe": { name: "Notion", category: "office" },
  "typora.exe": { name: "Typora", category: "reading" },
  "zotero.exe": { name: "Zotero", category: "reading" },

  "spotify.exe": { name: "Spotify", category: "music" },
  "vlc.exe": { name: "VLC Player", category: "video" },
  "steam.exe": { name: "Steam", category: "game" },
  "epicgameslauncher.exe": { name: "Epic Games", category: "game" },
  "leagueclient.exe": { name: "League of Legends", category: "game" },
  "valorant.exe": { name: "Valorant", category: "game" },
  "csgo.exe": { name: "CS:GO", category: "game" },
  "cs2.exe": { name: "CS2", category: "game" },
  "bilibili.exe": { name: "哔哩哔哩", category: "video" },
  "douyin.exe": { name: "抖音", category: "video" },
  "qqmusic.exe": { name: "QQ Music", category: "music" },
  "neteasemusic.exe": { name: "NetEase Music", category: "music" },
  "hoyoplay.exe": { name: "HoYoPlay", category: "game" },

  "powershell.exe": { name: "PowerShell", category: "system" },
  "pwsh.exe": { name: "PowerShell 7", category: "system" },
  "cmd.exe": { name: "Command Prompt", category: "system" },
  "windowsterminal.exe": { name: "Windows Terminal", category: "system" },
  "wt.exe": { name: "Windows Terminal", category: "system" },
  "explorer.exe": { name: "File Explorer", category: "system" },
  "taskmgr.exe": { name: "Task Manager", category: "system" },
  "regedit.exe": { name: "Registry Editor", category: "system" },
  "mmc.exe": { name: "Microsoft Management Console", category: "system" },
  "control.exe": { name: "Control Panel", category: "system" },
  "searchhost.exe": { name: "Windows Search", category: "system" },
  "shellhost.exe": { name: "Windows Shell Host", category: "system" },
  "shellexperiencehost.exe": { name: "Windows Shell", category: "system" },
  "consent.exe": { name: "UAC Prompt", category: "system" },
  "pickerhost.exe": { name: "Picker Host", category: "system" },
  "openwith.exe": { name: "Open With", category: "system" },
  "startmenuexperiencehost.exe": { name: "Start Menu Experience Host", category: "system" },
  "applicationframehost.exe": { name: "Application Frame Host", category: "system" },
  "textinputhost.exe": { name: "Text Input Host", category: "system" },
  "runtimebroker.exe": { name: "Runtime Broker", category: "system" },
  "taskhostw.exe": { name: "Task Host", category: "system" },
  "lockapp.exe": { name: "Lock Screen", category: "system" },
  "logonui.exe": { name: "Logon UI", category: "system" },
  "dwm.exe": { name: "Desktop Window Manager", category: "system" },
  "time_tracker.exe": { name: "Time Tracker", category: "system" },
  "time-tracker.exe": { name: "Time Tracker", category: "system" },
  "timetracker.exe": { name: "Time Tracker", category: "system" },
  "uninstall.exe": { name: "卸载程序", category: "system" },
  "unins000.exe": { name: "卸载程序", category: "system" },
};
