const ZH_CN_DATA_COPY = {
  data: {
    title: "数据",
    subtitle: "浏览长期活动趋势",
    pastSevenDays: "近 7 天",
    activityTrend: "活动趋势",
    weeklyTotal: "7 日总时长",
    dailyAverage: "日均时长",
    dailyAverageHint: "按近 7 天计算",
    appTrend: "应用趋势",
    webTrend: "网页趋势",
    appSearchPlaceholder: "搜索应用",
    appTrendAppList: "应用列表",
    appTrendEmpty: "当前范围暂无应用记录",
    appTrendNoMatch: "没有匹配的应用",
    appTrendTotal: "总时长",
    appTrendAverage: "日均",
    appTrendActiveDays: "活跃天数",
    appTrendPeakDay: "峰值日",
    appTrendBrowserHint: "当前数据包含浏览器使用时长，活动趋势中的应用统计已排除浏览器",
    trendRoundingHint: "列表中显示时长为取整显示，实际记录精度更高，人工合计可能与面板汇总有出入",
    webTrendSourceHint: "网页时长来源于浏览器扩展独立记录，各域名独立统计之和不等同于浏览器使用总时长",
    appTrendUsage: "应用时长",
    appTrendDayBreakdown: "每日明细",
    activityHeatmap: "活动热力图",
    activityHeatmapHint: "每日活动强度",
    heatmapDaily: "每日",
    heatmapWeekly: "每周",
    recentYear: "近一年",
    pastThirtyDays: "近 30 天",
    rangePickerTitle: "选择范围",
    pickerModes: {
      custom: "自定义",
      week: "一周",
      month: "一月",
      year: "一年",
    },
    pickStartDate: "开始日期",
    pickEndDate: "结束日期",
    pickDate: "选择日期",
    shortRangeHint: "当前范围少于 7 天。",
    applyRange: "确定",
    customDayCount: (days: number) => `${days}天`,
    weekLabel: (week: number) => `${week}周`,
    yearLabel: (year: number) => `${year}年`,
    rangeTotal: (label: string) => `${label}总时长`,
    trendTotal: (range: 7 | 30 | 365) => (
      range === 7 ? "7 日总时长" : range === 30 ? "30 日总时长" : "近一年总时长"
    ),
    yearlyAverage: "月均时长",
    yearlyAverageHint: "按近一年月份计算",
    rangeAverageHint: (rangeLabel: string) => `按${rangeLabel}计算`,
    appTime: "应用统计时间",
    webTime: "网页统计时间",
    openDetailPanel: "打开详细面板",
    notStarted: "未开始",
    duration: "时长",
    monthlyAverage: "月均",
    less: "少",
    more: "多",
  },
};

const EN_US_DATA_COPY = {
  data: {
    title: "Data",
    subtitle: "Browse long-term trends",
    pastSevenDays: "Last 7 days",
    activityTrend: "Activity Trend",
    weeklyTotal: "7-day total",
    dailyAverage: "Daily avg.",
    dailyAverageHint: "Based on last 7 days",
    appTrend: "App Trends",
    webTrend: "Web Trends",
    appSearchPlaceholder: "Search apps",
    appTrendAppList: "App list",
    appTrendEmpty: "No app data in this range",
    appTrendNoMatch: "No matching apps",
    appTrendTotal: "Total",
    appTrendAverage: "Daily avg.",
    appTrendActiveDays: "Active days",
    appTrendPeakDay: "Peak day",
    appTrendBrowserHint: "Data includes browser usage; activity trend app stats exclude browser time",
    trendRoundingHint: "Durations shown in the list are rounded for display; actual recorded values have higher precision. Manual totals may differ from the panel aggregate.",
    webTrendSourceHint: "Web time is recorded by the browser extension; per-domain sums do not equal total browser usage duration.",
    appTrendUsage: "App time",
    appTrendDayBreakdown: "Daily details",
    activityHeatmap: "Activity Heatmap",
    activityHeatmapHint: "Daily activity intensity",
    heatmapDaily: "Daily",
    heatmapWeekly: "Weekly",
    recentYear: "Past year",
    pastThirtyDays: "Last 30 days",
    rangePickerTitle: "Select range",
    pickerModes: {
      custom: "Custom",
      week: "Week",
      month: "Month",
      year: "Year",
    },
    pickStartDate: "Start date",
    pickEndDate: "End date",
    pickDate: "Select date",
    shortRangeHint: "The current range is shorter than 7 days.",
    applyRange: "Apply",
    customDayCount: (days: number) => `${days} days`,
    weekLabel: (week: number) => `Week ${week}`,
    yearLabel: (year: number) => String(year),
    rangeTotal: (label: string) => `${label} total`,
    trendTotal: (range: 7 | 30 | 365) => (
      range === 7 ? "7-day total" : range === 30 ? "30-day total" : "Past year total"
    ),
    yearlyAverage: "Monthly avg.",
    yearlyAverageHint: "Based on months in the past year",
    rangeAverageHint: (rangeLabel: string) => `Based on ${rangeLabel}`,
    appTime: "App time",
    webTime: "Web time",
    openDetailPanel: "Open detail panel",
    notStarted: "Not started",
    duration: "Duration",
    monthlyAverage: "Monthly avg.",
    less: "Less",
    more: "More",
  },
};

export const dataCopy = {
  "zh-CN": ZH_CN_DATA_COPY,
  "en-US": EN_US_DATA_COPY,
} as const;
