const ZH_CN_EXPORT_COPY = {
  export: {
    title: "数据导出",
    subtitle: "将会话和网页数据导出为通用格式",
    sidebarDescription: "导出",
    timeRangeLabel: "时间范围",
    timeRangePresetToday: "今日",
    timeRangePresetThisWeek: "本周",
    timeRangePresetThisMonth: "本月",
    timeRangePresetThisYear: "本年",
    timeRangePresetCustom: "自定义",
    timeRangeCustomStart: "开始日期",
    timeRangeCustomEnd: "结束日期",
    formatLabel: "导出格式",
    formatCSV: "CSV",
    formatCSVHint: "通用表格，Excel 直接打开。时间列显示 ##### 时拉宽列宽即可",
    formatSQLite: "SQLite",
    formatSQLiteHint: "单文件数据库，支持 SQL 自定义筛选，长期本地存储日志",
    formatParquet: "Parquet",
    formatParquetHint: "高性能压缩格式，海量数据、Python/AI 分析专用",
    recommendationTitle: "推荐",
    recommendationDaily: "按日导出 → CSV（单日快速查看，Excel 直接打开）",
    recommendationMonthly: "按月导出 → SQLite（月度精细化统计，支持 SQL 筛选）",
    recommendationYearly: "按年导出 → Parquet（全年海量归档，AI / 批量分析专用）",
    recommendationCustomShort: "自定义范围（<3 天）→ 推荐 CSV",
    recommendationCustomMedium: "自定义范围（1 个月～6 个月）→ 推荐 SQLite",
    recommendationCustomLong: "自定义范围（≥1 年）→ 推荐 Parquet",
    exportAction: "导出",
    exporting: "导出中...",
    exportDone: (count: number) => `已导出 ${count} 条记录`,
    exportFailed: "导出失败",
    pickPath: "选择保存路径",
    pathPlaceholder: "选择输出路径",
    browse: "浏览",
    configFields: "配置字段",
    configFieldsTitle: "导出字段配置",
    configFieldsHint: "拖拽排序，点击 × 移除不需要的字段",
    configFieldsReset: "恢复默认",
    configFieldsCount: (n: number, total: number) => `${n} / ${total} 个字段`,
    groupApps: "应用（来自会话记录）",
    groupWeb: "网页（来自浏览记录）",
    fields: {
      record_type: { label: "记录类型", desc: "标记来自本地应用(session)还是网页浏览(web)" },
      exe_name: { label: "可执行文件名", desc: "进程的可执行文件名称，如 chrome.exe" },
      app_name: { label: "应用名称", desc: "应用程序的显示名称，如 Google Chrome" },
      window_title: { label: "窗口标题", desc: "活动窗口的标题文字" },
      domain: { label: "域名", desc: "网页访问的域名，如 www.google.com" },
      normalized_domain: { label: "标准化域名", desc: "去除 www 前缀后的标准化域名" },
      url: { label: "URL 地址", desc: "网页的完整 URL 地址" },
      page_title: { label: "页面标题", desc: "网页的 HTML 标题" },
      start_time: { label: "开始时间", desc: "记录开始时间，格式 YYYY-MM-DD HH:mm:ss" },
      end_time: { label: "结束时间", desc: "记录结束时间，格式 YYYY-MM-DD HH:mm:ss" },
      duration_ms: { label: "持续时长(ms)", desc: "记录持续时长，单位毫秒" },
    },
  },
};

const EN_US_EXPORT_COPY = {
  export: {
    title: "Data Export",
    subtitle: "Export sessions and web activity in common formats",
    sidebarDescription: "Export",
    timeRangeLabel: "Time range",
    timeRangePresetToday: "Today",
    timeRangePresetThisWeek: "This week",
    timeRangePresetThisMonth: "This month",
    timeRangePresetThisYear: "This year",
    timeRangePresetCustom: "Custom",
    timeRangeCustomStart: "Start date",
    timeRangeCustomEnd: "End date",
    formatLabel: "Format",
    formatCSV: "CSV",
    formatCSVHint: "Universal table, open with Excel or Notepad. If timestamps show as #####, widen the column",
    formatSQLite: "SQLite",
    formatSQLiteHint: "Single-file database, supports custom SQL filtering, long-term local log storage",
    formatParquet: "Parquet",
    formatParquetHint: "High-performance columnar format, massive data, Python/AI analysis",
    recommendationTitle: "Recommendation",
    recommendationDaily: "Daily → CSV (quick daily view, open in Excel)",
    recommendationMonthly: "Monthly → SQLite (monthly fine-grained stats, SQL filtering)",
    recommendationYearly: "Yearly → Parquet (yearly archive, AI/batch analysis)",
    recommendationCustomShort: "Custom range (<3 days) → CSV recommended",
    recommendationCustomMedium: "Custom range (1 month ~ 6 months) → SQLite recommended",
    recommendationCustomLong: "Custom range (≥1 year) → Parquet recommended",
    exportAction: "Export",
    exporting: "Exporting...",
    exportDone: (count: number) => `Exported ${count} records`,
    exportFailed: "Export failed",
    pickPath: "Choose save path",
    pathPlaceholder: "Choose output path",
    browse: "Browse",
    configFields: "Configure Fields",
    configFieldsTitle: "Export Field Configuration",
    configFieldsHint: "Drag to reorder, click × to remove fields",
    configFieldsReset: "Reset to default",
    configFieldsCount: (n: number, total: number) => `${n} / ${total} fields`,
    groupApps: "Apps (from sessions)",
    groupWeb: "Web (from browsing)",
    fields: {
      record_type: { label: "Record Type", desc: "session (local app) or web (browsing)" },
      exe_name: { label: "Executable Name", desc: "Process executable filename, e.g. chrome.exe" },
      app_name: { label: "App Name", desc: "Display name of the application, e.g. Google Chrome" },
      window_title: { label: "Window Title", desc: "Active window title text" },
      domain: { label: "Domain", desc: "Website domain, e.g. www.google.com" },
      normalized_domain: { label: "Normalized Domain", desc: "Domain with www prefix stripped" },
      url: { label: "URL", desc: "Full URL of the page" },
      page_title: { label: "Page Title", desc: "HTML title of the page" },
      start_time: { label: "Start Time", desc: "Record start time (YYYY-MM-DD HH:mm:ss)" },
      end_time: { label: "End Time", desc: "Record end time (YYYY-MM-DD HH:mm:ss)" },
      duration_ms: { label: "Duration (ms)", desc: "Record duration in milliseconds" },
    },
  },
};

export const exportCopy = {
  "zh-CN": ZH_CN_EXPORT_COPY,
  "en-US": EN_US_EXPORT_COPY,
} as const;
