const ZH_CN_MAPPING_COPY = {
  mapping: {
    title: "分类",
    subtitle: "管理应用网页规则",
    saving: "正在保存...",
    idle: "已保存",
    unsaved: "有未保存更改",
    save: "保存",
    cancel: "取消",
    categoryControl: "管理分类",
    categorySelectLabel: (label: string) => `${label} 的分类`,
    loading: "加载中...",
    loadFailed: "分类数据加载失败。",
    retry: "重试",
    emptyState: "当前筛选暂无应用",
    searchNoResults: "没有找到匹配的应用",
    webEmptyState: "当前筛选暂无网页",
    appSearchPlaceholder: "搜索应用或分类",
    webSearchPlaceholder: "搜索网页或分类",
    objectModeApp: "应用",
    objectModeWeb: "网页",
    createCategoryTitle: "新建分类",
    createCategoryDescription: "建议中文 2 字，英文 1 个词。",
    createCategoryPlaceholder: "例如：学习",
    renameCategoryTitle: "重命名分类",
    renameCategoryDescription: "已使用该分类的应用和网页会显示新名称。",
    renameCategoryPlaceholder: "新的分类名称",
    renameCategoryDuplicateTitle: "合并同名分类",
    renameCategoryDuplicateDetail: (label: string) => `已存在 ${label} 分类。继续后会把当前分类并入该分类。`,
    renameCategory: (label: string) => `重命名分类：${label}`,
    deleteCategoryTitle: "删除分类",
    deleteCategoryDetail: (label: string) => `将删除 ${label} 分类。`,
    deleteCategory: (label: string) => `删除分类：${label}`,
    deleteAppSessionsTitle: "删除应用记录",
    deleteAppSessionsDetail: (label: string) => `将删除 ${label} 的全部应用记录，包括原生记录和外部导入记录。其他应用及其他导入记录不受影响。`,
    deleteWebDomainHistoryTitle: "删除网页记录",
    deleteWebDomainHistoryDetail: (label: string) => `将删除 ${label} 的网页记录。`,
    filters: {
      all: "全部",
      other: "未分类",
      classified: "已分类",
    },
    categoryDialogTitle: "管理分类",
    categoryDialogDescription: "新建分类并调整颜色",
    createCategoryAction: "新建分类",
    editAppName: "修改应用名称",
    editWebDomainName: "修改网页名称",
    color: "颜色",
    restoreDefaultColor: "恢复默认颜色",
    noStats: "已排除",
    statsEnabled: "计入统计",
    excludeStats: "排除统计",
    restoreStats: "恢复统计",
    titleNotRecorded: "屏蔽标题",
    titleRecorded: "记录标题",
    disableTitleCapture: "停止记录标题",
    enableTitleCapture: "恢复记录标题",
    globalTitleDisabled: "全局标题已关闭",
    disableTracking: "停止追踪并隐藏已有历史",
    enableTracking: "恢复追踪并重现已有历史",
    disableWebTracking: "停止追踪并隐藏已有历史",
    enableWebTracking: "恢复追踪并重现已有历史",
    deleteAppRecords: "删除应用记录",
    deleteWebRecords: "删除网页记录",
  },
};

const EN_US_MAPPING_COPY = {
  mapping: {
    ...ZH_CN_MAPPING_COPY.mapping,
    title: "Classification",
    subtitle: "Manage app and web rules",
    saving: "Saving...",
    idle: "Saved",
    unsaved: "Unsaved changes",
    save: "Save",
    cancel: "Cancel",
    categoryControl: "Manage categories",
    categorySelectLabel: (label: string) => `Category for ${label}`,
    loading: "Loading...",
    loadFailed: "Classification data failed to load.",
    retry: "Retry",
    emptyState: "No apps match the current filter",
    searchNoResults: "No matching apps found",
    webEmptyState: "No websites match the current filter",
    appSearchPlaceholder: "Search apps or categories",
    webSearchPlaceholder: "Search websites or categories",
    objectModeApp: "Apps",
    objectModeWeb: "Web",
    createCategoryTitle: "New category",
    createCategoryDescription: "Recommended: 2 CJK characters or 1 English word.",
    createCategoryPlaceholder: "Example: Study",
    renameCategoryTitle: "Rename category",
    renameCategoryDescription: "Apps and websites using this category will show the new name.",
    renameCategoryPlaceholder: "New category name",
    renameCategoryDuplicateTitle: "Merge matching category",
    renameCategoryDuplicateDetail: (label: string) => `${label} already exists. Continuing will merge this category into it.`,
    renameCategory: (label: string) => `Rename category: ${label}`,
    deleteCategoryTitle: "Delete category",
    deleteCategoryDetail: (label: string) => `This will delete the ${label} category.`,
    deleteCategory: (label: string) => `Delete category: ${label}`,
    deleteAppSessionsTitle: "Delete app records",
    deleteAppSessionsDetail: (label: string) => `All app records for ${label}, including Patina and imported records, will be deleted. Other apps and imported records are unaffected.`,
    deleteWebDomainHistoryTitle: "Delete web records",
    deleteWebDomainHistoryDetail: (label: string) => `This will delete web records for ${label}.`,
    filters: {
      all: "All",
      other: "Unclassified",
      classified: "Classified",
    },
    categoryDialogTitle: "Manage categories",
    categoryDialogDescription: "Create categories and adjust category colors",
    createCategoryAction: "New category",
    editAppName: "Edit app name",
    editWebDomainName: "Edit website name",
    color: "Color",
    restoreDefaultColor: "Restore default color",
    noStats: "Excluded",
    statsEnabled: "Included",
    excludeStats: "Exclude stats",
    restoreStats: "Restore stats",
    titleNotRecorded: "Block titles",
    titleRecorded: "Record titles",
    disableTitleCapture: "Stop recording titles",
    enableTitleCapture: "Resume recording titles",
    globalTitleDisabled: "Global titles are off",
    disableTracking: "Stop tracking and hide existing history",
    enableTracking: "Resume tracking and restore existing history",
    disableWebTracking: "Stop tracking and hide existing history",
    enableWebTracking: "Resume tracking and restore existing history",
    deleteAppRecords: "Delete records",
    deleteWebRecords: "Delete web records",
  },
};

export const mappingCopy = {
  "zh-CN": ZH_CN_MAPPING_COPY,
  "en-US": EN_US_MAPPING_COPY,
} as const;
