const ZH_CN_SETTINGS_COPY = {
  settings: {
    loading: "正在获取配置...",
    title: "设置",
    subtitle: "调整全局运行偏好",
    saving: "正在保存...",
    saved: "配置已更新",
    saveFailed: "配置保存失败，请稍后重试。",
    unsaved: "有未保存更改",
    idle: "已保存",
    save: "保存",
    cancel: "取消",
    cancelled: "已撤销本次编辑",
    tracking: "追踪",
    idleTimeoutLabel: "持续计入时间",
    idleTimeoutHint: "当前应用有音频等持续信号时，继续计入这段时间。",
    timelineMergeGapLabel: "活动保持时间",
    timelineMergeGapHint: "无操作后停止计时；短暂切屏返回，时间线保持连续。",
    performance: "性能",
    refreshLabel: "刷新间隔",
    refreshHint: "前端界面从后端拉取最新数据的时间间隔。",
    refreshWarning: "较短的刷新频率会增加一定的 CPU 开销。如果你发现界面有些延迟，建议设置为 5s 及以上。",
    cleanup: "数据管理",
    cleanupTitle: "清理历史记录",
    cleanupHint: "删除所选时间及以前的活动记录，操作无法撤销。",
    cleanupRangeLabel: "清理时间",
    decreaseCleanupRange: "缩短清理范围",
    increaseCleanupRange: "延长清理范围",
    cleanupRunning: "正在清理...",
    cleanupNow: "清理",
    cleanupConfirmTitle: "确认清理历史记录",
    cleanupConfirmDetail: (label: string) => `将删除 ${label} 及以前的活动记录。`,
    restoreConfirmTitle: "恢复备份",
    restoreConfirmDetail: (path: string, summary: string, strategy: string) => `恢复策略：${strategy}\n目标文件：${path}\n\n${summary}`,
    confirmRangeFallback: "所选时间",
    cleanupRangeLabels: {
      180: "180 天前",
      90: "90 天前",
      60: "60 天前",
      30: "30 天前",
      15: "15 天前",
      7: "7 天前",
    } as Record<number, string>,
    refreshPresets: {
      1: "实时 (1s)",
      3: "平衡 (3s)",
      5: "省电 (5s)",
      10: "低频 (10s)",
    } as Record<number, string>,
    minutePresets: {
      60: "1 分钟",
      180: "3 分钟",
      300: "5 分钟",
      600: "10 分钟",
    } as Record<number, string>,
    trackingPanelTitle: "追踪",
    trackingPausedLabel: "暂停追踪",
    trackingPausedHint: "暂停后不再写入新记录，恢复后继续追踪。",
    globalTitleLabel: "全局标题",
    globalTitleHint: "保存应用窗口标题和网页标题，用于历史活动明细。",
    residentTitle: "常驻",
    minimizeToWidgetLabel: "最小化到挂件",
    minimizeToWidgetHint: "最小化时隐藏主窗口，并显示侧边挂件。",
    closeToTrayLabel: "关闭到托盘",
    closeToTrayHint: "关闭窗口时隐藏主窗口，并继续在后台运行。",
    backgroundOptimizationLabel: "低耗后台",
    backgroundOptimizationHint: "后台闲置时释放主界面内存；再次打开可能略有延迟。",
    launchAtLoginLabel: "开机自启动",
    launchAtLoginHint: "系统登录后自动启动应用。",
    startMinimizedLabel: "静默启动",
    startMinimizedHint: "仅随开机自启动生效；启动后隐藏主窗口。",
    servicesTitle: "服务",
    webActivityTitle: "网页同步",
    webActivityEnabledLabel: "网页同步",
    webActivityEnabledHint: "通过浏览器扩展接收当前活动网页。",
    webActivityAddressLabel: "端口",
    webActivityTokenLabel: "Token",
    webActivityHelpAction: "使用说明",
    webActivityHelpCopiedAction: "已复制",
    webActivityHelpCopyPortAction: "复制端口",
    webActivityHelpCopyTokenAction: "复制 Token",
    webActivityHelpTitle: "网页同步使用说明",
    webActivityHelpDescription: "Patina Web Sync 会把当前活动网页同步到本机 Patina。",
    webActivityHelpSteps: [
      {
        title: "准备连接信息",
        description: "扩展需要使用本页的端口和 Token 连接本机 Patina。",
        details: [
          "复制端口和 Token，稍后粘贴到扩展设置中。",
        ],
      },
      {
        title: "安装浏览器扩展",
        description: "从 Patina Web Sync 发布页获取对应浏览器系的扩展包。",
        details: [
          {
            text: "从 Patina Web Sync 发布页获取扩展包。",
            links: [
              {
                label: "打开下载页",
                href: "https://github.com/Ceceliaee/patina-web-sync/releases/latest",
              },
            ],
          },
          {
            text: "Chromium 系：",
            children: [
              "下载 patina-chromium-extension-v...zip。",
              "解压后得到 patina-chromium-extension-v... 文件夹。",
              "在地址栏输入 chrome://extensions/ 或 edge://extensions/，开启「开发者模式」。",
              "点击「加载已解压的扩展程序」或「加载解压缩的扩展」。",
              "选择解压得到的 patina-chromium-extension-v... 文件夹（包含 manifest.json）。",
            ],
          },
          {
            text: "Firefox 系：",
            children: [
              "下载 patina-firefox-extension-v...xpi。",
              "在地址栏输入 about:addons，进入附加组件管理器。",
              "点击齿轮按钮，选择「从文件安装附加组件」。",
              "选择下载的 .xpi 文件，并在提示中点击「添加」。",
            ],
          },
        ],
      },
      {
        title: "配置扩展",
        description: "打开 Patina Web Sync 设置页，填入本页显示的连接信息。",
        details: [
          "打开浏览器工具栏里的「扩展程序」菜单。",
          "找到 Patina Web Sync 并打开它。",
          "在弹出的扩展窗口中点击「设置」。",
          "粘贴本页显示的端口和 Token。",
          "也可以从扩展管理页进入：找到 Patina Web Sync，点击「详情」/「详细信息」，再点击「扩展程序选项」。",
        ],
      },
      {
        title: "同步当前页",
        description: "打开常规网页后，扩展会同步当前活动页。",
        details: [
          "打开一个 http/https 网页。",
          "等待 Patina Web Sync 自动同步当前页。",
          "如需立即同步一次，可在扩展弹窗中点击「同步当前页」。",
        ],
      },
    ],
    webActivityHelpNote: "Patina Web Sync 启用并连接成功后：\n• 自动同步当前活动标签页的网站地址、标题和网站图标。\n• 不读取网页正文、表单内容、截图或剪贴板。\n• 不扫描或导入浏览器历史记录。\n• 无痕模式窗口不会写入网页记录。",
    remoteStatusBridgeTitle: "远程推送",
    remoteStatusBridgeEnabledHint: "向接收地址推送当前追踪状态。",
    remoteStatusBridgeUrlLabel: "接收地址",
    remoteStatusBridgeTokenLabel: "Token",
    remoteStatusBridgeMachineIdLabel: "本机标识",
    countValue: (count: number) => `${count} 个`,
    appearanceTitle: "外观",
    themeModeOptions: {
      light: "浅色",
      dark: "深色",
      system: "跟随系统",
    },
    themeLibraryOptions: {
      light: "浅色主题",
      dark: "深色主题",
    },
    betaLabel: "Beta",
    themeModeLabel: "主题模式",
    themeModeHint: "浅色、深色，或跟随系统外观自动切换。",
    languageLabel: "语言",
    languageHint: "切换界面显示语言。",
    languageOptions: {
      zhCN: "中文",
      enUS: "English",
    },
    colorSchemeLabel: "配色方案",
    colorSchemeHint: "分别调整浅色和深色主题配色。",
    dynamicEffectsLabel: "灵动视效",
    dynamicEffectsHint: "显示界面切换和操作反馈动效。",
    colorSchemeDialogFallbackTitle: "主题",
    colorSchemeDialogDescription: "选择后即时预览，确认后保存。",
    colorSchemeSaving: "保存中",
    dataSafetyTitle: "存储",
    backupRestoreTitle: "备份与恢复",
    backupRestoreHint: "备份本机数据快照；恢复时可选择覆盖或合并当前数据。",
    backupExportTitle: "备份",
    backupExportHint: "导出当前数据快照",
    backupExporting: "备份中...",
    backupExportAction: "备份",
    dataExportTitle: "数据导入与导出",
    dataExportHint: "导出已有记录，或将通用 CSV 数据导入 Patina。",
    dataExportAction: "导出",
    dataImportAction: "导入",
    dataImportActionHint: "导入 Patina 通用 CSV，或先解构 Tai/Taix 数据",
    importExactCount: (count: number) => `${count} 条精确记录`,
    importHourCount: (count: number) => `${count} 条小时汇总`,
    dataImport: {
      dialogDescription: "通用导入只读取 Patina CSV；外部文件需要先解构。",
      csvTitle: "导入 CSV",
      csvHint: "选择 Patina 通用 CSV，预览并校验后写入。",
      chooseAction: "选择文件",
      destructureTitle: "解构外部数据",
      destructureHint: "识别 Tai/Taix 的 CSV 或 SQLite 数据库，并在原文件同级生成 Patina CSV。",
      destructureAction: "解构",
      previewTitle: "确认导入",
      previewDescription: "这里只显示文件实际包含的数据类型，不补造缺失信息。",
      availableLabel: "可导入",
      exactLabel: "精确记录",
      hourLabel: "小时汇总",
      duplicateLabel: "重复跳过",
      errorLabel: "无效跳过",
      hourNote: "小时汇总只参与排行与统计，不会显示为精确时间线。",
      lineError: (line: number, message: string) => `第 ${line} 行：${message}`,
      batchesTitle: "删除外部导入数据",
      batchesDescription: "仅删除所选导入批次；Patina 自己记录的数据不会受影响。",
      backAction: "返回导入",
      batchTitle: (number: number) => `第 ${number} 次导入`,
      deleteBatchAction: (number: number) => `删除第 ${number} 次导入`,
      deleteConfirmTitle: "删除这次导入？",
      deleteConfirmDescription: (sourceName: string) => `将删除来自 ${sourceName} 的全部外部记录。此操作无法撤销。`,
      deleteConfirmAction: "删除",
    },
    backupRestoreActionTitle: "恢复",
    backupRestoreActionHint: "从备份恢复数据",
    backupRestoreActionHelp: "旧版备份恢复保留截止日期将在正式发布后确定。",
    backupTargetTitle: "选择备份位置",
    backupTargetHint: "选择保存到本地文件，或上传到已绑定的 WebDAV。",
    backupTargetLocalTitle: "本地备份",
    backupTargetLocalHint: "保存为本机 zip 文件",
    backupTargetRemoteTitle: "WebDAV 备份",
    backupTargetRemoteHint: "上传到已绑定的 WebDAV",
    restoreSourceTitle: "选择恢复来源",
    restoreSourceHint: "选择本地备份文件，或从已绑定的 WebDAV 下载。",
    restoreSourceLocalTitle: "本地恢复",
    restoreSourceLocalHint: "选择本机 zip 文件",
    restoreSourceRemoteTitle: "WebDAV 恢复",
    restoreSourceRemoteHint: "从已绑定的 WebDAV 选择备份",
    remoteBackupTitle: "WebDAV 配置",
    remoteBackupHint: "绑定 WebDAV，用于远程备份。",
    webDavConfigure: "配置",
    webDavEdit: "编辑",
    webDavConfigTitle: "WebDAV 配置",
    webDavConfigDescription: "仅用于远程备份，不会作为云同步使用。",
    webDavServerUrl: "服务器地址",
    webDavUsername: "用户名",
    webDavPassword: "应用密码",
    webDavTestConnection: "测试连接",
    webDavTesting: "测试中...",
    webDavUploadBackup: "上传备份",
    webDavUploading: "上传中...",
    webDavRestoreBackup: "从远端恢复",
    webDavLoadingBackups: "加载中...",
    webDavRestoreSelected: "恢复",
    webDavDeleteTitle: "删除 WebDAV 配置",
    webDavDeleteDetail: "这只会删除本机保存的 WebDAV 配置和密码，不会删除远端备份文件。",
    webDavDeleteAction: "删除",
    webDavRemoteBackupsTitle: "远程备份",
    webDavRemoteBackupsDescription: "选择一份远端备份；下载后会先校验是否可恢复，再确认恢复。",
    webDavRemoteBackupsEmpty: "远端暂无可用备份。",
    restoreStrategyLabel: "恢复策略",
    restoreStrategyHint: "选择恢复时如何处理当前数据。",
    restoreStrategyOptions: {
      replace: "覆盖",
      merge: "合并",
    },
    restoreStrategyOptionHints: {
      replace: "恢复后仅保留备份数据",
      merge: "保留当前数据并去重",
    },
    backupRestoring: "恢复中...",
    backupRestoreAction: "恢复",
    minuteValue: (minutes: number) => `${minutes} 分钟`,
    decreaseMinute: (label: string) => `${label}减少 1 分钟`,
    increaseMinute: (label: string) => `${label}增加 1 分钟`,
    storage: {
      storageDirectoryTitle: "本机目录",
      storageDirectoryBetaLabel: "Beta",
      storageDirectorySummary: "安装目录随应用安装位置确定；数据目录和缓存目录可单独调整。",
      storageSnapshotRefreshAction: "检查存储",
      storageSnapshotRefreshFailed: "无法检查存储目录。",
      changePathAction: "更改目录",
      restoreDefaultPathAction: "恢复默认目录",
      installDirectoryLabel: "安装目录",
      dataDirectoryLabel: "数据目录",
      webviewCacheDirectoryLabel: "缓存目录",
      openDirectoryAction: "打开目录",
      restartAndApplyAction: "重启并应用",
      storageDataMigrationConfirmTitle: "更改数据目录",
      storageDataMigrationConfirmDetail: (currentDataRoot: string, targetDataRoot: string) => (
        `当前目录：${currentDataRoot}\n目标目录：${targetDataRoot}\n\nPatina 将保存当前记录并重新启动，然后把数据迁移到目标目录。迁移完成前，请不要删除或移动当前目录和目标目录。`
      ),
      storageCacheMigrationConfirmTitle: "更改缓存目录",
      storageCacheMigrationConfirmDetail: (currentWebviewRoot: string, targetWebviewRoot: string) => (
        `当前缓存：${currentWebviewRoot}\n目标缓存：${targetWebviewRoot}\n\nPatina 将保存当前记录并重新启动，然后使用目标缓存目录。完成前，请不要删除或移动目标目录。`
      ),
      storageMigrationConfirmAction: "确认更改",
      storageRestoreDefaultDataConfirmDetail: (currentDataRoot: string, defaultDataRoot: string) => (
        `当前数据：${currentDataRoot}\n默认数据：${defaultDataRoot}\n\nPatina 将保存当前记录并重新启动，然后把数据迁移到默认目录。迁移完成前，请不要删除或移动当前目录和默认目录。`
      ),
      storageRestoreDefaultCacheConfirmDetail: (currentWebviewRoot: string, defaultWebviewRoot: string) => (
        `当前缓存：${currentWebviewRoot}\n默认缓存：${defaultWebviewRoot}\n\nPatina 将保存当前记录并重新启动，然后恢复默认缓存目录。完成前，请不要删除或移动默认目录。`
      ),
      webviewCacheClearTitle: "清理缓存",
      webviewCacheClearConfirmTitle: "重启并清理缓存？",
      webviewCacheClearConfirmDetail: "Patina 将保存当前记录并重新启动，在创建窗口前清理可重新生成的 WebView 缓存。",
      webviewCacheClearFailed: "无法准备缓存清理，请重试。",
      storageMigrationFailed: "无法准备重启，请检查目标目录。",
      storageOpenDirectoryFailed: "无法打开该目录。",
    },
  },
};

const EN_US_SETTINGS_COPY = {
  settings: {
    ...ZH_CN_SETTINGS_COPY.settings,
    loading: "Loading settings...",
    title: "Settings",
    subtitle: "Adjust global runtime preferences",
    saving: "Saving...",
    saved: "Settings updated",
    saveFailed: "Could not save settings. Try again later.",
    unsaved: "Unsaved changes",
    idle: "Saved",
    save: "Save",
    cancel: "Cancel",
    cancelled: "Edits discarded",
    tracking: "Tracking",
    idleTimeoutLabel: "Continue counting",
    idleTimeoutHint: "When the current app has audio or similar signals, keep counting that time.",
    timelineMergeGapLabel: "Activity hold time",
    timelineMergeGapHint: "Stop counting after idle time; briefly switching away and back keeps the timeline continuous.",
    performance: "Performance",
    refreshLabel: "Refresh interval",
    refreshHint: "How often the interface pulls fresh data from the backend.",
    refreshWarning: "Shorter refresh intervals can increase CPU usage. Use 5s or above if the UI feels slow.",
    cleanup: "Data management",
    cleanupTitle: "Clear history records",
    cleanupHint: "Delete activity records from the selected time and earlier. This cannot be undone.",
    cleanupRangeLabel: "Clear time",
    decreaseCleanupRange: "Shorten clear range",
    increaseCleanupRange: "Extend clear range",
    cleanupRunning: "Clearing...",
    cleanupNow: "Clear",
    cleanupConfirmTitle: "Confirm history cleanup",
    cleanupConfirmDetail: (label: string) => `Activity records from ${label} and earlier will be deleted.`,
    restoreConfirmTitle: "Restore backup",
    restoreConfirmDetail: (path: string, summary: string, strategy: string) => `Restore strategy: ${strategy}\nTarget file: ${path}\n\n${summary}`,
    confirmRangeFallback: "selected range",
    cleanupRangeLabels: {
      180: "180 days ago",
      90: "90 days ago",
      60: "60 days ago",
      30: "30 days ago",
      15: "15 days ago",
      7: "7 days ago",
    } as Record<number, string>,
    refreshPresets: {
      1: "Realtime (1s)",
      3: "Balanced (3s)",
      5: "Battery saver (5s)",
      10: "Low frequency (10s)",
    } as Record<number, string>,
    minutePresets: {
      60: "1 minute",
      180: "3 minutes",
      300: "5 minutes",
      600: "10 minutes",
    } as Record<number, string>,
    trackingPanelTitle: "Tracking",
    trackingPausedLabel: "Pause tracking",
    trackingPausedHint: "Paused tracking will stop writing new records. Resume to continue tracking.",
    globalTitleLabel: "Global titles",
    globalTitleHint: "Save application window titles and webpage titles for activity history details.",
    residentTitle: "Resident",
    minimizeToWidgetLabel: "Minimize to widget",
    minimizeToWidgetHint: "Hide the main window and show the side widget when minimized.",
    closeToTrayLabel: "Close to tray",
    closeToTrayHint: "Hide the main window and keep running in the background when closed.",
    backgroundOptimizationLabel: "Low-footprint background",
    backgroundOptimizationHint: "Release main UI memory while idle in the background. Reopening may feel slightly slower.",
    launchAtLoginLabel: "Launch at login",
    launchAtLoginHint: "Start the app automatically after Windows sign-in.",
    startMinimizedLabel: "Launch silently",
    startMinimizedHint: "Only applies to launch at login. Hide the main window after startup.",
    servicesTitle: "Services",
    webActivityTitle: "Web sync",
    webActivityEnabledLabel: "Web sync",
    webActivityEnabledHint: "Receives active web pages from the browser extension.",
    webActivityAddressLabel: "Port",
    webActivityTokenLabel: "Token",
    webActivityHelpAction: "Guide",
    webActivityHelpCopiedAction: "Copied",
    webActivityHelpCopyPortAction: "Copy port",
    webActivityHelpCopyTokenAction: "Copy Token",
    webActivityHelpTitle: "Web Sync Guide",
    webActivityHelpDescription: "Patina Web Sync sends the active webpage to the local Patina desktop app.",
    webActivityHelpSteps: [
      {
        title: "Prepare connection details",
        description: "The extension uses this page's port and Token to connect to the local Patina app.",
        details: [
          "Copy the port and Token, then paste them into the extension settings later.",
        ],
      },
      {
        title: "Install the browser extension",
        description: "Download the extension package for your browser family from Patina Web Sync releases.",
        details: [
          {
            text: "Download the extension packages from the Patina Web Sync releases page.",
            links: [
              {
                label: "Open downloads",
                href: "https://github.com/Ceceliaee/patina-web-sync/releases/latest",
              },
            ],
          },
          {
            text: "Chromium-based browsers:",
            children: [
              "Download patina-chromium-extension-v...zip.",
              "Extract it to get the patina-chromium-extension-v... folder.",
              "Enter chrome://extensions/ or edge://extensions/, then enable Developer mode.",
              "Click Load unpacked or Load extracted extension.",
              "Select the extracted patina-chromium-extension-v... folder that contains manifest.json.",
            ],
          },
          {
            text: "Firefox-based browsers:",
            children: [
              "Download patina-firefox-extension-v...xpi.",
              "Enter about:addons in the address bar to open the add-ons manager.",
              "Click the cog button, then choose Install Add-on From File.",
              "Select the downloaded .xpi file, then click Add when prompted.",
            ],
          },
        ],
      },
      {
        title: "Configure the extension",
        description: "Open the Patina Web Sync settings page and enter the connection details shown here.",
        details: [
          "Open the Extensions menu in the browser toolbar.",
          "Find Patina Web Sync and open it.",
          "Click Settings in the extension popup.",
          "Paste the port and Token shown on this page.",
          "You can also enter from the extensions management page: find Patina Web Sync, click Details, then click Extension options.",
        ],
      },
      {
        title: "Sync the current page",
        description: "After you open a regular webpage, the extension syncs the active page.",
        details: [
          "Open an http/https webpage.",
          "Wait for Patina Web Sync to automatically sync the current page.",
          "To sync once immediately, click Sync current page in the extension popup.",
        ],
      },
    ],
    webActivityHelpNote: "After Patina Web Sync is enabled and connected:\n• Automatically syncs the active tab's website address, title, and website icon.\n• Does not read page body content, form values, screenshots, or clipboard contents.\n• Does not scan or import browser history.\n• Incognito windows are not written to web records.",
    remoteStatusBridgeTitle: "Remote push",
    remoteStatusBridgeEnabledHint: "Push the current tracking status to the endpoint.",
    remoteStatusBridgeUrlLabel: "Endpoint URL",
    remoteStatusBridgeTokenLabel: "Token",
    remoteStatusBridgeMachineIdLabel: "Device ID",
    countValue: (count: number) => `${count}`,
    appearanceTitle: "Appearance",
    themeModeOptions: {
      light: "Light",
      dark: "Dark",
      system: "System",
    },
    themeLibraryOptions: {
      light: "Light theme",
      dark: "Dark theme",
    },
    themeModeLabel: "Theme mode",
    themeModeHint: "Light, dark, or follow the system appearance.",
    languageLabel: "Language",
    languageHint: "Change the interface language.",
    languageOptions: {
      zhCN: "中文",
      enUS: "English",
    },
    colorSchemeLabel: "Color scheme",
    colorSchemeHint: "Adjust light and dark theme colors separately.",
    dynamicEffectsLabel: "Dynamic effects",
    dynamicEffectsHint: "Show motion for view changes and interaction feedback.",
    colorSchemeDialogFallbackTitle: "Theme",
    colorSchemeDialogDescription: "Preview immediately. Confirm to save.",
    colorSchemeSaving: "Saving",
    dataSafetyTitle: "Storage",
    backupRestoreTitle: "Backup and restore",
    backupRestoreHint: "Back up a local data snapshot. Restore can replace or merge with current data.",
    backupExportTitle: "Back up",
    backupExportHint: "Export a snapshot of current data",
    backupExporting: "Backing up...",
    backupExportAction: "Back up",
    dataExportTitle: "Data import and export",
    dataExportHint: "Export existing records or import canonical CSV data into Patina.",
    dataExportAction: "Export",
    dataImportAction: "Import",
    dataImportActionHint: "Import a Patina CSV or destructure Tai/Taix data first",
    importExactCount: (count: number) => `${count} exact records`,
    importHourCount: (count: number) => `${count} hourly totals`,
    dataImport: {
      dialogDescription: "Canonical import accepts Patina CSV only. Destructure external files first.",
      csvTitle: "Import CSV",
      csvHint: "Choose a Patina CSV. It will be previewed and validated before writing.",
      chooseAction: "Choose file",
      destructureTitle: "Destructure external data",
      destructureHint: "Recognize Tai/Taix CSV or SQLite data and generate a Patina CSV beside the source file.",
      destructureAction: "Destructure",
      previewTitle: "Confirm import",
      previewDescription: "Only data types present in the file are shown; missing information is not invented.",
      availableLabel: "Ready",
      exactLabel: "Exact records",
      hourLabel: "Hourly totals",
      duplicateLabel: "Duplicates skipped",
      errorLabel: "Invalid rows skipped",
      hourNote: "Hourly totals contribute to rankings and statistics, but not the exact timeline.",
      lineError: (line: number, message: string) => `Line ${line}: ${message}`,
      batchesTitle: "Delete external imported data",
      batchesDescription: "Only the selected import batch is deleted. Patina's own records are untouched.",
      backAction: "Back to import",
      batchTitle: (number: number) => `Import ${number}`,
      deleteBatchAction: (number: number) => `Delete import ${number}`,
      deleteConfirmTitle: "Delete this import?",
      deleteConfirmDescription: (sourceName: string) => `All external records from ${sourceName} will be deleted. This cannot be undone.`,
      deleteConfirmAction: "Delete",
    },
    backupRestoreActionTitle: "Restore",
    backupRestoreActionHint: "Restore data from a backup",
    backupRestoreActionHelp: "The cutoff date for restoring older backups will be set at release.",
    backupTargetTitle: "Choose backup location",
    backupTargetHint: "Save a local file or upload to the linked WebDAV target.",
    backupTargetLocalTitle: "Local backup",
    backupTargetLocalHint: "Save as a local zip file",
    backupTargetRemoteTitle: "WebDAV backup",
    backupTargetRemoteHint: "Upload to the linked WebDAV target",
    restoreSourceTitle: "Choose restore source",
    restoreSourceHint: "Choose a local backup file or download from the linked WebDAV target.",
    restoreSourceLocalTitle: "Local restore",
    restoreSourceLocalHint: "Choose a local zip file",
    restoreSourceRemoteTitle: "WebDAV restore",
    restoreSourceRemoteHint: "Choose a backup from the linked WebDAV target",
    remoteBackupTitle: "WebDAV configuration",
    remoteBackupHint: "Link WebDAV for remote backups.",
    webDavConfigure: "Configure",
    webDavEdit: "Edit",
    webDavConfigTitle: "WebDAV configuration",
    webDavConfigDescription: "Used only for remote backup, not cloud sync.",
    webDavServerUrl: "Server address",
    webDavUsername: "Username",
    webDavPassword: "App password",
    webDavTestConnection: "Test connection",
    webDavTesting: "Testing...",
    webDavUploadBackup: "Upload backup",
    webDavUploading: "Uploading...",
    webDavRestoreBackup: "Restore from remote",
    webDavLoadingBackups: "Loading...",
    webDavRestoreSelected: "Restore",
    webDavDeleteTitle: "Delete WebDAV configuration",
    webDavDeleteDetail: "This only removes the local WebDAV settings and password. Remote backup files are not deleted.",
    webDavDeleteAction: "Delete",
    webDavRemoteBackupsTitle: "Remote backups",
    webDavRemoteBackupsDescription: "Choose a remote backup. It will be downloaded, previewed for compatibility, then confirmed for restore.",
    webDavRemoteBackupsEmpty: "No remote backups available.",
    restoreStrategyLabel: "Restore strategy",
    restoreStrategyHint: "Choose how restore handles current data.",
    restoreStrategyOptions: {
      replace: "Replace",
      merge: "Merge",
    },
    restoreStrategyOptionHints: {
      replace: "Keep backup data only after restoring",
      merge: "Keep current data and deduplicate",
    },
    backupRestoring: "Restoring...",
    backupRestoreAction: "Restore",
    minuteValue: (minutes: number) => `${minutes} min`,
    decreaseMinute: (label: string) => `Decrease ${label} by 1 minute`,
    increaseMinute: (label: string) => `Increase ${label} by 1 minute`,
    storage: {
      storageDirectoryTitle: "Local paths",
      storageDirectoryBetaLabel: "Beta",
      storageDirectorySummary: "Install folder follows the app install location; data and cache folders can be adjusted separately.",
      storageSnapshotRefreshAction: "Check storage",
      storageSnapshotRefreshFailed: "Could not check storage folders.",
      changePathAction: "Change location",
      restoreDefaultPathAction: "Restore default location",
      installDirectoryLabel: "Install folder",
      dataDirectoryLabel: "Data folder",
      webviewCacheDirectoryLabel: "Cache folder",
      openDirectoryAction: "Open folder",
      restartAndApplyAction: "Restart and apply",
      storageDataMigrationConfirmTitle: "Change data folder",
      storageDataMigrationConfirmDetail: (currentDataRoot: string, targetDataRoot: string) => (
        `Current folder: ${currentDataRoot}\nTarget folder: ${targetDataRoot}\n\nPatina will save the current record, restart, and migrate the data to the target folder. Do not move or delete either folder until migration finishes.`
      ),
      storageCacheMigrationConfirmTitle: "Change cache folder",
      storageCacheMigrationConfirmDetail: (currentWebviewRoot: string, targetWebviewRoot: string) => (
        `Current cache: ${currentWebviewRoot}\nTarget cache: ${targetWebviewRoot}\n\nPatina will save the current record, restart, and use the target cache folder. Do not move or delete the target folder until this finishes.`
      ),
      storageMigrationConfirmAction: "Confirm change",
      storageRestoreDefaultDataConfirmDetail: (currentDataRoot: string, defaultDataRoot: string) => (
        `Current data: ${currentDataRoot}\nDefault data: ${defaultDataRoot}\n\nPatina will save the current record, restart, and migrate the data to the default folder. Do not move or delete either folder until migration finishes.`
      ),
      storageRestoreDefaultCacheConfirmDetail: (currentWebviewRoot: string, defaultWebviewRoot: string) => (
        `Current cache: ${currentWebviewRoot}\nDefault cache: ${defaultWebviewRoot}\n\nPatina will save the current record, restart, and restore the default cache folder. Do not move or delete the default folder until this finishes.`
      ),
      webviewCacheClearTitle: "Clear cache",
      webviewCacheClearConfirmTitle: "Restart and clear cache?",
      webviewCacheClearConfirmDetail: "Patina will save the current record, restart, and clear regenerable WebView cache before creating the window.",
      webviewCacheClearFailed: "Could not prepare cache cleanup. Try again.",
      storageMigrationFailed: "Could not prepare the restart. Check the target folder.",
      storageOpenDirectoryFailed: "Could not open that folder.",
    },
  },
};

export const settingsCopy = {
  "zh-CN": ZH_CN_SETTINGS_COPY,
  "en-US": EN_US_SETTINGS_COPY,
} as const;
