const ZH_CN_SETTINGS_COPY = {
  settings: {
    loading: "正在获取配置...",
    title: "设置",
    subtitle: "调整全局运行偏好",
    saving: "正在保存...",
    saved: "配置已更新",
    saveFailed: "配置保存失败，请稍后重试。",
    unsaved: "有未保存更改",
    idle: "已保存",
    save: "保存",
    cancel: "取消",
    cancelled: "已撤销本次编辑",
    tracking: "追踪",
    idleTimeoutLabel: "持续计入时间",
    idleTimeoutHint: "当前应用有音频等持续信号时，继续计入这段时间。",
    timelineMergeGapLabel: "活动保持时间",
    timelineMergeGapHint: "无操作后停止计时；短暂切屏返回，时间线保持连续。",
    performance: "性能",
    refreshLabel: "刷新间隔",
    refreshHint: "前端界面从后端拉取最新数据的时间间隔。",
    refreshWarning: "较短的刷新频率会增加一定的 CPU 开销。如果你发现界面有些卡顿，建议设置为 5s 及以上。",
    cleanup: "数据管理",
    cleanupTitle: "清理历史记录",
    cleanupHint: "删除所选时间及以前的活动记录，操作无法撤销。",
    cleanupRangeLabel: "清理时间",
    decreaseCleanupRange: "缩短清理范围",
    increaseCleanupRange: "延长清理范围",
    cleanupRunning: "正在清理...",
    cleanupNow: "清理",
    cleanupConfirmTitle: "确认清理历史记录",
    cleanupConfirmDetail: (label: string) => `将删除 ${label} 及以前的活动记录。`,
    restoreConfirmTitle: "恢复备份",
    restoreConfirmDetail: (path: string, summary: string, strategy: string) => `恢复策略：${strategy}\n目标文件：${path}\n\n${summary}`,
    confirmRangeFallback: "所选时间",
    cleanupRangeLabels: {
      180: "180 天前",
      90: "90 天前",
      60: "60 天前",
      30: "30 天前",
      15: "15 天前",
      7: "7 天前",
    } as Record<number, string>,
    refreshPresets: {
      1: "实时 (1s)",
      3: "平衡 (3s)",
      5: "省电 (5s)",
      10: "低频 (10s)",
    } as Record<number, string>,
    minutePresets: {
      60: "1 分钟",
      180: "3 分钟",
      300: "5 分钟",
      600: "10 分钟",
    } as Record<number, string>,
    trackingPanelTitle: "追踪",
    trackingPausedLabel: "暂停追踪",
    trackingPausedHint: "暂停后不再写入新记录，恢复后继续追踪。",
    residentTitle: "常驻",
    minimizeToWidgetLabel: "最小化到挂件",
    minimizeToWidgetHint: "最小化时隐藏主窗口，并显示侧边挂件。",
    closeToTrayLabel: "关闭到托盘",
    closeToTrayHint: "关闭窗口时隐藏主窗口，并继续在后台运行。",
    backgroundOptimizationLabel: "低耗后台",
    backgroundOptimizationHint: "后台闲置时释放主界面内存；再次打开可能略有卡顿。",
    launchAtLoginLabel: "开机自启动",
    launchAtLoginHint: "系统登录后自动启动应用。",
    startMinimizedLabel: "启动时最小化",
    startMinimizedHint: "仅随开机自启动生效；启动后隐藏主窗口。",
    servicesTitle: "服务",
    webActivityTitle: "网页同步",
    webActivityEnabledLabel: "网页同步",
    webActivityEnabledHint: "通过浏览器扩展接收当前活动网页。",
    webActivityAddressLabel: "端口",
    webActivityTokenLabel: "Token",
    webActivityHelpAction: "使用说明",
    webActivityHelpCopiedAction: "已复制",
    webActivityHelpCopyPortAction: "复制端口",
    webActivityHelpCopyTokenAction: "复制 Token",
    webActivityHelpTitle: "网页同步使用说明",
    webActivityHelpDescription: "Patina Web Sync 会把当前活动网页同步到本机 Patina。",
    webActivityHelpSteps: [
      {
        title: "准备连接信息",
        description: "扩展需要使用本页的端口和 Token 连接本机 Patina。",
        details: [
          "复制端口和 Token，稍后粘贴到扩展设置中。",
        ],
      },
      {
        title: "安装浏览器扩展",
        description: "按浏览器系选择对应的 Patina Web Sync 扩展包。",
        details: [
          {
            text: "从下载页获取扩展包。",
            links: [
              {
                label: "打开下载页",
                href: "https://github.com/Ceceliaee/patina/releases/latest",
              },
            ],
          },
          {
            text: "Chromium 系：",
            children: [
              "下载 patina-chromium-extension-v...zip。",
              "解压后得到 patina-chromium-extension-v... 文件夹。",
              "在地址栏输入 chrome://extensions/ 或 edge://extensions/，开启「开发者模式」。",
              "点击「加载已解压的扩展程序」或「加载解压缩的扩展」。",
              "选择解压得到的 patina-chromium-extension-v... 文件夹（包含 manifest.json）。",
            ],
          },
          {
            text: "Firefox 系：",
            children: [
              "下载 patina-firefox-extension-v...xpi。",
              "在地址栏输入 about:addons，进入附加组件管理器。",
              "点击齿轮按钮，选择「从文件安装附加组件」。",
              "选择下载的 .xpi 文件，并在提示中点击「添加」。",
            ],
          },
        ],
      },
      {
        title: "配置扩展",
        description: "打开 Patina Web Sync 设置页，填入本页显示的连接信息。",
        details: [
          "打开浏览器工具栏里的「扩展程序」菜单。",
          "找到 Patina Web Sync 并打开它。",
          "在弹出的扩展窗口中点击「设置」。",
          "粘贴本页显示的端口和 Token。",
          "也可以从扩展管理页进入：找到 Patina Web Sync，点击「详情」/「详细信息」，再点击「扩展程序选项」。",
        ],
      },
      {
        title: "同步当前页",
        description: "打开常规网页后，扩展会同步当前活动页。",
        details: [
          "打开一个 http/https 网页。",
          "等待 Patina Web Sync 自动同步当前页。",
          "如需立即同步一次，可在扩展弹窗中点击「同步当前页」。",
        ],
      },
    ],
    webActivityHelpNote: "Patina Web Sync 启用并连接成功后：\n• 自动同步当前活动标签页的网站地址、标题和网站图标。\n• 不读取网页正文、表单内容、截图或剪贴板。\n• 不扫描或导入浏览器历史记录。\n• 无痕模式窗口不会写入网页记录。",
    remoteStatusBridgeTitle: "远程推送",
    remoteStatusBridgeEnabledHint: "向接收地址推送当前追踪状态。",
    remoteStatusBridgeUrlLabel: "接收地址",
    remoteStatusBridgeTokenLabel: "Token",
    remoteStatusBridgeMachineIdLabel: "本机标识",
    countValue: (count: number) => `${count} 个`,
    appearanceTitle: "外观",
    themeModeOptions: {
      light: "浅色",
      dark: "深色",
      system: "跟随系统",
    },
    themeLibraryOptions: {
      light: "浅色主题",
      dark: "深色主题",
    },
    themeModeLabel: "主题模式",
    themeModeHint: "浅色、深色，或跟随系统外观自动切换。",
    languageLabel: "语言",
    languageHint: "切换界面显示语言。",
    languageOptions: {
      zhCN: "中文",
      enUS: "English",
    },
    colorSchemeLabel: "配色方案",
    colorSchemeHint: "分别调整浅色和深色主题配色。",
    dynamicEffectsLabel: "灵动视效",
    dynamicEffectsHint: "控制导航、页面切换、弹窗和提示动效。",
    colorSchemeDialogFallbackTitle: "主题",
    colorSchemeDialogDescription: "选择后即时预览，确认后保存。",
    colorSchemeSaving: "保存中",
    dataSafetyTitle: "存储",
    backupRestoreTitle: "备份与恢复",
    backupRestoreHint: "备份本机数据快照；恢复时可选择覆盖或合并当前数据。",
    backupExportTitle: "备份",
    backupExportHint: "导出当前数据快照",
    backupExporting: "备份中...",
    backupExportAction: "备份",
    backupRestoreActionTitle: "恢复",
    backupRestoreActionHint: "从备份恢复数据",
    backupTargetTitle: "选择备份位置",
    backupTargetHint: "选择保存到本地文件，或上传到已绑定的 WebDAV。",
    backupTargetLocalTitle: "本地备份",
    backupTargetLocalHint: "保存为本机 zip 文件",
    backupTargetRemoteTitle: "WebDAV 备份",
    backupTargetRemoteHint: "上传到已绑定的 WebDAV",
    restoreSourceTitle: "选择恢复来源",
    restoreSourceHint: "选择本地备份文件，或从已绑定的 WebDAV 下载。",
    restoreSourceLocalTitle: "本地恢复",
    restoreSourceLocalHint: "选择本机 zip 文件",
    restoreSourceRemoteTitle: "WebDAV 恢复",
    restoreSourceRemoteHint: "从已绑定的 WebDAV 选择备份",
    remoteBackupTitle: "WebDAV 配置",
    remoteBackupHint: "绑定 WebDAV，用于远程备份。",
    webDavConfigure: "配置",
    webDavEdit: "编辑",
    webDavConfigTitle: "WebDAV 配置",
    webDavConfigDescription: "仅用于远程备份，不会作为云同步使用。",
    webDavServerUrl: "服务器地址",
    webDavUsername: "用户名",
    webDavPassword: "应用密码",
    webDavTestConnection: "测试连接",
    webDavTesting: "测试中...",
    webDavUploadBackup: "上传备份",
    webDavUploading: "上传中...",
    webDavRestoreBackup: "从远端恢复",
    webDavLoadingBackups: "加载中...",
    webDavRestoreSelected: "恢复",
    webDavDeleteTitle: "删除 WebDAV 配置",
    webDavDeleteDetail: "这只会删除本机保存的 WebDAV 配置和密码，不会删除远端备份文件。",
    webDavDeleteAction: "删除",
    webDavRemoteBackupsTitle: "远程备份",
    webDavRemoteBackupsDescription: "选择一份远端备份；下载后会先预览兼容性，再确认恢复。",
    webDavRemoteBackupsEmpty: "远端暂无可用备份。",
    restoreStrategyLabel: "恢复策略",
    restoreStrategyHint: "选择恢复时如何处理当前数据。",
    restoreStrategyOptions: {
      replace: "覆盖",
      merge: "兼容",
    },
    backupRestoring: "恢复中...",
    backupRestoreAction: "恢复",
    minuteValue: (minutes: number) => `${minutes} 分钟`,
    decreaseMinute: (label: string) => `${label}减少 1 分钟`,
    increaseMinute: (label: string) => `${label}增加 1 分钟`,
    storage: {
      storageDirectoryTitle: "本机目录",
      storageDirectoryBetaLabel: "Beta",
      storageDirectorySummary: "安装目录随应用安装位置确定；数据目录和缓存目录可单独调整。",
      storageSnapshotRefreshAction: "检查存储",
      storageSnapshotRefreshFailed: "无法检查存储目录。",
      changePathAction: "更改目录",
      restoreDefaultPathAction: "恢复默认目录",
      installDirectoryLabel: "安装目录",
      dataDirectoryLabel: "数据目录",
      webviewCacheDirectoryLabel: "缓存目录",
      openDirectoryAction: "打开目录",
      storageMigrationPendingTitle: "迁移将在下次启动前执行",
      storageMigrationPendingHint: (dataPath: string | null, cachePath: string | null) => [
        dataPath ? `数据目录迁移到：${dataPath}` : null,
        cachePath ? `缓存目录迁移到：${cachePath}` : null,
      ].filter(Boolean).join("\n"),
      storageMigrationCancelAction: "取消迁移",
      storageDataMigrationConfirmTitle: "更改数据目录",
      storageDataMigrationConfirmDetail: (currentDataRoot: string, targetDataRoot: string) => (
        `当前目录：${currentDataRoot}\n目标目录：${targetDataRoot}\n\nPatina 会在下次启动时迁移数据目录：\n- 本次运行中不会移动数据文件。\n- 下次启动时，Patina 会将当前数据复制到目标目录。\n- 迁移完成前，请不要删除或移动当前目录和目标目录。\n- 迁移成功后，默认目录只保留必要的锚点文件。`
      ),
      storageCacheMigrationConfirmTitle: "更改缓存目录",
      storageCacheMigrationConfirmDetail: (currentWebviewRoot: string, targetWebviewRoot: string) => (
        `当前缓存：${currentWebviewRoot}\n目标缓存：${targetWebviewRoot}\n\nPatina 会在下次启动时更改缓存目录：\n- 本次运行中不会更改缓存目录。\n- 下次启动时，Patina 会使用目标缓存目录。\n- 更改完成前，请不要删除或移动目标目录。\n- 更改成功后，默认目录只保留必要的锚点文件。`
      ),
      storageMigrationConfirmAction: "确认更改",
      storageRestoreDefaultDataConfirmDetail: (currentDataRoot: string, defaultDataRoot: string) => (
        `当前数据：${currentDataRoot}\n默认数据：${defaultDataRoot}\n\nPatina 会在下次启动时迁移数据目录：\n- 本次运行中不会移动数据文件。\n- 下次启动时，Patina 会将当前数据复制到默认目录。\n- 迁移完成前，请不要删除或移动当前目录和默认目录。\n- 迁移成功后，自定义目录会被删除，清理其中的数据文件。`
      ),
      storageRestoreDefaultCacheConfirmDetail: (currentWebviewRoot: string, defaultWebviewRoot: string) => (
        `当前缓存：${currentWebviewRoot}\n默认缓存：${defaultWebviewRoot}\n\nPatina 会在下次启动时更改缓存目录：\n- 本次运行中不会更改缓存目录。\n- 下次启动时，Patina 会使用默认缓存目录。\n- 更改完成前，请不要删除或移动默认目录。\n- 更改成功后，自定义目录会被删除，清理其中的缓存文件。`
      ),
      webviewCacheClearTitle: "清理缓存",
      webviewCacheClearPending: "已安排在下次启动前清理。",
      webviewCacheClearAction: "下次启动清理",
      webviewCacheClearConfirmTitle: "清理缓存",
      webviewCacheClearConfirmDetail: "下次启动创建窗口前，清理可重新生成的缓存。",
      webviewCacheClearScheduled: "已安排下次启动前清理缓存。",
      webviewCacheClearFailed: "无法安排缓存清理。",
      storageMigrationScheduled: "迁移已安排，下次启动前执行。",
      storageMigrationFailed: "无法安排迁移，请检查目标目录。",
      storageMigrationCancelled: "已取消待执行迁移。",
      storageMigrationCancelFailed: "无法取消迁移。",
      storageOpenDirectoryFailed: "无法打开该目录。",
    },
  },
};

const EN_US_SETTINGS_COPY = {
  settings: {
    ...ZH_CN_SETTINGS_COPY.settings,
    loading: "Loading settings...",
    title: "Settings",
    subtitle: "Adjust global runtime preferences",
    saving: "Saving...",
    saved: "Settings updated",
    saveFailed: "Could not save settings. Try again later.",
    unsaved: "Unsaved changes",
    idle: "Saved",
    save: "Save",
    cancel: "Cancel",
    cancelled: "Edits discarded",
    tracking: "Tracking",
    idleTimeoutLabel: "Continue counting",
    idleTimeoutHint: "When the current app has audio or similar signals, keep counting that time.",
    timelineMergeGapLabel: "Activity hold time",
    timelineMergeGapHint: "Stop counting after idle time; briefly switching away and back keeps the timeline continuous.",
    performance: "Performance",
    refreshLabel: "Refresh interval",
    refreshHint: "How often the interface pulls fresh data from the backend.",
    refreshWarning: "Shorter refresh intervals can increase CPU usage. Use 5s or above if the UI feels slow.",
    cleanup: "Data management",
    cleanupTitle: "Clear history records",
    cleanupHint: "Delete activity records from the selected time and earlier. This cannot be undone.",
    cleanupRangeLabel: "Clear time",
    decreaseCleanupRange: "Shorten clear range",
    increaseCleanupRange: "Extend clear range",
    cleanupRunning: "Clearing...",
    cleanupNow: "Clear",
    cleanupConfirmTitle: "Confirm history cleanup",
    cleanupConfirmDetail: (label: string) => `Activity records from ${label} and earlier will be deleted.`,
    restoreConfirmTitle: "Restore backup",
    restoreConfirmDetail: (path: string, summary: string, strategy: string) => `Restore strategy: ${strategy}\nTarget file: ${path}\n\n${summary}`,
    confirmRangeFallback: "selected range",
    cleanupRangeLabels: {
      180: "180 days ago",
      90: "90 days ago",
      60: "60 days ago",
      30: "30 days ago",
      15: "15 days ago",
      7: "7 days ago",
    } as Record<number, string>,
    refreshPresets: {
      1: "Realtime (1s)",
      3: "Balanced (3s)",
      5: "Battery saver (5s)",
      10: "Low frequency (10s)",
    } as Record<number, string>,
    minutePresets: {
      60: "1 minute",
      180: "3 minutes",
      300: "5 minutes",
      600: "10 minutes",
    } as Record<number, string>,
    trackingPanelTitle: "Tracking",
    trackingPausedLabel: "Pause tracking",
    trackingPausedHint: "Paused tracking will stop writing new records. Resume to continue tracking.",
    residentTitle: "Resident",
    minimizeToWidgetLabel: "Minimize to widget",
    minimizeToWidgetHint: "Hide the main window and show the side widget when minimized.",
    closeToTrayLabel: "Close to tray",
    closeToTrayHint: "Hide the main window and keep running in the background when closed.",
    backgroundOptimizationLabel: "Low-footprint background",
    backgroundOptimizationHint: "Release main UI memory while idle in the background. Reopening may feel slightly slower.",
    launchAtLoginLabel: "Launch at login",
    launchAtLoginHint: "Start the app automatically after Windows sign-in.",
    startMinimizedLabel: "Start minimized",
    startMinimizedHint: "Only applies to launch at login. Hide the main window after startup.",
    servicesTitle: "Services",
    webActivityTitle: "Web sync",
    webActivityEnabledLabel: "Web sync",
    webActivityEnabledHint: "Receives active web pages from the browser extension.",
    webActivityAddressLabel: "Port",
    webActivityTokenLabel: "Token",
    webActivityHelpAction: "Guide",
    webActivityHelpCopiedAction: "Copied",
    webActivityHelpCopyPortAction: "Copy port",
    webActivityHelpCopyTokenAction: "Copy Token",
    webActivityHelpTitle: "Web Sync Guide",
    webActivityHelpDescription: "Patina Web Sync sends the active webpage to the local Patina desktop app.",
    webActivityHelpSteps: [
      {
        title: "Prepare connection details",
        description: "The extension uses this page's port and Token to connect to the local Patina app.",
        details: [
          "Copy the port and Token, then paste them into the extension settings later.",
        ],
      },
      {
        title: "Install the browser extension",
        description: "Choose the Patina Web Sync extension package for your browser family.",
        details: [
          {
            text: "Download the extension packages from the releases page.",
            links: [
              {
                label: "Open downloads",
                href: "https://github.com/Ceceliaee/patina/releases/latest",
              },
            ],
          },
          {
            text: "Chromium-based browsers:",
            children: [
              "Download patina-chromium-extension-v...zip.",
              "Extract it to get the patina-chromium-extension-v... folder.",
              "Enter chrome://extensions/ or edge://extensions/, then enable Developer mode.",
              "Click Load unpacked or Load extracted extension.",
              "Select the extracted patina-chromium-extension-v... folder that contains manifest.json.",
            ],
          },
          {
            text: "Firefox-based browsers:",
            children: [
              "Download patina-firefox-extension-v...xpi.",
              "Enter about:addons in the address bar to open the add-ons manager.",
              "Click the cog button, then choose Install Add-on From File.",
              "Select the downloaded .xpi file, then click Add when prompted.",
            ],
          },
        ],
      },
      {
        title: "Configure the extension",
        description: "Open the Patina Web Sync settings page and enter the connection details shown here.",
        details: [
          "Open the Extensions menu in the browser toolbar.",
          "Find Patina Web Sync and open it.",
          "Click Settings in the extension popup.",
          "Paste the port and Token shown on this page.",
          "You can also enter from the extensions management page: find Patina Web Sync, click Details, then click Extension options.",
        ],
      },
      {
        title: "Sync the current page",
        description: "After you open a regular webpage, the extension syncs the active page.",
        details: [
          "Open an http/https webpage.",
          "Wait for Patina Web Sync to automatically sync the current page.",
          "To sync once immediately, click Sync current page in the extension popup.",
        ],
      },
    ],
    webActivityHelpNote: "After Patina Web Sync is enabled and connected:\n• Automatically syncs the active tab's website address, title, and website icon.\n• Does not read page body content, form values, screenshots, or clipboard contents.\n• Does not scan or import browser history.\n• Incognito windows are not written to web records.",
    remoteStatusBridgeTitle: "Remote push",
    remoteStatusBridgeEnabledHint: "Push the current tracking status to the endpoint.",
    remoteStatusBridgeUrlLabel: "Endpoint URL",
    remoteStatusBridgeTokenLabel: "Token",
    remoteStatusBridgeMachineIdLabel: "Device ID",
    countValue: (count: number) => `${count}`,
    appearanceTitle: "Appearance",
    themeModeOptions: {
      light: "Light",
      dark: "Dark",
      system: "System",
    },
    themeLibraryOptions: {
      light: "Light theme",
      dark: "Dark theme",
    },
    themeModeLabel: "Theme mode",
    themeModeHint: "Light, dark, or follow the system appearance.",
    languageLabel: "Language",
    languageHint: "Change the interface language.",
    languageOptions: {
      zhCN: "中文",
      enUS: "English",
    },
    colorSchemeLabel: "Color scheme",
    colorSchemeHint: "Adjust light and dark theme colors separately.",
    dynamicEffectsLabel: "Dynamic effects",
    dynamicEffectsHint: "Controls navigation, view switching, dialog, and toast motion.",
    colorSchemeDialogFallbackTitle: "Theme",
    colorSchemeDialogDescription: "Preview immediately. Confirm to save.",
    colorSchemeSaving: "Saving",
    dataSafetyTitle: "Storage",
    backupRestoreTitle: "Backup and restore",
    backupRestoreHint: "Back up a local data snapshot. Restore can replace or merge with current data.",
    backupExportTitle: "Back up",
    backupExportHint: "Export a snapshot of current data",
    backupExporting: "Backing up...",
    backupExportAction: "Back up",
    backupRestoreActionTitle: "Restore",
    backupRestoreActionHint: "Restore data from a backup",
    backupTargetTitle: "Choose backup location",
    backupTargetHint: "Save a local file or upload to the linked WebDAV target.",
    backupTargetLocalTitle: "Local backup",
    backupTargetLocalHint: "Save as a local zip file",
    backupTargetRemoteTitle: "WebDAV backup",
    backupTargetRemoteHint: "Upload to the linked WebDAV target",
    restoreSourceTitle: "Choose restore source",
    restoreSourceHint: "Choose a local backup file or download from the linked WebDAV target.",
    restoreSourceLocalTitle: "Local restore",
    restoreSourceLocalHint: "Choose a local zip file",
    restoreSourceRemoteTitle: "WebDAV restore",
    restoreSourceRemoteHint: "Choose a backup from the linked WebDAV target",
    remoteBackupTitle: "WebDAV configuration",
    remoteBackupHint: "Link WebDAV for remote backups.",
    webDavConfigure: "Configure",
    webDavEdit: "Edit",
    webDavConfigTitle: "WebDAV configuration",
    webDavConfigDescription: "Used only for remote backup, not cloud sync.",
    webDavServerUrl: "Server address",
    webDavUsername: "Username",
    webDavPassword: "App password",
    webDavTestConnection: "Test connection",
    webDavTesting: "Testing...",
    webDavUploadBackup: "Upload backup",
    webDavUploading: "Uploading...",
    webDavRestoreBackup: "Restore from remote",
    webDavLoadingBackups: "Loading...",
    webDavRestoreSelected: "Restore",
    webDavDeleteTitle: "Delete WebDAV configuration",
    webDavDeleteDetail: "This only removes the local WebDAV settings and password. Remote backup files are not deleted.",
    webDavDeleteAction: "Delete",
    webDavRemoteBackupsTitle: "Remote backups",
    webDavRemoteBackupsDescription: "Choose a remote backup. It will be downloaded, previewed for compatibility, then confirmed for restore.",
    webDavRemoteBackupsEmpty: "No remote backups available.",
    restoreStrategyLabel: "Restore strategy",
    restoreStrategyHint: "Choose how restore handles current data.",
    restoreStrategyOptions: {
      replace: "Replace",
      merge: "Merge",
    },
    backupRestoring: "Restoring...",
    backupRestoreAction: "Restore",
    minuteValue: (minutes: number) => `${minutes} min`,
    decreaseMinute: (label: string) => `Decrease ${label} by 1 minute`,
    increaseMinute: (label: string) => `Increase ${label} by 1 minute`,
    storage: {
      storageDirectoryTitle: "Local paths",
      storageDirectoryBetaLabel: "Beta",
      storageDirectorySummary: "Install folder follows the app install location; data and cache folders can be adjusted separately.",
      storageSnapshotRefreshAction: "Check storage",
      storageSnapshotRefreshFailed: "Could not check storage folders.",
      changePathAction: "Change location",
      restoreDefaultPathAction: "Restore default location",
      installDirectoryLabel: "Install folder",
      dataDirectoryLabel: "Data folder",
      webviewCacheDirectoryLabel: "Cache folder",
      openDirectoryAction: "Open folder",
      storageMigrationPendingTitle: "Migration runs before next launch",
      storageMigrationPendingHint: (dataPath: string | null, cachePath: string | null) => [
        dataPath ? `Data folder moves to: ${dataPath}` : null,
        cachePath ? `Cache folder moves to: ${cachePath}` : null,
      ].filter(Boolean).join("\n"),
      storageMigrationCancelAction: "Cancel migration",
      storageDataMigrationConfirmTitle: "Change data folder",
      storageDataMigrationConfirmDetail: (currentDataRoot: string, targetDataRoot: string) => (
        `Current folder: ${currentDataRoot}\nTarget folder: ${targetDataRoot}\n\nPatina will migrate the data folder before the next launch:\n- No data files move during this run.\n- On the next launch, Patina copies the current data to the target folder.\n- Until migration finishes, do not delete or move the current or target folder.\n- After migration succeeds, the default folder only keeps the required anchor files.`
      ),
      storageCacheMigrationConfirmTitle: "Change cache folder",
      storageCacheMigrationConfirmDetail: (currentWebviewRoot: string, targetWebviewRoot: string) => (
        `Current cache: ${currentWebviewRoot}\nTarget cache: ${targetWebviewRoot}\n\nPatina will change the cache folder before the next launch:\n- The cache folder will not change during this run.\n- On the next launch, Patina uses the target cache folder.\n- Until the change finishes, do not delete or move the target folder.\n- After the change succeeds, the default folder only keeps the required anchor files.`
      ),
      storageMigrationConfirmAction: "Confirm change",
      storageRestoreDefaultDataConfirmDetail: (currentDataRoot: string, defaultDataRoot: string) => (
        `Current data: ${currentDataRoot}\nDefault data: ${defaultDataRoot}\n\nPatina will migrate the data folder before the next launch:\n- No data files move during this run.\n- On the next launch, Patina copies the current data to the default folder.\n- Until migration finishes, do not delete or move the current or default folder.\n- After migration succeeds, the custom folder is removed and its data files are cleaned.`
      ),
      storageRestoreDefaultCacheConfirmDetail: (currentWebviewRoot: string, defaultWebviewRoot: string) => (
        `Current cache: ${currentWebviewRoot}\nDefault cache: ${defaultWebviewRoot}\n\nPatina will change the cache folder before the next launch:\n- The cache folder will not change during this run.\n- On the next launch, Patina uses the default cache folder.\n- Until the change finishes, do not delete or move the default folder.\n- After the change succeeds, the custom folder is removed and its cache files are cleaned.`
      ),
      webviewCacheClearTitle: "Clear cache",
      webviewCacheClearPending: "Scheduled to clear before the next launch.",
      webviewCacheClearAction: "Clear next launch",
      webviewCacheClearConfirmTitle: "Clear cache",
      webviewCacheClearConfirmDetail: "Before the next window starts, Patina clears regenerable cache.",
      webviewCacheClearScheduled: "Cache cleanup scheduled for next launch.",
      webviewCacheClearFailed: "Could not schedule cache cleanup.",
      storageMigrationScheduled: "Migration scheduled for next launch.",
      storageMigrationFailed: "Could not schedule migration. Check the target.",
      storageMigrationCancelled: "Pending migration cancelled.",
      storageMigrationCancelFailed: "Could not cancel migration.",
      storageOpenDirectoryFailed: "Could not open that folder.",
    },
  },
};

export const settingsCopy = {
  "zh-CN": ZH_CN_SETTINGS_COPY,
  "en-US": EN_US_SETTINGS_COPY,
} as const;
