const ZH_CN_TOOLS_COPY = {
  tools: {
    title: "工具",
    beta: "Beta",
    subtitle: "启动本地桌面工具",
    remindersTitle: "提醒器",
    reminderModeEvent: "事件",
    reminderModeSoftware: "应用",
    softwareReminderEmpty: "暂无应用规则",
    softwareReminderAppLabel: "应用",
    softwareReminderAppPlaceholder: "输入或选择应用",
    softwareReminderDurationLabel: "每日上限（分钟）",
    softwareReminderMessageLabel: "提醒内容",
    softwareReminderMessagePlaceholder: "例如：休息一下",
    softwareReminderRulesTitle: "应用规则",
    softwareReminderActive: "启用",
    softwareReminderDisable: "停用",
    softwareReminderDailyLimit: (minutes: number) => `每日 ${minutes} 分钟`,
    softwareReminderAppRequired: "请选择已记录的应用。",
    softwareReminderDurationInvalid: "每日上限至少为 1 分钟。",
    newReminder: "新建提醒",
    notificationStatus: "到期通知",
    reminderLabel: "提醒内容",
    reminderLabelPlaceholder: "例如：休息一下",
    defaultReminderLabel: "时间到了",
    reminderModeRelative: "相对时间",
    reminderModeAbsolute: "绝对时间",
    relativeMinutesLabel: "分钟后",
    absoluteDateLabel: "日期",
    absoluteTimeLabel: "时间",
    createReminder: "创建",
    pendingReminders: "提醒列表",
    reminderStatus: {
      scheduled: "待提醒",
      fired: "已触发",
      cancelled: "已取消",
    },
    reminderEmpty: "暂无待提醒",
    reminderTimeInvalid: "提醒时间需要晚于当前时间。",
    timerTitle: "计时器",
    timerHint: "计时结果不会写入活动记录。",
    timerModeStopwatch: "正计时",
    timerModeCountdown: "倒计时",
    timerLabel: "名称",
    timerLabelPlaceholder: "可选",
    countdownDuration: "倒计时时长",
    durationPresets: {
      5: "5 分钟",
      10: "10 分钟",
      25: "25 分钟",
      30: "30 分钟",
      60: "60 分钟",
    } as Record<number, string>,
    minuteValue: (minutes: number) => `${minutes} 分钟`,
    timerStatus: {
      idle: "未开始",
      running: "运行中",
      paused: "已暂停",
      completed: "已完成",
    },
    start: "开始",
    pause: "暂停",
    resume: "继续",
    reset: "重置",
    lap: "分段",
    lapsTitle: "分段",
    lapsEmpty: "暂无分段",
    lapIndex: (index: number) => `第 ${index} 段`,
    pomodoroTitle: "番茄钟",
    pomodoroPhase: {
      focus: "专注",
      shortBreak: "短休息",
      longBreak: "长休息",
    },
    pomodoroStatus: {
      idle: "未开始",
      running: "运行中",
      paused: "已暂停",
      completed: "已完成",
    },
    pomodoroCycle: (index: number, every: number) => `第 ${index} / ${every} 个番茄`,
    completedToday: (count: number) => `今日完成 ${count} 个`,
    pomodoroSettings: "默认时长",
    focusDuration: "专注时长",
    shortBreakDuration: "短休息时长",
    longBreakDuration: "长休息时长",
    longBreakEvery: "长休息间隔",
    longBreakEveryValue: (count: number) => `每 ${count} 个番茄`,
    skipPhase: "跳过",
    dueNow: "现在",
    alertOccurredAt: (value: string) => `到点时间：${value}`,
    alertSnooze: "稍后提醒",
    alertSnoozeMinutes: (minutes: number) => `${minutes} 分钟后提醒`,
    alertSnoozing: "稍后提醒中...",
    alertPausePomodoro: "暂停",
    alertPausingPomodoro: "暂停中...",
    alertDismiss: "知道了",
    loadFailed: "工具状态加载失败。",
    actionFailed: "操作失败，可稍后重试。",
    statusChip: {
      focus: "专注",
      break: "休息",
      countdown: "倒计时",
      stopwatch: "计时",
      reminder: "提醒",
    },
  },
};

const EN_US_TOOLS_COPY = {
  tools: {
    title: "Tools",
    beta: "Beta",
    subtitle: "Start local desktop tools",
    remindersTitle: "Reminder",
    reminderModeEvent: "Event",
    reminderModeSoftware: "App",
    softwareReminderEmpty: "No app rules",
    softwareReminderAppLabel: "App",
    softwareReminderAppPlaceholder: "Type or select app",
    softwareReminderDurationLabel: "Daily limit (min)",
    softwareReminderMessageLabel: "Message",
    softwareReminderMessagePlaceholder: "Example: take a break",
    softwareReminderRulesTitle: "App rules",
    softwareReminderActive: "Active",
    softwareReminderDisable: "Disable",
    softwareReminderDailyLimit: (minutes: number) => `${minutes} min daily`,
    softwareReminderAppRequired: "Select a recorded app.",
    softwareReminderDurationInvalid: "Daily limit must be at least 1 minute.",
    newReminder: "New reminder",
    notificationStatus: "Due notifications",
    reminderLabel: "Reminder",
    reminderLabelPlaceholder: "Example: take a break",
    defaultReminderLabel: "Time is up",
    reminderModeRelative: "Relative time",
    reminderModeAbsolute: "Exact time",
    relativeMinutesLabel: "Minutes from now",
    absoluteDateLabel: "Date",
    absoluteTimeLabel: "Time",
    createReminder: "Create",
    pendingReminders: "Reminder list",
    reminderStatus: {
      scheduled: "Scheduled",
      fired: "Fired",
      cancelled: "Cancelled",
    },
    reminderEmpty: "No pending reminders",
    reminderTimeInvalid: "Reminder time needs to be in the future.",
    timerTitle: "Timer",
    timerHint: "Timer results are not written to activity records.",
    timerModeStopwatch: "Count up",
    timerModeCountdown: "Countdown",
    timerLabel: "Name",
    timerLabelPlaceholder: "Optional",
    countdownDuration: "Countdown duration",
    durationPresets: {
      5: "5 min",
      10: "10 min",
      25: "25 min",
      30: "30 min",
      60: "60 min",
    } as Record<number, string>,
    minuteValue: (minutes: number) => `${minutes} min`,
    timerStatus: {
      idle: "Not started",
      running: "Running",
      paused: "Paused",
      completed: "Completed",
    },
    start: "Start",
    pause: "Pause",
    resume: "Resume",
    reset: "Reset",
    lap: "Lap",
    lapsTitle: "Laps",
    lapsEmpty: "No laps",
    lapIndex: (index: number) => `Lap ${index}`,
    pomodoroTitle: "Pomodoro",
    pomodoroPhase: {
      focus: "Focus",
      shortBreak: "Short break",
      longBreak: "Long break",
    },
    pomodoroStatus: {
      idle: "Not started",
      running: "Running",
      paused: "Paused",
      completed: "Completed",
    },
    pomodoroCycle: (index: number, every: number) => `${index} / ${every} pomodoro`,
    completedToday: (count: number) => `${count} completed today`,
    pomodoroSettings: "Default durations",
    focusDuration: "Focus duration",
    shortBreakDuration: "Short break",
    longBreakDuration: "Long break",
    longBreakEvery: "Long break interval",
    longBreakEveryValue: (count: number) => `Every ${count} pomodoros`,
    skipPhase: "Skip",
    dueNow: "Now",
    alertOccurredAt: (value: string) => `Due at ${value}`,
    alertSnooze: "Snooze",
    alertSnoozeMinutes: (minutes: number) => `Snooze ${minutes} min`,
    alertSnoozing: "Snoozing...",
    alertPausePomodoro: "Pause",
    alertPausingPomodoro: "Pausing...",
    alertDismiss: "Got it",
    loadFailed: "Could not load tools status.",
    actionFailed: "Action failed. Try again later.",
    statusChip: {
      focus: "Focus",
      break: "Break",
      countdown: "Countdown",
      stopwatch: "Timer",
      reminder: "Reminder",
    },
  },
};

export const toolsCopy = {
  "zh-CN": ZH_CN_TOOLS_COPY,
  "en-US": EN_US_TOOLS_COPY,
} as const;
