import { readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";

const SCAN_ROOTS = [
  "src-tauri/src/commands",
  "src-tauri/src/app",
  "src-tauri/src/platform",
  "src-tauri/src/domain",
  "src-tauri/src/engine",
] as const;

const EXTRA_FILES = ["src-tauri/src/lib.rs"] as const;

type RustBoundaryRule =
  | "entry-layer-no-direct-sql-query"
  | "commands-no-sqlite-pool-type"
  | "app-no-data-repository-import"
  | "app-no-sqlite-pool-access"
  | "app-no-sqlite-pool-type"
  | "platform-no-data-import"
  | "platform-no-app-import"
  | "domain-no-data-import"
  | "domain-no-platform-import"
  | "engine-no-data-import"
  | "engine-no-app-import"
  | "engine-no-data-repository-import"
  | "engine-no-sqlite-pool-type"
  | "engine-no-direct-sql-query"
  | "engine-no-raw-windows-api"
  | "engine-no-wait-for-sqlite-pool";

interface SourceFile {
  path: string;
  content: string;
}

interface BoundaryViolation {
  path: string;
  line: number;
  rule: RustBoundaryRule;
  text: string;
}

interface BoundaryDebtBaseline {
  path: string;
  rule: RustBoundaryRule;
  maxOccurrences: number;
  owner: string;
  exitPhase: string;
}

function engineDebt(
  path: string,
  rule: RustBoundaryRule,
  maxOccurrences: number,
): BoundaryDebtBaseline {
  return {
    path,
    rule,
    maxOccurrences,
    owner: "app composition + engine port + data adapter",
    exitPhase: "D",
  };
}

// Generated by --report-engine-debt. Every entry is exact and must shrink with its owner slice.
const ENGINE_DEBT_BASELINE: BoundaryDebtBaseline[] = [
];

function normalizePath(path: string) {
  return path.split(sep).join("/");
}

function collectRustFiles(root: string): SourceFile[] {
  const files: SourceFile[] = [];

  function walk(path: string) {
    const stats = statSync(path);
    if (stats.isDirectory()) {
      for (const entry of readdirSync(path)) {
        walk(join(path, entry));
      }
      return;
    }

    if (path.endsWith(".rs")) {
      files.push({
        path: normalizePath(relative(process.cwd(), path)),
        content: readFileSync(path, "utf8"),
      });
    }
  }

  walk(root);
  return files;
}

function isCommandsSource(path: string) {
  return /^src-tauri\/src\/commands\//.test(path);
}

function isAppSource(path: string) {
  return /^src-tauri\/src\/app\//.test(path);
}

function isPlatformSource(path: string) {
  return /^src-tauri\/src\/platform\//.test(path);
}

function isDomainSource(path: string) {
  return /^src-tauri\/src\/domain\//.test(path);
}

function isEngineSource(path: string) {
  return /^src-tauri\/src\/engine\//.test(path);
}

function isLibSource(path: string) {
  return path === "src-tauri/src/lib.rs";
}

function braceDelta(line: string) {
  let delta = 0;
  let quote: '"' | "'" | null = null;
  let escaped = false;

  for (let index = 0; index < line.length; index += 1) {
    const char = line[index];
    const next = line[index + 1];
    if (quote) {
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === quote) {
        quote = null;
      }
      continue;
    }
    if (char === "/" && next === "/") {
      break;
    }
    if (char === '"' || char === "'") {
      quote = char;
    } else if (char === "{") {
      delta += 1;
    } else if (char === "}") {
      delta -= 1;
    }
  }

  return delta;
}

function productionOnlyContent(content: string) {
  const lines = content.split(/\r?\n/);
  const productionLines = [...lines];
  let pendingTestAttribute = false;
  let pendingTestItemStarted = false;
  let testDepth: number | null = null;

  lines.forEach((line, index) => {
    const trimmed = line.trim();
    if (testDepth !== null) {
      productionLines[index] = "";
      testDepth += braceDelta(line);
      if (testDepth <= 0) {
        testDepth = null;
      }
      return;
    }

    if (/^#\s*\[\s*cfg\s*\(\s*test\s*\)\s*\]/.test(trimmed)) {
      pendingTestAttribute = true;
      productionLines[index] = "";
      if (/\bmod\s+\w+\s*\{/.test(trimmed)) {
        testDepth = braceDelta(line);
        pendingTestAttribute = false;
      }
      return;
    }

    if (pendingTestAttribute) {
      productionLines[index] = "";
      if (!trimmed || (!pendingTestItemStarted && trimmed.startsWith("#"))) {
        return;
      }

      pendingTestItemStarted = true;
      const delta = braceDelta(line);
      if (delta > 0) {
        testDepth = delta;
        pendingTestAttribute = false;
        pendingTestItemStarted = false;
      } else if (trimmed.endsWith(";") || (trimmed.includes("{") && delta === 0)) {
        pendingTestAttribute = false;
        pendingTestItemStarted = false;
      }
    }
  });

  return productionLines.join("\n");
}

function lineForOffset(content: string, offset: number) {
  return content.slice(0, offset).split("\n").length;
}

function lineTextAt(content: string, line: number) {
  return content.split(/\r?\n/)[line - 1]?.trim() ?? "";
}

function addRegexViolations(
  violations: BoundaryViolation[],
  file: SourceFile,
  productionContent: string,
  rule: RustBoundaryRule,
  pattern: RegExp,
) {
  for (const match of productionContent.matchAll(pattern)) {
    const line = lineForOffset(productionContent, match.index ?? 0);
    violations.push({
      path: file.path,
      line,
      rule,
      text: lineTextAt(file.content, line),
    });
  }
}

function findRustBoundaryViolations(files: SourceFile[]): BoundaryViolation[] {
  const violations: BoundaryViolation[] = [];

  for (const file of files) {
    const productionContent = productionOnlyContent(file.content);
    const directSqlPattern = /\bsqlx\s*::\s*query(?:_scalar|_as)?(?:\s*::\s*<[^>]+>)?\s*\(/g;
    const sqlitePoolPattern = /\b(?:SqlitePool|Pool\s*<\s*(?:sqlx\s*::\s*)?Sqlite\s*>)/g;

    if (isCommandsSource(file.path) || isAppSource(file.path) || isLibSource(file.path)) {
      addRegexViolations(
        violations,
        file,
        productionContent,
        "entry-layer-no-direct-sql-query",
        directSqlPattern,
      );
    }

    if (isCommandsSource(file.path)) {
      addRegexViolations(
        violations,
        file,
        productionContent,
        "commands-no-sqlite-pool-type",
        sqlitePoolPattern,
      );
    }

    if (isAppSource(file.path)) {
      addRegexViolations(
        violations,
        file,
        productionContent,
        "app-no-data-repository-import",
        /crate\s*::\s*data\s*::\s*(?:repositories\b|\{[^}]*\brepositories\b)/g,
      );
      addRegexViolations(
        violations,
        file,
        productionContent,
        "app-no-sqlite-pool-access",
        /\bwait_for_sqlite_pool\b/g,
      );
      addRegexViolations(
        violations,
        file,
        productionContent,
        "app-no-sqlite-pool-type",
        sqlitePoolPattern,
      );
    }

    if (isPlatformSource(file.path)) {
      addRegexViolations(
        violations,
        file,
        productionContent,
        "platform-no-app-import",
        /crate\s*::\s*app\s*::/g,
      );
      addRegexViolations(
        violations,
        file,
        productionContent,
        "platform-no-data-import",
        /crate\s*::\s*data\s*::/g,
      );
    }

    if (isDomainSource(file.path)) {
      addRegexViolations(
        violations,
        file,
        productionContent,
        "domain-no-data-import",
        /crate\s*::\s*data\s*::/g,
      );
      addRegexViolations(
        violations,
        file,
        productionContent,
        "domain-no-platform-import",
        /crate\s*::\s*platform\s*::/g,
      );
    }

    if (isEngineSource(file.path)) {
      addRegexViolations(
        violations,
        file,
        productionContent,
        "engine-no-app-import",
        /crate\s*::\s*app\s*::/g,
      );
      addRegexViolations(
        violations,
        file,
        productionContent,
        "engine-no-data-import",
        /crate\s*::\s*data\s*::/g,
      );
      addRegexViolations(
        violations,
        file,
        productionContent,
        "engine-no-data-repository-import",
        /crate\s*::\s*data\s*::\s*(?:repositories\b|\{[^}]*\brepositories\b)/g,
      );
      addRegexViolations(
        violations,
        file,
        productionContent,
        "engine-no-sqlite-pool-type",
        sqlitePoolPattern,
      );
      addRegexViolations(
        violations,
        file,
        productionContent,
        "engine-no-direct-sql-query",
        directSqlPattern,
      );
      addRegexViolations(
        violations,
        file,
        productionContent,
        "engine-no-raw-windows-api",
        /(?:\bwindows\s*::\s*(?:core|Win32)\b|\bstd\s*::\s*os\s*::\s*windows\b)/g,
      );
      addRegexViolations(
        violations,
        file,
        productionContent,
        "engine-no-wait-for-sqlite-pool",
        /\bwait_for_sqlite_pool\b/g,
      );
    }
  }

  return violations;
}

function baselineKey(path: string, rule: RustBoundaryRule) {
  return `${path}\0${rule}`;
}

function applyEngineDebtBaseline(violations: BoundaryViolation[]) {
  const productionViolations = violations.filter((violation) => !isEngineSource(violation.path));
  const engineViolations = violations.filter((violation) => isEngineSource(violation.path));
  const counts = new Map<string, number>();
  for (const violation of engineViolations) {
    const key = baselineKey(violation.path, violation.rule);
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }

  const baselineByKey = new Map(
    ENGINE_DEBT_BASELINE.map((entry) => [baselineKey(entry.path, entry.rule), entry]),
  );
  for (const violation of engineViolations) {
    const entry = baselineByKey.get(baselineKey(violation.path, violation.rule));
    if (!entry || (counts.get(baselineKey(violation.path, violation.rule)) ?? 0) > entry.maxOccurrences) {
      productionViolations.push(violation);
    }
  }

  for (const entry of ENGINE_DEBT_BASELINE) {
    const actual = counts.get(baselineKey(entry.path, entry.rule)) ?? 0;
    if (actual < entry.maxOccurrences) {
      productionViolations.push({
        path: entry.path,
        line: 1,
        rule: entry.rule,
        text: `stale baseline: ${actual} remaining, budget is ${entry.maxOccurrences}; tighten it`,
      });
    }
  }

  return productionViolations;
}

function reportEngineDebt(violations: BoundaryViolation[]) {
  const grouped = new Map<string, { path: string; rule: RustBoundaryRule; count: number }>();
  for (const violation of violations.filter((item) => isEngineSource(item.path))) {
    const key = baselineKey(violation.path, violation.rule);
    const current = grouped.get(key) ?? { path: violation.path, rule: violation.rule, count: 0 };
    current.count += 1;
    grouped.set(key, current);
  }

  const report = [...grouped.values()]
    .sort((left, right) => left.path.localeCompare(right.path) || left.rule.localeCompare(right.rule))
    .map((item) => ({
      path: item.path,
      rule: item.rule,
      maxOccurrences: item.count,
      owner: "app composition + engine port + data adapter",
      exitPhase: "D",
    }));
  console.log(JSON.stringify(report, null, 2));
}

function assertRules(actual: BoundaryViolation[], expected: RustBoundaryRule[]) {
  const actualRules = actual.map((violation) => violation.rule).sort();
  const expectedRules = [...expected].sort();
  if (JSON.stringify(actualRules) !== JSON.stringify(expectedRules)) {
    throw new Error(
      `Rust boundary self-test failed\nexpected ${JSON.stringify(expectedRules)}\nactual ${JSON.stringify(actualRules)}`,
    );
  }
}

function runSelfTest() {
  const violations = findRustBoundaryViolations([
    {
      path: "src-tauri/src/commands/tracking.rs",
      content: "let row = sqlx::query(\"SELECT 1\");\nfn takes_pool(pool: Pool<Sqlite>) {}",
    },
    {
      path: "src-tauri/src/app/tray.rs",
      content: [
        "use crate::data::{",
        "  repositories::tracker_settings,",
        "  sqlite_pool::wait_for_sqlite_pool,",
        "};",
        "fn takes_pool(pool: Pool<Sqlite>) {}",
      ].join("\n"),
    },
    {
      path: "src-tauri/src/app/tray.rs",
      content: [
        "#[cfg(test)]",
        "mod tests {",
        "  use crate::data::repositories::tracker_settings;",
        "  use sqlx::SqlitePool;",
        "}",
        "#[cfg(test)]",
        "fn test_only_pool(",
        "  pool: sqlx::SqlitePool,",
        ") { crate::data::repositories::sessions::load(); }",
        "fn production_after_tests() { crate::data::repositories::sessions::load(); }",
      ].join("\n"),
    },
    {
      path: "src-tauri/src/lib.rs",
      content: "let row = sqlx::query_as::<_, Row>(\"SELECT 1\");",
    },
    {
      path: "src-tauri/src/platform/windows/foo.rs",
      content: "use crate::data::sqlite_pool::wait_for_sqlite_pool;\nuse crate::app::runtime;",
    },
    {
      path: "src-tauri/src/domain/tracking.rs",
      content: "use crate::platform::windows::foreground;\nuse crate::data::schema;",
    },
    {
      path: "src-tauri/src/engine/export.rs",
      content: [
        "use crate::data::{repositories::sessions, tracking_runtime::Store};",
        "fn takes_pool(pool: sqlx::Pool<sqlx::Sqlite>) {}",
        "fn query() { sqlx::query_scalar(\"SELECT 1\"); }",
        "fn wait() { wait_for_sqlite_pool(); }",
        "fn reverse() { crate::app::runtime::now_ms(); }",
        "fn raw_platform() { windows::Win32::UI::WindowsAndMessaging::GetForegroundWindow(); }",
      ].join("\n"),
    },
  ]);

  assertRules(violations, [
    "entry-layer-no-direct-sql-query",
    "commands-no-sqlite-pool-type",
    "app-no-data-repository-import",
    "app-no-sqlite-pool-access",
    "app-no-sqlite-pool-type",
    "app-no-data-repository-import",
    "entry-layer-no-direct-sql-query",
    "platform-no-data-import",
    "platform-no-app-import",
    "domain-no-data-import",
    "domain-no-platform-import",
    "engine-no-data-import",
    "engine-no-app-import",
    "engine-no-data-repository-import",
    "engine-no-sqlite-pool-type",
    "engine-no-direct-sql-query",
    "engine-no-raw-windows-api",
    "engine-no-wait-for-sqlite-pool",
  ]);
}

function loadFiles() {
  return [
    ...SCAN_ROOTS.flatMap((root) => collectRustFiles(root)),
    ...EXTRA_FILES.map((path) => ({ path, content: readFileSync(path, "utf8") })),
  ];
}

function main() {
  runSelfTest();
  if (process.argv.includes("--self-test")) {
    console.log("Rust boundary self-test passed");
    return;
  }

  const rawViolations = findRustBoundaryViolations(loadFiles());
  if (process.argv.includes("--report-engine-debt")) {
    reportEngineDebt(rawViolations);
    return;
  }

  const violations = applyEngineDebtBaseline(rawViolations);
  if (violations.length === 0) {
    console.log("Rust boundary check passed");
    return;
  }

  console.error("Rust boundary check failed. Keep entry, platform, domain, and engine dependencies honest.");
  for (const violation of violations) {
    console.error(
      `${violation.path}:${violation.line} ${violation.rule} -> ${violation.text} ` +
        "[owner: app composition / engine port / data adapter]",
    );
  }
  process.exitCode = 1;
}

main();
