const ZH_CN_UI_TEXT = {
  common: {
    confirm: "确认",
    cancel: "取消",
    close: "关闭",
    save: "保存",
    saving: "正在保存...",
    saved: "已保存",
    loading: "加载中...",
    processing: "处理中...",
    default: "默认",
    showPassword: "显示密码",
    hidePassword: "隐藏密码",
  },
  dialog: {
    confirm: "确认",
    cancel: "取消",
    confirmDanger: "继续",
  },
  app: {
    loadingView: "正在加载界面...",
    mappingUpdated: "应用映射已更新。",
    historyDeleted: "应用历史已删除。",
    unsavedConfirmTitle: "保存未保存修改",
    unsavedConfirmBody: "当前页面有未保存更改。保存后将自动切换到目标页面。",
    unsavedConfirmSave: "保存",
  },
  widget: {
    tracking: "追踪中",
    sustainedTracking: "持续参与",
    currentApp: "当前应用",
    currentActivityRecording: "当前活动正在记录",
    currentSustainedRecording: "当前持续参与正在记录",
    pause: "暂停",
    resume: "恢复",
    error: "异常",
    trackingService: "追踪服务",
    trackingNotSynced: "追踪状态暂时未同步",
    paused: "已暂停",
    trackingPaused: "追踪已暂停",
    clickToResume: "点击即可恢复追踪",
    idle: "空闲",
    currentlyIdle: "当前空闲中",
    currentAppNotTracked: "当前应用不追踪",
    noTrackableActivity: "当前暂无可追踪活动",
    windowExcluded: "当前窗口不会进入记录",
    loadingStatus: "加载中",
    loadingAppName: "挂件",
    loadingHelper: "正在同步状态",
    pauseTracking: "暂停追踪",
  },
  accessibility: {
    titleBar: {
      minimize: "最小化窗口",
      maximize: "最大化窗口",
      restore: "还原窗口",
      close: "关闭窗口",
    },
    widget: {
      currentApp: (appName: string) => `当前应用：${appName}`,
      openMainWindow: "打开主窗口",
      collapse: "收起挂件",
      expand: "展开挂件",
      toggle: (expanded: boolean, statusTitle: string) => `${expanded ? "收起挂件" : "展开挂件"}，${statusTitle}`,
    },
    data: {
      trendSummary: "趋势摘要",
      trendRange: "选择趋势范围",
      shorterTrendRange: "查看更短趋势范围",
      longerTrendRange: "查看更长趋势范围",
      heatmapRange: "选择热力图范围",
      earlierRange: "查看更早范围",
      newerRange: "查看更新范围",
      appTrendRange: "选择应用趋势范围",
      shorterAppTrendRange: "查看更短应用趋势范围",
      longerAppTrendRange: "查看更长应用趋势范围",
      openTrendRangePicker: "打开趋势范围选择",
      resetTrendRange: "恢复近 7 天",
      previousPickerMode: "上一个范围模式",
      nextPickerMode: "下一个范围模式",
      previousPickerMonth: "上个月",
      nextPickerMonth: "下个月",
    },
    date: {
      previousMonth: "上个月",
      nextMonth: "下个月",
    },
    history: {
      previousMonth: "上个月",
      nextMonth: "下个月",
      decreaseMinDuration: "减少最短时长 1 分钟",
      increaseMinDuration: "增加最短时长 1 分钟",
      toggleActivityDetails: (expanded: boolean, appName: string) => (
        `${expanded ? "收起" : "展开"} ${appName} 的标题详情`
      ),
    },
    settings: {
      toggleTrackingPaused: "切换暂停追踪",
      toggleMinimizeToWidget: "切换最小化到挂件",
      toggleCloseToTray: "切换关闭到托盘",
      toggleBackgroundOptimization: "切换低耗后台",
      toggleLaunchAtLogin: "切换开机自启动",
      toggleStartMinimized: "切换启动时最小化",
      toggleWebActivity: "切换网页同步",
      openWebActivityHelp: "打开网页同步使用说明",
      copyWebActivityPort: "复制网页同步端口",
      copyWebActivityToken: "复制网页同步 Token",
      toggleRemoteStatusBridge: "切换远程推送",
      generateServiceToken: "随机生成 Token",
      showServiceToken: "显示 Token",
      hideServiceToken: "隐藏 Token",
      showRemoteMachineId: "显示本机标识",
      hideRemoteMachineId: "隐藏本机标识",
      colorScheme: "配色方案",
    },
    tools: {
      openStatusChip: "打开工具页面状态",
      createReminder: "创建提醒",
      cancelReminder: "取消提醒",
      startTimer: "开始计时器",
      pauseTimer: "暂停计时器",
      resumeTimer: "继续计时器",
      resetTimer: "重置计时器",
      addTimerLap: "添加分段",
      startPomodoro: "开始番茄钟",
      pausePomodoro: "暂停番茄钟",
      resumePomodoro: "继续番茄钟",
      skipPomodoroPhase: "跳过番茄钟阶段",
      resetPomodoro: "重置番茄钟",
      restorePomodoroDefaults: "恢复番茄钟默认时长",
      decreaseDuration: (label: string) => `${label}减少 1 分钟`,
      increaseDuration: (label: string) => `${label}增加 1 分钟`,
    },
    color: {
      color: "颜色",
      eyedropper: "取色器",
      eyedropperUnsupported: "当前环境不支持取色器",
      colorPicker: "颜色选择器",
      colorFormat: "颜色格式",
    },
  },
  toast: {
    releaseNotesOpenFailed: "无法打开发布说明链接。",
    repositoryOpenFailed: "无法打开 GitHub 链接。",
    feedbackOpenFailed: "无法打开反馈链接。",
    supportOpenFailed: "无法打开赞助链接。",
    settingsRuntimeSyncPartial: "设置已保存，部分运行时同步将在下次刷新后生效。",
    cleanupSuccess: "历史数据已清理。",
    cleanupFailed: "历史数据清理失败，请稍后重试。",
    backupExportSuccess: (path: string) => `备份已创建：${path}`,
    backupExportFailed: "备份失败，请检查路径后重试。",
    backupIncompatible: (reason?: string | null) => `备份不兼容：${reason ?? "无法确认兼容性"}`,
    backupPreviewFailed: "无法预览备份文件，请确认文件后重试。",
    backupRestoreSuccess: "备份已恢复，正在刷新界面。",
    backupRestoreFailed: "备份恢复失败，已自动回滚，不会破坏当前数据。",
    webDavConfigSaved: "WebDAV 配置已保存。",
    webDavConfigSaveFailed: "WebDAV 配置保存失败，请检查后重试。",
    webDavConfigDeleted: "WebDAV 配置已删除。",
    webDavConfigDeleteFailed: "WebDAV 配置删除失败，请稍后重试。",
    webDavMissingConfig: "请先配置 WebDAV 并保存密码。",
    webDavMissingPassword: "请输入 WebDAV 密码或应用密码。",
    webDavTestSuccess: "WebDAV 连接可用。",
    webDavTestFailed: "WebDAV 连接失败，请检查地址、账号和应用密码。",
    webDavUploadSuccess: (fileName: string) => `远程备份已上传：${fileName}`,
    webDavUploadIndexWarning: (fileName: string) => `远程备份已上传：${fileName}，但列表索引更新失败。`,
    webDavUploadFailed: "远程备份上传失败，本地数据未受影响。",
    webDavListFailed: "无法读取远程备份列表。",
    webDavDownloadFailed: "远程备份下载或恢复失败，本地数据未受影响。",
  },
  date: {
    today: "今天",
    yesterday: "昨天",
    pickDate: "选择日期",
    weekdaysShort: ["一", "二", "三", "四", "五", "六", "日"],
    heatmapWeekdays: ["一", "", "三", "", "五", "", "日"],
    monthLabel: (month: number) => `${month}月`,
    yearMonthLabel: (year: number, month: number) => `${year} 年 ${month} 月`,
  },
  time: {
    pickTime: "选择时间",
    hours: "小时",
    minutes: "分钟",
  },
  dashboard: {
    title: "今天",
    subtitle: "查看今天的使用概览",
    tracking: (activeAppName: string) => `正在追踪：${activeAppName}`,
    trackingPaused: "追踪已暂停",
    idle: "空闲",
    afk: "无操作",
    active: "当前活跃",
    paused: "已暂停",
    focusShare: "专注分布",
    total: "总计",
    comparedWithYesterday: (deltaLabel: string, direction: "increase" | "decrease" | "same") => {
      if (direction === "same") return "与昨天持平";
      return `比昨天${direction === "increase" ? "增加" : "减少"} ${deltaLabel}`;
    },
    hourlyActivity: "今日活动",
    showHourlyActivityByCategory: "按分类显示",
    showTotalHourlyActivity: "显示总活动",
    topApps: "应用排行",
    topAppsBadge: (count: number) => `前 ${count} 项`,
    emptyState: "暂无今日记录",
    sharePrefix: "占比",
  },
  hourlyActivityChart: {
    activeMinutes: "活跃",
    remainingCategories: "其他",
  },
  history: {
    title: "历史",
    sessionCount: (count: number) => `${count} 段会话`,
    pastSevenDays: "近 7 天",
    dailyHourlyActivity: "当日活动",
    appDistribution: "应用分布",
    noData: "暂无数据",
    timeline: "时间线",
    loading: "加载中...",
    emptyDay: "这一天暂无记录",
    activitySegmentCount: (count: number) => `活动 ${count}`,
    titleRowCount: (count: number) => `标题 ${count}`,
    titleDetails: "标题详情",
    untilNow: "至今",
  },
  data: {
    title: "数据",
    subtitle: "查看趋势与长期变化",
    pastSevenDays: "近 7 天",
    activityTrend: "活动趋势",
    weeklyTotal: "7 日总时长",
    dailyAverage: "日均时长",
    dailyAverageHint: "按近 7 天计算",
    appTrend: "应用趋势",
    appTrendHint: "查看各应用的每日时长",
    appSearchPlaceholder: "搜索应用",
    appTrendAppList: "应用列表",
    appTrendEmpty: "当前范围暂无应用数据",
    appTrendNoMatch: "没有匹配的应用",
    appTrendTotal: "总时长",
    appTrendAverage: "日均",
    appTrendActiveDays: "活跃天数",
    appTrendPeakDay: "峰值日",
    appTrendUsage: "应用时长",
    appTrendDayBreakdown: "每日明细",
    activityHeatmap: "活动热力图",
    activityHeatmapHint: "每日活动强度",
    heatmapDaily: "每日",
    heatmapWeekly: "每周",
    recentYear: "近一年",
    pastThirtyDays: "近 30 天",
    rangePickerTitle: "选择范围",
    pickerModes: {
      custom: "自定义",
      week: "一周",
      month: "一月",
      year: "一年",
    },
    pickStartDate: "开始日期",
    pickEndDate: "结束日期",
    pickDate: "选择日期",
    shortRangeHint: "当前范围不足 7 天。",
    applyRange: "应用",
    customDayCount: (days: number) => `${days}天`,
    weekLabel: (week: number) => `${week}周`,
    yearLabel: (year: number) => `${year}年`,
    rangeTotal: (label: string) => `${label}总时长`,
    trendTotal: (range: 7 | 30 | 365) => (
      range === 7 ? "7 日总时长" : range === 30 ? "30 日总时长" : "近一年总时长"
    ),
    yearlyAverage: "月均时长",
    yearlyAverageHint: "按近一年月份计算",
    rangeAverageHint: (rangeLabel: string) => `按${rangeLabel}计算`,
    notStarted: "未开始",
    duration: "时长",
    monthlyAverage: "月均",
    less: "少",
    more: "多",
  },
  about: {
    title: "关于",
    subtitle: "版本、更新与支持入口",
    sectionTitle: "关于",
    appInfo: "应用信息",
    currentVersion: (version: string) => `当前版本：v${version}`,
    description: "本地优先的个人桌面时间追踪工具",
  },
  settings: {
    loading: "正在获取配置...",
    title: "设置",
    subtitle: "调整追踪、常驻、数据和外观设置",
    saving: "正在保存...",
    saved: "配置已更新",
    saveFailed: "配置保存失败，请稍后重试。",
    unsaved: "有未保存更改",
    idle: "已保存",
    save: "保存",
    cancel: "取消",
    cancelled: "已撤销本次编辑",
    tracking: "追踪",
    idleTimeoutLabel: "持续计入时间",
    idleTimeoutHint: "当前应用有音频等持续信号时，继续计入这段时间。",
    timelineMergeGapLabel: "活动保持时间",
    timelineMergeGapHint: "无操作后停止计时；短暂切屏返回时，时间线保持连续。",
    minSessionLabel: "时间线最短时长",
    minSessionHint: "只影响时间线展示；排行、分布和总时长仍按真实活动统计。",
    performance: "性能",
    refreshLabel: "刷新间隔",
    refreshHint: "前端界面从后端拉取最新数据的时间间隔。",
    refreshWarning: "较短的刷新频率会增加一定的 CPU 开销。如果你发现界面有些卡顿，建议设置为 5s 及以上。",
    cleanup: "数据管理",
    cleanupTitle: "清理历史记录",
    cleanupHint: "删除所选时间以前的记录，数据无法恢复。",
    cleanupRangeLabel: "清理范围",
    decreaseCleanupRange: "缩短清理范围",
    increaseCleanupRange: "延长清理范围",
    cleanupRunning: "正在清理...",
    cleanupNow: "清理",
    cleanupConfirmTitle: "清理历史数据",
    cleanupConfirmDetail: (label: string) => `将删除 ${label} 及更早的记录。`,
    restoreConfirmTitle: "恢复备份",
    restoreConfirmDetail: (path: string, summary: string, strategy: string) => `恢复策略：${strategy}\n目标文件：${path}\n\n${summary}`,
    confirmRangeFallback: "所选时间",
    confirmCleanup: (label: string) => `确定要清理 ${label} 及更早的所有记录吗？此操作无法撤销。`,
    cleanupRangeLabels: {
      180: "180 天前",
      90: "90 天前",
      60: "60 天前",
      30: "30 天前",
      15: "15 天前",
      7: "7 天前",
    } as Record<number, string>,
    refreshPresets: {
      1: "实时 (1s)",
      3: "平衡 (3s)",
      5: "省电 (5s)",
      10: "低频 (10s)",
    } as Record<number, string>,
    minutePresets: {
      60: "1 分钟",
      180: "3 分钟",
      300: "5 分钟",
      600: "10 分钟",
    } as Record<number, string>,
    trackingPanelTitle: "追踪",
    trackingPausedLabel: "暂停追踪",
    trackingPausedHint: "暂停后不再写入新记录，恢复后继续计时。",
    residentTitle: "常驻",
    minimizeToWidgetLabel: "最小化到挂件",
    minimizeToWidgetHint: "开启后，点最小化时隐藏主窗口并显示侧边挂件。",
    closeToTrayLabel: "关闭到托盘",
    closeToTrayHint: "开启后，点关闭时隐藏窗口并继续后台运行。",
    backgroundOptimizationLabel: "低耗后台",
    backgroundOptimizationHint: "后台闲置时释放主界面内存，重新打开会有轻微卡顿。",
    launchAtLoginLabel: "开机自启动",
    launchAtLoginHint: "开启后，系统登录时自动启动应用。",
    startMinimizedLabel: "启动时最小化",
    startMinimizedHint: "仅对自启动生效：启动时按当前最小化行为收起。",
    servicesTitle: "服务",
    webActivityTitle: "网页同步",
    webActivityEnabledLabel: "网页同步",
    webActivityEnabledHint: "通过浏览器扩展同步当前活动网页。",
    webActivityAddressLabel: "端口",
    webActivityTokenLabel: "Token",
    webActivityHelpAction: "使用说明",
    webActivityHelpCopiedAction: "已复制",
    webActivityHelpCopyPortAction: "复制端口",
    webActivityHelpCopyTokenAction: "复制 Token",
    webActivityHelpTitle: "网页同步使用说明",
    webActivityHelpDescription: "Patina Web Sync 会把当前活动网页同步到本机 Patina。",
    webActivityHelpSteps: [
      {
        title: "准备连接信息",
        description: "扩展需要使用本页的端口和 Token 连接本机 Patina。",
        details: [
          "复制端口和 Token，稍后粘贴到扩展设置中。",
        ],
      },
      {
        title: "安装浏览器扩展",
        description: "在 Chrome / Edge 等 Chromium 系浏览器中加载解压后的扩展文件夹。",
        details: [
          {
            text: "下载 Patina Web Sync 扩展包：patina-chromium-extension-v...zip。",
            links: [
              {
                label: "打开下载页",
                href: "https://github.com/Ceceliaee/patina/releases/latest",
              },
            ],
          },
          "解压这个 zip，得到 patina-chromium-extension-v... 文件夹。",
          "在浏览器地址栏输入 chrome://extensions/ 或 edge://extensions/，打开扩展管理页。",
          "开启「开发者模式」。",
          "点击「加载已解压的扩展程序」或「加载解压缩的扩展」。",
          "选择包含 manifest.json 的扩展文件夹。",
          "不要选择 zip 文件，也不要选择它的上一级目录。",
        ],
      },
      {
        title: "配置扩展",
        description: "打开 Patina Web Sync 设置页，填入本页显示的连接信息。",
        details: [
          "打开浏览器工具栏里的「扩展程序」菜单。",
          "找到 Patina Web Sync 并打开它。",
          "在弹出的扩展窗口中点击「设置」。",
          "粘贴本页显示的端口和 Token。",
          "也可以从扩展管理页进入：找到 Patina Web Sync，点击「详情」/「详细信息」，再点击「扩展程序选项」。",
        ],
      },
      {
        title: "同步当前页",
        description: "打开常规网页后，扩展会同步当前活动页。",
        details: [
          "打开一个 http/https 网页。",
          "等待 Patina Web Sync 自动同步当前页。",
          "如需立即同步一次，可在扩展弹窗中点击「同步当前页」。",
        ],
      },
    ],
    webActivityHelpNote: "Patina Web Sync 启用并连接成功后：\n• 自动同步当前活动标签页的网站地址、标题和网站图标。\n• 不读取网页正文、表单内容、截图或剪贴板。\n• 不扫描或导入浏览器历史记录。\n• 无痕模式窗口不会写入网页记录。",
    remoteStatusBridgeTitle: "远程推送",
    remoteStatusBridgeEnabledHint: "用于向接收地址推送当前追踪状态。",
    remoteStatusBridgeUrlLabel: "接收地址",
    remoteStatusBridgeTokenLabel: "Token",
    remoteStatusBridgeMachineIdLabel: "本机标识",
    countValue: (count: number) => `${count} 个`,
    appearanceTitle: "外观",
    themeModeOptions: {
      light: "浅色",
      dark: "深色",
      system: "跟随系统",
    },
    themeLibraryOptions: {
      light: "浅色主题",
      dark: "深色主题",
    },
    themeModeLabel: "主题模式",
    themeModeHint: "选择浅色、深色，或跟随系统外观自动切换。",
    languageLabel: "语言",
    languageHint: "选择界面显示语言。",
    languageOptions: {
      zhCN: "中文",
      enUS: "English",
    },
    colorSchemeLabel: "配色方案",
    colorSchemeHint: "分别设置浅色和深色主题的整体配色。",
    colorSchemeDialogFallbackTitle: "主题",
    colorSchemeDialogDescription: "选择后会即时预览，保存后生效。",
    colorSchemeSaving: "保存中",
    dataSafetyTitle: "存储",
    backupRestoreTitle: "备份与恢复",
    backupRestoreHint: "包含会话数据、窗口标题明细、设置项和图标缓存。恢复策略决定如何处理当前数据。",
    backupExportTitle: "备份",
    backupExportHint: "备份当前数据快照",
    backupExporting: "备份中...",
    backupExportAction: "备份",
    backupRestoreActionTitle: "恢复",
    backupRestoreActionHint: "从备份恢复数据",
    backupTargetTitle: "选择备份位置",
    backupTargetHint: "选择保存到本地文件，或上传到已绑定的 WebDAV。",
    backupTargetLocalTitle: "本地备份",
    backupTargetLocalHint: "保存为本机 zip 文件",
    backupTargetRemoteTitle: "WebDAV 备份",
    backupTargetRemoteHint: "上传到已绑定的 WebDAV",
    restoreSourceTitle: "选择恢复来源",
    restoreSourceHint: "选择本地备份文件，或从已绑定的 WebDAV 下载。",
    restoreSourceLocalTitle: "本地恢复",
    restoreSourceLocalHint: "选择本机 zip 文件",
    restoreSourceRemoteTitle: "WebDAV 恢复",
    restoreSourceRemoteHint: "从已绑定的 WebDAV 选择备份",
    remoteBackupTitle: "WebDAV 配置",
    remoteBackupHint: "绑定 WebDAV 存储，用于远程备份。",
    webDavConfigure: "配置",
    webDavEdit: "编辑",
    webDavConfigTitle: "WebDAV 配置",
    webDavConfigDescription: "用于远程备份，不会作为云同步使用。",
    webDavServerUrl: "服务器地址",
    webDavUsername: "用户名",
    webDavPassword: "应用密码",
    webDavTestConnection: "测试连接",
    webDavTesting: "测试中...",
    webDavUploadBackup: "上传备份",
    webDavUploading: "上传中...",
    webDavRestoreBackup: "从远端恢复",
    webDavLoadingBackups: "加载中...",
    webDavRestoreSelected: "恢复",
    webDavDeleteTitle: "删除 WebDAV 配置",
    webDavDeleteDetail: "这只会删除本机保存的 WebDAV 配置和密码，不会删除远端备份文件。",
    webDavDeleteAction: "删除",
    webDavRemoteBackupsTitle: "远程备份",
    webDavRemoteBackupsDescription: "选择一份远端备份，下载后会先预览兼容性，再确认恢复。",
    webDavRemoteBackupsEmpty: "远端暂无可用备份。",
    restoreStrategyLabel: "恢复策略",
    restoreStrategyHint: "选择恢复时如何处理当前数据。",
    restoreStrategyOptions: {
      replace: "覆盖",
      merge: "兼容",
    },
    backupRestoring: "恢复中...",
    backupRestoreAction: "恢复",
    minuteValue: (minutes: number) => `${minutes} 分钟`,
    decreaseMinute: (label: string) => `${label}减少 1 分钟`,
    increaseMinute: (label: string) => `${label}增加 1 分钟`,
  },
  tools: {
    title: "工具",
    beta: "Beta",
    subtitle: "本地工具与主动操作",
    remindersTitle: "提醒器",
    reminderModeEvent: "事件",
    reminderModeSoftware: "软件",
    softwareReminderEmpty: "暂无软件使用规则",
    softwareReminderAppLabel: "软件",
    softwareReminderAppPlaceholder: "输入或选择软件",
    softwareReminderDurationLabel: "每日上限（分钟）",
    softwareReminderMessageLabel: "提醒内容",
    softwareReminderMessagePlaceholder: "例如：休息一下",
    softwareReminderRulesTitle: "使用规则",
    softwareReminderStatusLabel: "状态",
    softwareReminderActive: "启用",
    softwareReminderDisable: "停用",
    softwareReminderDailyLimit: (minutes: number) => `每日 ${minutes} 分钟`,
    softwareReminderAppRequired: "请选择已记录的软件。",
    softwareReminderDurationInvalid: "每日上限至少为 1 分钟。",
    newReminder: "新建提醒",
    notificationStatus: "到期通知",
    reminderLabel: "提醒内容",
    reminderLabelPlaceholder: "例如：休息一下",
    defaultReminderLabel: "时间到了",
    reminderModeRelative: "相对时间",
    reminderModeAbsolute: "绝对时间",
    relativeMinutesLabel: "分钟后",
    absoluteDateLabel: "日期",
    absoluteTimeLabel: "时间",
    createReminder: "创建",
    cancelReminder: "取消",
    pendingReminders: "提醒列表",
    reminderStatus: {
      scheduled: "待提醒",
      fired: "已触发",
      cancelled: "已取消",
    },
    reminderEmpty: "暂无待提醒",
    reminderTimeInvalid: "提醒时间必须晚于当前时间。",
    timingTitle: "计时器",
    timingHint: "提醒和计时分别处理。",
    timingModeReminder: "提醒",
    timingModeTimer: "计时",
    timerTitle: "计时器",
    timerHint: "计时不会写入自动追踪记录。",
    timerModeStopwatch: "计时",
    timerModeCountdown: "倒计时",
    timerLabel: "计时名称",
    timerLabelPlaceholder: "可选",
    countdownDuration: "倒计时时长",
    durationPresets: {
      5: "5 分钟",
      10: "10 分钟",
      25: "25 分钟",
      30: "30 分钟",
      60: "60 分钟",
    } as Record<number, string>,
    minuteValue: (minutes: number) => `${minutes} 分钟`,
    timerStatus: {
      idle: "未开始",
      running: "运行中",
      paused: "已暂停",
      completed: "已完成",
    },
    start: "开始",
    pause: "暂停",
    resume: "继续",
    reset: "重置",
    lap: "分段",
    lapsTitle: "分段",
    lapsEmpty: "暂无分段",
    lapIndex: (index: number) => `第 ${index} 段`,
    pomodoroTitle: "番茄钟",
    pomodoroPhase: {
      focus: "专注",
      shortBreak: "短休息",
      longBreak: "长休息",
    },
    pomodoroStatus: {
      idle: "未开始",
      running: "运行中",
      paused: "已暂停",
      completed: "已完成",
    },
    pomodoroCycle: (index: number, every: number) => `第 ${index} / ${every} 个番茄`,
    completedToday: (count: number) => `今日完成 ${count} 个`,
    pomodoroSettings: "默认时长",
    focusDuration: "专注时长",
    shortBreakDuration: "短休息时长",
    longBreakDuration: "长休息时长",
    longBreakEvery: "长休息间隔",
    longBreakEveryValue: (count: number) => `每 ${count} 个番茄`,
    skipPhase: "跳过",
    dueNow: "现在",
    alertOccurredAt: (value: string) => `到点时间：${value}`,
    alertPausePomodoro: "暂停",
    alertPausingPomodoro: "暂停中...",
    alertDismiss: "知道了",
    loadFailed: "工具状态加载失败。",
    actionFailed: "工具操作失败，请稍后重试。",
    statusChip: {
      focus: "专注",
      break: "休息",
      countdown: "倒计时",
      stopwatch: "计时",
      reminder: "提醒",
    },
  },
  mapping: {
    title: "分类",
    subtitle: "设置应用和网页的分类、颜色与记录规则",
    saving: "正在保存...",
    saved: "已保存",
    idle: "已保存",
    unsaved: "有未保存更改",
    save: "保存",
    cancel: "取消",
    categoryControl: "管理分类",
    loading: "加载中...",
    emptyState: "当前筛选下暂无应用",
    webEmptyState: "当前筛选下暂无网页",
    searchPlaceholder: "搜索应用、网页或分类",
    appSearchPlaceholder: "搜索应用或分类",
    webSearchPlaceholder: "搜索网页或分类",
    objectModeApp: "应用",
    objectModeWeb: "网页",
    createCategoryTitle: "新建自定义分类",
    createCategoryDescription: "请输入自定义分类名称（最多 2 个字）。",
    createCategoryPlaceholder: "例如：学习",
    deleteCategoryTitle: "删除分类",
    deleteCategoryDetail: (label: string) => `目标分类：${label}`,
    deleteCategory: (label: string) => `删除分类：${label}`,
    deleteAppSessionsTitle: "删除应用记录",
    deleteAppSessionsDetail: (label: string) => `目标应用：${label}`,
    deleteWebDomainHistoryTitle: "删除网页记录",
    deleteWebDomainHistoryDetail: (label: string) => `目标网页：${label}`,
    filters: {
      all: "全部",
      other: "未分类",
      classified: "已分类",
    },
    categoryDialogTitle: "管理分类",
    categoryDialogDescription: "新建分类，调整分类颜色",
    createCategoryAction: "新建分类",
    editAppName: "修改应用名称",
    editWebDomainName: "修改网页名称",
    color: "颜色",
    restoreDefaultColor: "恢复默认颜色",
    noStats: "不计入统计",
    statsEnabled: "计入统计",
    titleNotRecorded: "不记录标题",
    titleRecorded: "记录标题",
    disableTitleCapture: "不记录该应用窗口标题",
    enableTitleCapture: "恢复记录该应用窗口标题",
    disableTracking: "将该应用排除出统计",
    enableTracking: "重新计入统计",
    disableWebTracking: "停止记录该网页",
    enableWebTracking: "恢复记录该网页",
    deleteAppRecords: "删除应用记录",
    deleteWebRecords: "删除网页记录",
  },
  update: {
    appUpdate: "应用更新",
    sidebarEntry: "更新",
    releaseNotes: "更新说明",
    feedback: "问题反馈",
    support: "赞助项目",
    later: "稍后",
    manualDownload: "手动下载",
    downloadInstaller: "下载安装包",
    redownloadInstaller: "重新下载安装包",
    installAgain: "再次安装",
    checkAgain: "重新检查",
    checkUpdates: "检查更新",
    checkingUpdates: "正在检查更新...",
    checking: "检查中...",
    downloading: "正在下载更新...",
    installing: "正在安装更新...",
    processing: "处理中...",
    foundVersion: (version: string) => `发现新版本：${version}`,
    unknownVersion: "未知版本",
    updateReadyDetail: "新版本可用。确认后开始下载。",
    downloadNow: "立即下载",
    downloadedTitle: (version: string) => `更新已下载：${version}`,
    downloadedDetail: "更新包已下载。确认后重启安装。",
    restartInstall: "重启安装",
    targetVersion: (version: string) => `目标版本：${version}`,
    preparingPackage: "正在准备更新包。",
    installRestartDetail: "安装完成后应用会自动重启。",
    upToDate: "已是最新版本",
    notChecked: "未检查更新",
    checkFailed: "无法检查更新",
    downloadFailed: "无法下载安装包",
    installFailed: "更新安装失败",
    updateFailed: "更新失败",
    checkFailedDialog: "无法检查更新",
    downloadFailedDialog: "下载更新失败",
    installFailedDialog: "安装更新失败",
    updateFailedDialog: "更新失败",
    checkErrorDetail: "无法访问更新清单。当前网络可能无法连接 GitHub，你可以稍后重试，或手动下载。",
    downloadErrorDetail: "已发现新版本，但自动下载安装包失败。你可以手动下载。",
    installErrorDetail: "更新包已下载，但安装没有完成。你可以再次安装，或重新下载。",
    genericErrorDetail: "更新流程未能完成。你可以稍后重试。",
    errorDetailWithSummary: (prefix: string, summary: string) => `${prefix} 详细信息：${summary}`,
    downloadedBytes: (value: string) => `已下载 ${value}`,
    progressPending: "正在获取进度",
    packageDownloaded: (value?: string) => value ? `更新包 ${value} 已下载` : "更新包已下载",
    installingProgress: "正在安装更新，应用将很快重启",
    dialogInstalling: "正在安装更新",
    dialogDownloading: "正在下载更新",
    dialogDownloaded: "更新已下载",
    dialogAvailable: "发现新版本",
    dialogInstallingDetail: "更新安装已开始。请保持应用开启，完成后会自动重启。",
    dialogDownloadingDetail: "更新包正在下载，完成后会切换到安装确认。",
    dialogDownloadedDetail: "更新包已下载。确认后重启并完成安装。",
    dialogAvailableDetail: "新版本可用。确认后先下载更新包，下载完成后再确认安装。",
    updateProcessFailed: "更新流程未能完成。",
  },
  backup: {
    versionLabel: (version: number) => `备份版本：v${version}`,
    schemaLabel: (schemaVersion: number) => `Schema ${schemaVersion}`,
    exportedAt: (value: string) => `导出时间：${value}`,
    appVersion: (version: string) => `应用版本：${version}`,
    restoreSafety: (message: string) => `恢复提示：${message}`,
    itemCounts: (sessionCount: number, settingCount: number, iconCacheCount: number) => (
      `会话数：${sessionCount}，设置项：${settingCount}，图标缓存：${iconCacheCount}`
    ),
  },
  categories: {
    ai: "AI",
    custom: "自定义",
    short: {
      development: "开发",
      office: "办公",
      browser: "浏览",
      communication: "通讯",
      video: "视频",
      music: "音乐",
      game: "游戏",
      design: "设计",
      utility: "工具",
      other: "未分类",
      system: "系统",
    },
    development: "开发编码",
    office: "办公协作",
    browser: "浏览阅读",
    communication: "即时通讯",
    video: "视频内容",
    music: "音乐音频",
    game: "游戏",
    design: "设计创作",
    utility: "工具效率",
    system: "系统工具",
    other: "其他",
  },
};

export type UiLanguage = "zh-CN" | "en-US";
type WidenCopyValue<T> =
  T extends (...args: infer Args) => infer Return
    ? (...args: Args) => WidenCopyValue<Return>
    : T extends string
      ? string
      : T extends number
        ? number
        : T extends boolean
          ? boolean
          : T extends readonly (infer Item)[]
            ? WidenCopyValue<Item>[]
            : T extends Record<PropertyKey, unknown>
              ? { [Key in keyof T]: WidenCopyValue<T[Key]> }
              : T;
export type UiText = WidenCopyValue<typeof ZH_CN_UI_TEXT>;

const EN_US_UI_TEXT: UiText = {
  ...ZH_CN_UI_TEXT,
  common: {
    ...ZH_CN_UI_TEXT.common,
    confirm: "Confirm",
    cancel: "Cancel",
    close: "Close",
    save: "Save",
    saving: "Saving...",
    saved: "Saved",
    loading: "Loading...",
    processing: "Processing...",
    default: "Default",
    showPassword: "Show password",
    hidePassword: "Hide password",
  },
  dialog: {
    confirm: "Confirm",
    cancel: "Cancel",
    confirmDanger: "Continue",
  },
  app: {
    loadingView: "Loading view...",
    mappingUpdated: "App settings updated.",
    historyDeleted: "App history deleted.",
    unsavedConfirmTitle: "Save changes",
    unsavedConfirmBody: "This page has unsaved changes. Save before switching pages.",
    unsavedConfirmSave: "Save",
  },
  widget: {
    tracking: "Tracking",
    sustainedTracking: "Sustained",
    currentApp: "Current app",
    currentActivityRecording: "Current activity is being recorded",
    currentSustainedRecording: "Sustained activity is being recorded",
    pause: "Pause",
    resume: "Resume",
    error: "Error",
    trackingService: "Tracking service",
    trackingNotSynced: "Tracking status is not synced yet",
    paused: "Paused",
    trackingPaused: "Tracking paused",
    clickToResume: "Click to resume tracking",
    idle: "Idle",
    currentlyIdle: "Currently idle",
    currentAppNotTracked: "Current app is not tracked",
    noTrackableActivity: "No trackable activity",
    windowExcluded: "Current window will not be recorded",
    loadingStatus: "Loading",
    loadingAppName: "Widget",
    loadingHelper: "Syncing status",
    pauseTracking: "Pause tracking",
  },
  accessibility: {
    titleBar: {
      minimize: "Minimize window",
      maximize: "Maximize window",
      restore: "Restore window",
      close: "Close window",
    },
    widget: {
      currentApp: (appName: string) => `Current app: ${appName}`,
      openMainWindow: "Open main window",
      collapse: "Collapse widget",
      expand: "Expand widget",
      toggle: (expanded: boolean, statusTitle: string) => `${expanded ? "Collapse widget" : "Expand widget"}, ${statusTitle}`,
    },
    data: {
      trendSummary: "Trend summary",
      trendRange: "Select trend range",
      shorterTrendRange: "Show shorter trend range",
      longerTrendRange: "Show longer trend range",
      heatmapRange: "Select heatmap range",
      earlierRange: "Show earlier range",
      newerRange: "Show newer range",
      appTrendRange: "Select app trend range",
      shorterAppTrendRange: "Show shorter app trend range",
      longerAppTrendRange: "Show longer app trend range",
      openTrendRangePicker: "Open trend range picker",
      resetTrendRange: "Reset to last 7 days",
      previousPickerMode: "Previous range mode",
      nextPickerMode: "Next range mode",
      previousPickerMonth: "Previous month",
      nextPickerMonth: "Next month",
    },
    date: {
      previousMonth: "Previous month",
      nextMonth: "Next month",
    },
    history: {
      previousMonth: "Previous month",
      nextMonth: "Next month",
      decreaseMinDuration: "Decrease minimum duration by 1 minute",
      increaseMinDuration: "Increase minimum duration by 1 minute",
      toggleActivityDetails: (expanded: boolean, appName: string) => (
        `${expanded ? "Collapse" : "Expand"} title details for ${appName}`
      ),
    },
    settings: {
      toggleTrackingPaused: "Toggle pause tracking",
      toggleMinimizeToWidget: "Toggle minimize to widget",
      toggleCloseToTray: "Toggle close to tray",
      toggleBackgroundOptimization: "Toggle low-footprint background",
      toggleLaunchAtLogin: "Toggle launch at login",
      toggleStartMinimized: "Toggle start minimized",
      toggleWebActivity: "Toggle web sync",
      openWebActivityHelp: "Open web sync guide",
      copyWebActivityPort: "Copy web sync port",
      copyWebActivityToken: "Copy web sync Token",
      toggleRemoteStatusBridge: "Toggle remote push",
      generateServiceToken: "Generate token",
      showServiceToken: "Show token",
      hideServiceToken: "Hide token",
      showRemoteMachineId: "Show device ID",
      hideRemoteMachineId: "Hide device ID",
      colorScheme: "Color scheme",
    },
    tools: {
      openStatusChip: "Open tools status",
      createReminder: "Create reminder",
      cancelReminder: "Cancel reminder",
      startTimer: "Start timer",
      pauseTimer: "Pause timer",
      resumeTimer: "Resume timer",
      resetTimer: "Reset timer",
      addTimerLap: "Add lap",
      startPomodoro: "Start pomodoro",
      pausePomodoro: "Pause pomodoro",
      resumePomodoro: "Resume pomodoro",
      skipPomodoroPhase: "Skip pomodoro phase",
      resetPomodoro: "Reset pomodoro",
      restorePomodoroDefaults: "Restore pomodoro default durations",
      decreaseDuration: (label: string) => `Decrease ${label} by 1 minute`,
      increaseDuration: (label: string) => `Increase ${label} by 1 minute`,
    },
    color: {
      color: "Color",
      eyedropper: "Eyedropper",
      eyedropperUnsupported: "Eyedropper is unavailable",
      colorPicker: "Color picker",
      colorFormat: "Color format",
    },
  },
  toast: {
    releaseNotesOpenFailed: "Could not open release notes.",
    repositoryOpenFailed: "Could not open GitHub link.",
    feedbackOpenFailed: "Could not open feedback link.",
    supportOpenFailed: "Could not open support link.",
    settingsRuntimeSyncPartial: "Settings were saved. Some runtime changes will apply after the next refresh.",
    cleanupSuccess: "History records cleared.",
    cleanupFailed: "Could not clear history records. Try again later.",
    backupExportSuccess: (path: string) => `Backup created: ${path}`,
    backupExportFailed: "Could not create backup. Check the path and try again.",
    backupIncompatible: (reason?: string | null) => `Backup is incompatible: ${reason ?? "compatibility could not be confirmed"}`,
    backupPreviewFailed: "Could not preview this backup file. Check the file and try again.",
    backupRestoreSuccess: "Backup restored. Refreshing view.",
    backupRestoreFailed: "Backup restore failed. Changes were rolled back and current data is safe.",
    webDavConfigSaved: "WebDAV configuration saved.",
    webDavConfigSaveFailed: "Could not save WebDAV configuration. Check it and try again.",
    webDavConfigDeleted: "WebDAV configuration deleted.",
    webDavConfigDeleteFailed: "Could not delete WebDAV configuration. Try again later.",
    webDavMissingConfig: "Configure WebDAV and save the password first.",
    webDavMissingPassword: "Enter the WebDAV password or app password.",
    webDavTestSuccess: "WebDAV connection is available.",
    webDavTestFailed: "WebDAV connection failed. Check the address, username, and app password.",
    webDavUploadSuccess: (fileName: string) => `Remote backup uploaded: ${fileName}`,
    webDavUploadIndexWarning: (fileName: string) => `Remote backup uploaded: ${fileName}, but the list index could not be updated.`,
    webDavUploadFailed: "Remote backup upload failed. Local data was not changed.",
    webDavListFailed: "Could not read the remote backup list.",
    webDavDownloadFailed: "Remote backup download or restore failed. Local data was not changed.",
  },
  date: {
    today: "Today",
    yesterday: "Yesterday",
    pickDate: "Select date",
    weekdaysShort: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    heatmapWeekdays: ["Mon", "", "Wed", "", "Fri", "", "Sun"],
    monthLabel: (month: number) => new Date(2020, month - 1, 1).toLocaleString("en-US", { month: "short" }),
    yearMonthLabel: (year: number, month: number) => `${new Date(year, month - 1, 1).toLocaleString("en-US", { month: "long" })} ${year}`,
  },
  time: {
    pickTime: "Select time",
    hours: "Hour",
    minutes: "Minute",
  },
  dashboard: {
    title: "Today",
    subtitle: "Review today's usage overview",
    tracking: (activeAppName: string) => `Tracking: ${activeAppName}`,
    trackingPaused: "Tracking paused",
    idle: "Idle",
    afk: "Idle",
    active: "Active now",
    paused: "Paused",
    focusShare: "Focus share",
    total: "Total",
    comparedWithYesterday: (deltaLabel: string, direction: "increase" | "decrease" | "same") => {
      if (direction === "same") return "Same as yesterday";
      return `${direction === "increase" ? "Up" : "Down"} ${deltaLabel} from yesterday`;
    },
    hourlyActivity: "Today's Activity",
    showHourlyActivityByCategory: "Show by category",
    showTotalHourlyActivity: "Show total activity",
    topApps: "Top Apps",
    topAppsBadge: (count: number) => `Top ${count}`,
    emptyState: "No records today",
    sharePrefix: "Share",
  },
  hourlyActivityChart: {
    activeMinutes: "Active",
    remainingCategories: "Other",
  },
  history: {
    title: "History",
    sessionCount: (count: number) => `${count} sessions`,
    pastSevenDays: "Last 7 days",
    dailyHourlyActivity: "Daily Activity",
    appDistribution: "App Distribution",
    noData: "No data",
    timeline: "Timeline",
    loading: "Loading...",
    emptyDay: "No records for this day",
    activitySegmentCount: (count: number) => `Act ${count}`,
    titleRowCount: (count: number) => `Titles ${count}`,
    titleDetails: "Title details",
    untilNow: "until now",
  },
  data: {
    title: "Data",
    subtitle: "Review trends and long-term changes",
    pastSevenDays: "Last 7 days",
    activityTrend: "Activity Trend",
    weeklyTotal: "7-day total",
    dailyAverage: "Daily avg.",
    dailyAverageHint: "Based on last 7 days",
    appTrend: "App Trends",
    appTrendHint: "View daily time by app",
    appSearchPlaceholder: "Search apps",
    appTrendAppList: "App list",
    appTrendEmpty: "No app data in this range",
    appTrendNoMatch: "No matching apps",
    appTrendTotal: "Total",
    appTrendAverage: "Daily avg.",
    appTrendActiveDays: "Active days",
    appTrendPeakDay: "Peak day",
    appTrendUsage: "App time",
    appTrendDayBreakdown: "Daily details",
    activityHeatmap: "Activity Heatmap",
    activityHeatmapHint: "Daily activity intensity",
    heatmapDaily: "Daily",
    heatmapWeekly: "Weekly",
    recentYear: "Past year",
    pastThirtyDays: "Last 30 days",
    rangePickerTitle: "Select range",
    pickerModes: {
      custom: "Custom",
      week: "Week",
      month: "Month",
      year: "Year",
    },
    pickStartDate: "Start date",
    pickEndDate: "End date",
    pickDate: "Select date",
    shortRangeHint: "The current range is shorter than 7 days.",
    applyRange: "Apply",
    customDayCount: (days: number) => `${days} days`,
    weekLabel: (week: number) => `Week ${week}`,
    yearLabel: (year: number) => String(year),
    rangeTotal: (label: string) => `${label} total`,
    trendTotal: (range: 7 | 30 | 365) => (
      range === 7 ? "7-day total" : range === 30 ? "30-day total" : "Past year total"
    ),
    yearlyAverage: "Monthly avg.",
    yearlyAverageHint: "Based on months in the past year",
    rangeAverageHint: (rangeLabel: string) => `Based on ${rangeLabel}`,
    notStarted: "Not started",
    duration: "Duration",
    monthlyAverage: "Monthly avg.",
    less: "Less",
    more: "More",
  },
  about: {
    title: "About",
    subtitle: "Version, updates, and support links",
    sectionTitle: "About",
    appInfo: "App info",
    currentVersion: (version: string) => `Current version: v${version}`,
    description: "A local-first personal desktop time tracker",
  },
  settings: {
    ...ZH_CN_UI_TEXT.settings,
    loading: "Loading settings...",
    title: "Settings",
    subtitle: "Adjust tracking, resident, data, and appearance settings",
    saving: "Saving...",
    saved: "Settings updated",
    saveFailed: "Could not save settings. Try again later.",
    unsaved: "Unsaved changes",
    idle: "Saved",
    save: "Save",
    cancel: "Cancel",
    cancelled: "Edits discarded",
    tracking: "Tracking",
    idleTimeoutLabel: "Continue counting",
    idleTimeoutHint: "When the current app has audio or similar signals, keep counting this time.",
    timelineMergeGapLabel: "Activity hold time",
    timelineMergeGapHint: "Stop counting after idle time; brief app switches stay continuous on the timeline.",
    minSessionLabel: "Timeline minimum",
    minSessionHint: "Only affects timeline display; rankings, distribution, and totals still use real activity.",
    performance: "Performance",
    refreshLabel: "Refresh interval",
    refreshHint: "How often the interface pulls fresh data from the backend.",
    refreshWarning: "Shorter refresh intervals can increase CPU usage. Use 5s or above if the UI feels slow.",
    cleanup: "Data management",
    cleanupTitle: "Clear history records",
    cleanupHint: "Delete records older than the selected range. Data cannot be restored.",
    cleanupRangeLabel: "Clear range",
    decreaseCleanupRange: "Shorten clear range",
    increaseCleanupRange: "Extend clear range",
    cleanupRunning: "Clearing...",
    cleanupNow: "Clear",
    cleanupConfirmTitle: "Clear history",
    cleanupConfirmDetail: (label: string) => `Records from ${label} and earlier will be deleted.`,
    restoreConfirmTitle: "Restore backup",
    restoreConfirmDetail: (path: string, summary: string, strategy: string) => `Restore strategy: ${strategy}\nTarget file: ${path}\n\n${summary}`,
    confirmRangeFallback: "selected range",
    confirmCleanup: (label: string) => `Clear all records from ${label} and earlier? This cannot be undone.`,
    cleanupRangeLabels: {
      180: "180 days ago",
      90: "90 days ago",
      60: "60 days ago",
      30: "30 days ago",
      15: "15 days ago",
      7: "7 days ago",
    } as Record<number, string>,
    refreshPresets: {
      1: "Realtime (1s)",
      3: "Balanced (3s)",
      5: "Battery saver (5s)",
      10: "Low frequency (10s)",
    } as Record<number, string>,
    minutePresets: {
      60: "1 minute",
      180: "3 minutes",
      300: "5 minutes",
      600: "10 minutes",
    } as Record<number, string>,
    trackingPanelTitle: "Tracking",
    trackingPausedLabel: "Pause tracking",
    trackingPausedHint: "Paused tracking will stop writing new records. Resume to continue.",
    residentTitle: "Resident",
    minimizeToWidgetLabel: "Minimize to widget",
    minimizeToWidgetHint: "When minimized, hide the main window and show the side widget.",
    closeToTrayLabel: "Close to tray",
    closeToTrayHint: "When closed, hide the window and keep running in the background.",
    backgroundOptimizationLabel: "Low-footprint background",
    backgroundOptimizationHint: "Release main UI memory while idle in background. Reopening may feel slightly slower.",
    launchAtLoginLabel: "Launch at login",
    launchAtLoginHint: "Start the app automatically when Windows signs in.",
    startMinimizedLabel: "Start minimized",
    startMinimizedHint: "Only applies to launch at login. Starts with the current minimize behavior.",
    servicesTitle: "Services",
    webActivityTitle: "Web sync",
    webActivityEnabledLabel: "Web sync",
    webActivityEnabledHint: "Syncs active web pages through the browser extension.",
    webActivityAddressLabel: "Port",
    webActivityTokenLabel: "Token",
    webActivityHelpAction: "Guide",
    webActivityHelpCopiedAction: "Copied",
    webActivityHelpCopyPortAction: "Copy port",
    webActivityHelpCopyTokenAction: "Copy Token",
    webActivityHelpTitle: "Web Sync Guide",
    webActivityHelpDescription: "Patina Web Sync sends the active webpage to the local Patina desktop app.",
    webActivityHelpSteps: [
      {
        title: "Prepare connection details",
        description: "The extension uses this page's port and Token to connect to the local Patina app.",
        details: [
          "Copy the port and Token, then paste them into the extension settings later.",
        ],
      },
      {
        title: "Install the browser extension",
        description: "Load the extracted extension folder in Chrome, Edge, or another Chromium-based browser.",
        details: [
          {
            text: "Download the Patina Web Sync extension package: patina-chromium-extension-v...zip.",
            links: [
              {
                label: "Open downloads",
                href: "https://github.com/Ceceliaee/patina/releases/latest",
              },
            ],
          },
          "Extract the zip to get the patina-chromium-extension-v... folder.",
          "Enter chrome://extensions/ or edge://extensions/ in the browser address bar to open extension management.",
          "Enable Developer mode.",
          "Click Load unpacked or Load extracted extension.",
          "Select the extension folder that contains manifest.json.",
          "Do not select the zip file or its parent folder.",
        ],
      },
      {
        title: "Configure the extension",
        description: "Open the Patina Web Sync settings page and enter the connection details shown here.",
        details: [
          "Open the Extensions menu in the browser toolbar.",
          "Find Patina Web Sync and open it.",
          "Click Settings in the extension popup.",
          "Paste the port and Token shown on this page.",
          "You can also enter from the extensions management page: find Patina Web Sync, click Details, then click Extension options.",
        ],
      },
      {
        title: "Sync the current page",
        description: "After you open a regular webpage, the extension syncs the active page.",
        details: [
          "Open an http/https webpage.",
          "Wait for Patina Web Sync to automatically sync the current page.",
          "To sync once immediately, click Sync current page in the extension popup.",
        ],
      },
    ],
    webActivityHelpNote: "After Patina Web Sync is enabled and connected:\n• Automatically syncs the active tab's website address, title, and website icon.\n• Does not read page body content, form values, screenshots, or clipboard contents.\n• Does not scan or import browser history.\n• Incognito windows are not written to web records.",
    remoteStatusBridgeTitle: "Remote push",
    remoteStatusBridgeEnabledHint: "Pushes the current tracking status to the endpoint.",
    remoteStatusBridgeUrlLabel: "Endpoint URL",
    remoteStatusBridgeTokenLabel: "Token",
    remoteStatusBridgeMachineIdLabel: "Device ID",
    countValue: (count: number) => `${count}`,
    appearanceTitle: "Appearance",
    themeModeOptions: {
      light: "Light",
      dark: "Dark",
      system: "System",
    },
    themeLibraryOptions: {
      light: "Light theme",
      dark: "Dark theme",
    },
    themeModeLabel: "Theme mode",
    themeModeHint: "Use light, dark, or follow the system appearance.",
    languageLabel: "Language",
    languageHint: "Choose the interface language.",
    languageOptions: {
      zhCN: "中文",
      enUS: "English",
    },
    colorSchemeLabel: "Color scheme",
    colorSchemeHint: "Set the overall color style for light and dark themes.",
    colorSchemeDialogFallbackTitle: "Theme",
    colorSchemeDialogDescription: "Preview now. Save to apply.",
    colorSchemeSaving: "Saving",
    dataSafetyTitle: "Storage",
    backupRestoreTitle: "Backup and restore",
    backupRestoreHint: "Includes sessions, window title details, settings, and cached icons. The restore strategy decides how current data is handled.",
    backupExportTitle: "Back up",
    backupExportHint: "Create a backup of current data",
    backupExporting: "Backing up...",
    backupExportAction: "Back up",
    backupRestoreActionTitle: "Restore",
    backupRestoreActionHint: "Restore data from a backup",
    backupTargetTitle: "Choose backup location",
    backupTargetHint: "Save a local file or upload to the linked WebDAV target.",
    backupTargetLocalTitle: "Local backup",
    backupTargetLocalHint: "Save as a local zip file",
    backupTargetRemoteTitle: "WebDAV backup",
    backupTargetRemoteHint: "Upload to the linked WebDAV target",
    restoreSourceTitle: "Choose restore source",
    restoreSourceHint: "Choose a local backup file or download from the linked WebDAV target.",
    restoreSourceLocalTitle: "Local restore",
    restoreSourceLocalHint: "Choose a local zip file",
    restoreSourceRemoteTitle: "WebDAV restore",
    restoreSourceRemoteHint: "Choose a backup from the linked WebDAV target",
    remoteBackupTitle: "WebDAV configuration",
    remoteBackupHint: "Link WebDAV storage for remote backups.",
    webDavConfigure: "Configure",
    webDavEdit: "Edit",
    webDavConfigTitle: "WebDAV configuration",
    webDavConfigDescription: "Used for remote backup only, not cloud sync.",
    webDavServerUrl: "Server address",
    webDavUsername: "Username",
    webDavPassword: "App password",
    webDavTestConnection: "Test connection",
    webDavTesting: "Testing...",
    webDavUploadBackup: "Upload backup",
    webDavUploading: "Uploading...",
    webDavRestoreBackup: "Restore from remote",
    webDavLoadingBackups: "Loading...",
    webDavRestoreSelected: "Restore",
    webDavDeleteTitle: "Delete WebDAV configuration",
    webDavDeleteDetail: "This only removes the local WebDAV settings and password. Remote backup files are not deleted.",
    webDavDeleteAction: "Delete",
    webDavRemoteBackupsTitle: "Remote backups",
    webDavRemoteBackupsDescription: "Choose a remote backup. It will be downloaded and previewed before restore confirmation.",
    webDavRemoteBackupsEmpty: "No remote backups available.",
    restoreStrategyLabel: "Restore strategy",
    restoreStrategyHint: "Choose how restore handles current data.",
    restoreStrategyOptions: {
      replace: "Replace",
      merge: "Merge",
    },
    backupRestoring: "Restoring...",
    backupRestoreAction: "Restore",
    minuteValue: (minutes: number) => `${minutes} min`,
    decreaseMinute: (label: string) => `Decrease ${label} by 1 minute`,
    increaseMinute: (label: string) => `Increase ${label} by 1 minute`,
  },
  tools: {
    title: "Tools",
    beta: "Beta",
    subtitle: "Local tools and active actions",
    remindersTitle: "Reminder",
    reminderModeEvent: "Event",
    reminderModeSoftware: "Software",
    softwareReminderEmpty: "No software usage rules",
    softwareReminderAppLabel: "App",
    softwareReminderAppPlaceholder: "Type or select app",
    softwareReminderDurationLabel: "Daily limit (min)",
    softwareReminderMessageLabel: "Message",
    softwareReminderMessagePlaceholder: "Example: take a break",
    softwareReminderRulesTitle: "Usage rules",
    softwareReminderStatusLabel: "Status",
    softwareReminderActive: "Active",
    softwareReminderDisable: "Disable",
    softwareReminderDailyLimit: (minutes: number) => `${minutes} min daily`,
    softwareReminderAppRequired: "Select a recorded app.",
    softwareReminderDurationInvalid: "Daily limit must be at least 1 minute.",
    newReminder: "New reminder",
    notificationStatus: "Due notifications",
    reminderLabel: "Reminder",
    reminderLabelPlaceholder: "Example: take a break",
    defaultReminderLabel: "Time is up",
    reminderModeRelative: "Relative time",
    reminderModeAbsolute: "Exact time",
    relativeMinutesLabel: "Minutes from now",
    absoluteDateLabel: "Date",
    absoluteTimeLabel: "Time",
    createReminder: "Create",
    cancelReminder: "Cancel",
    pendingReminders: "Reminder list",
    reminderStatus: {
      scheduled: "Scheduled",
      fired: "Fired",
      cancelled: "Cancelled",
    },
    reminderEmpty: "No pending reminders",
    reminderTimeInvalid: "Reminder time must be in the future.",
    timingTitle: "Timer",
    timingHint: "Reminders and timers are separate tools.",
    timingModeReminder: "Reminder",
    timingModeTimer: "Timer",
    timerTitle: "Timer",
    timerHint: "Timer time is not written to automatic tracking records.",
    timerModeStopwatch: "Count up",
    timerModeCountdown: "Countdown",
    timerLabel: "Timer name",
    timerLabelPlaceholder: "Optional",
    countdownDuration: "Countdown duration",
    durationPresets: {
      5: "5 min",
      10: "10 min",
      25: "25 min",
      30: "30 min",
      60: "60 min",
    } as Record<number, string>,
    minuteValue: (minutes: number) => `${minutes} min`,
    timerStatus: {
      idle: "Not started",
      running: "Running",
      paused: "Paused",
      completed: "Completed",
    },
    start: "Start",
    pause: "Pause",
    resume: "Resume",
    reset: "Reset",
    lap: "Lap",
    lapsTitle: "Laps",
    lapsEmpty: "No laps",
    lapIndex: (index: number) => `Lap ${index}`,
    pomodoroTitle: "Pomodoro",
    pomodoroPhase: {
      focus: "Focus",
      shortBreak: "Short break",
      longBreak: "Long break",
    },
    pomodoroStatus: {
      idle: "Not started",
      running: "Running",
      paused: "Paused",
      completed: "Completed",
    },
    pomodoroCycle: (index: number, every: number) => `${index} / ${every} pomodoro`,
    completedToday: (count: number) => `${count} completed today`,
    pomodoroSettings: "Default durations",
    focusDuration: "Focus duration",
    shortBreakDuration: "Short break",
    longBreakDuration: "Long break",
    longBreakEvery: "Long break interval",
    longBreakEveryValue: (count: number) => `Every ${count} pomodoros`,
    skipPhase: "Skip",
    dueNow: "Now",
    alertOccurredAt: (value: string) => `Due at ${value}`,
    alertPausePomodoro: "Pause",
    alertPausingPomodoro: "Pausing...",
    alertDismiss: "Got it",
    loadFailed: "Could not load tools status.",
    actionFailed: "Tool action failed. Try again later.",
    statusChip: {
      focus: "Focus",
      break: "Break",
      countdown: "Countdown",
      stopwatch: "Timer",
      reminder: "Reminder",
    },
  },
  mapping: {
    ...ZH_CN_UI_TEXT.mapping,
    title: "Classify",
    subtitle: "Set categories, colors, and recording rules for apps and websites",
    saving: "Saving...",
    saved: "Saved",
    idle: "Saved",
    unsaved: "Unsaved changes",
    save: "Save",
    cancel: "Cancel",
    categoryControl: "Manage categories",
    loading: "Loading...",
    emptyState: "No apps match the current filter",
    webEmptyState: "No websites match the current filter",
    searchPlaceholder: "Search apps, websites, or categories",
    appSearchPlaceholder: "Search apps or categories",
    webSearchPlaceholder: "Search websites or categories",
    objectModeApp: "Apps",
    objectModeWeb: "Web",
    createCategoryTitle: "New custom category",
    createCategoryDescription: "Enter one short category word.",
    createCategoryPlaceholder: "Example: Study",
    deleteCategoryTitle: "Delete category",
    deleteCategoryDetail: (label: string) => `Target category: ${label}`,
    deleteCategory: (label: string) => `Delete category: ${label}`,
    deleteAppSessionsTitle: "Delete app records",
    deleteAppSessionsDetail: (label: string) => `Target app: ${label}`,
    deleteWebDomainHistoryTitle: "Delete web records",
    deleteWebDomainHistoryDetail: (label: string) => `Target website: ${label}`,
    filters: {
      all: "All",
      other: "Unclassified",
      classified: "Classified",
    },
    categoryDialogTitle: "Manage categories",
    categoryDialogDescription: "Create categories and adjust category colors",
    createCategoryAction: "New category",
    editAppName: "Edit app name",
    editWebDomainName: "Edit website name",
    color: "Color",
    restoreDefaultColor: "Restore default color",
    noStats: "Excluded",
    statsEnabled: "Included",
    titleNotRecorded: "No title",
    titleRecorded: "Record title",
    disableTitleCapture: "Stop recording this app's window titles",
    enableTitleCapture: "Resume recording this app's window titles",
    disableTracking: "Exclude this app from statistics",
    enableTracking: "Include this app in statistics",
    disableWebTracking: "Stop recording this website",
    enableWebTracking: "Resume recording this website",
    deleteAppRecords: "Delete records",
    deleteWebRecords: "Delete web records",
  },
  update: {
    appUpdate: "App updates",
    sidebarEntry: "Update",
    releaseNotes: "Release notes",
    feedback: "Feedback",
    support: "Sponsor",
    later: "Later",
    manualDownload: "Manual download",
    downloadInstaller: "Download installer",
    redownloadInstaller: "Download again",
    installAgain: "Install again",
    checkAgain: "Check again",
    checkUpdates: "Check updates",
    checkingUpdates: "Checking for updates...",
    checking: "Checking...",
    downloading: "Downloading update...",
    installing: "Installing update...",
    processing: "Processing...",
    foundVersion: (version: string) => `New version: ${version}`,
    unknownVersion: "unknown version",
    updateReadyDetail: "A new version is available. Confirm to start downloading.",
    downloadNow: "Download now",
    downloadedTitle: (version: string) => `Update downloaded: ${version}`,
    downloadedDetail: "The update package is downloaded. Confirm to restart and install.",
    restartInstall: "Restart to install",
    targetVersion: (version: string) => `Target version: ${version}`,
    preparingPackage: "Preparing the update package.",
    installRestartDetail: "The app will restart after installation.",
    upToDate: "You are up to date",
    notChecked: "Not checked",
    checkFailed: "Could not check updates",
    downloadFailed: "Could not download installer",
    installFailed: "Update installation failed",
    updateFailed: "Update failed",
    checkFailedDialog: "Could not check updates",
    downloadFailedDialog: "Download failed",
    installFailedDialog: "Install failed",
    updateFailedDialog: "Update failed",
    checkErrorDetail: "Could not access the update manifest. Your current network may not be able to reach GitHub. Try again later or download manually.",
    downloadErrorDetail: "A new version was found, but automatic download failed. You can download manually.",
    installErrorDetail: "The update package was downloaded, but installation did not finish. Try installing again or redownload it.",
    genericErrorDetail: "The update flow could not finish. Try again later.",
    errorDetailWithSummary: (prefix: string, summary: string) => `${prefix} Details: ${summary}`,
    downloadedBytes: (value: string) => `Downloaded ${value}`,
    progressPending: "Getting progress",
    packageDownloaded: (value?: string) => value ? `Package ${value} downloaded` : "Package downloaded",
    installingProgress: "Installing update. The app will restart soon.",
    dialogInstalling: "Installing update",
    dialogDownloading: "Downloading update",
    dialogDownloaded: "Update downloaded",
    dialogAvailable: "New version available",
    dialogInstallingDetail: "Installation has started. Keep the app open; it will restart when finished.",
    dialogDownloadingDetail: "The update package is downloading. Installation confirmation appears when it finishes.",
    dialogDownloadedDetail: "The update package is ready. Confirm to restart and finish installation.",
    dialogAvailableDetail: "A new version is available. Download first, then confirm installation.",
    updateProcessFailed: "The update flow could not finish.",
  },
  backup: {
    versionLabel: (version: number) => `Backup version: v${version}`,
    schemaLabel: (schemaVersion: number) => `Schema ${schemaVersion}`,
    exportedAt: (value: string) => `Exported at: ${value}`,
    appVersion: (version: string) => `App version: ${version}`,
    restoreSafety: (message: string) => `Restore status: ${message}`,
    itemCounts: (sessionCount: number, settingCount: number, iconCacheCount: number) => (
      `Sessions: ${sessionCount}, settings: ${settingCount}, cached icons: ${iconCacheCount}`
    ),
  },
  categories: {
    ai: "AI",
    custom: "Custom",
    short: {
      development: "Dev",
      office: "Office",
      browser: "Browser",
      communication: "Chat",
      video: "Video",
      music: "Music",
      game: "Games",
      design: "Design",
      utility: "Tools",
      other: "Other",
      system: "System",
    },
    development: "Development",
    office: "Office",
    browser: "Browser",
    communication: "Communication",
    video: "Video",
    music: "Music",
    game: "Games",
    design: "Design",
    utility: "Utilities",
    system: "System",
    other: "Other",
  },
};

export const COPY: Record<UiLanguage, UiText> = {
  "zh-CN": ZH_CN_UI_TEXT,
  "en-US": EN_US_UI_TEXT,
};

export const SUPPORTED_UI_LANGUAGES = Object.keys(COPY) as UiLanguage[];

let activeUiLanguage: UiLanguage = "zh-CN";
let activeUiText: UiText = ZH_CN_UI_TEXT;

export function getUiText(language: UiLanguage): UiText {
  return COPY[language] ?? ZH_CN_UI_TEXT;
}

export function getUiTextLanguage(): UiLanguage {
  return activeUiLanguage;
}

export function getUiLocale(): UiLanguage {
  return activeUiLanguage;
}

export function setUiTextLanguage(language: UiLanguage): void {
  activeUiLanguage = COPY[language] ? language : "zh-CN";
  activeUiText = getUiText(activeUiLanguage);
}

export const UI_TEXT: UiText = new Proxy({} as UiText, {
  get(_target, property: keyof UiText) {
    return activeUiText[property];
  },
});
