const ZH_CN_UI_TEXT = {
  common: {
    confirm: "确认",
    cancel: "取消",
    close: "关闭",
    save: "保存",
    saving: "正在保存...",
    saved: "已保存",
    loading: "加载中...",
    processing: "处理中...",
    default: "默认",
  },
  dialog: {
    confirm: "确认",
    cancel: "取消",
    confirmDanger: "继续",
  },
  app: {
    loadingView: "正在加载界面...",
    mappingUpdated: "应用映射已更新。",
    historyDeleted: "应用历史已删除。",
    unsavedConfirmTitle: "保存未保存修改",
    unsavedConfirmBody: "当前页面有未保存更改。保存后将自动切换到目标页面。",
    unsavedConfirmSave: "保存",
  },
  widget: {
    tracking: "追踪中",
    sustainedTracking: "持续参与",
    currentApp: "当前应用",
    currentActivityRecording: "当前活动正在记录",
    currentSustainedRecording: "当前持续参与正在记录",
    pause: "暂停",
    resume: "恢复",
    error: "异常",
    trackingService: "追踪服务",
    trackingNotSynced: "追踪状态暂时未同步",
    paused: "已暂停",
    trackingPaused: "追踪已暂停",
    clickToResume: "点击即可恢复追踪",
    idle: "空闲",
    currentlyIdle: "当前空闲中",
    currentAppNotTracked: "当前应用不追踪",
    noTrackableActivity: "当前暂无可追踪活动",
    windowExcluded: "当前窗口不会进入记录",
    loadingStatus: "加载中",
    loadingAppName: "挂件",
    loadingHelper: "正在同步状态",
    pauseTracking: "暂停追踪",
  },
  accessibility: {
    titleBar: {
      minimize: "最小化窗口",
      maximize: "最大化窗口",
      restore: "还原窗口",
      close: "关闭窗口",
    },
    widget: {
      currentApp: (appName: string) => `当前应用：${appName}`,
      openMainWindow: "打开主窗口",
      collapse: "收起挂件",
      expand: "展开挂件",
      toggle: (expanded: boolean, statusTitle: string) => `${expanded ? "收起挂件" : "展开挂件"}，${statusTitle}`,
    },
    data: {
      trendSummary: "趋势摘要",
      trendRange: "选择趋势范围",
      shorterTrendRange: "查看更短趋势范围",
      longerTrendRange: "查看更长趋势范围",
      heatmapRange: "选择热力图范围",
      earlierRange: "查看更早范围",
      newerRange: "查看更新范围",
      appTrendRange: "选择应用趋势范围",
      shorterAppTrendRange: "查看更短应用趋势范围",
      longerAppTrendRange: "查看更长应用趋势范围",
    },
    history: {
      previousMonth: "上个月",
      nextMonth: "下个月",
      decreaseMinDuration: "减少最短时长 1 分钟",
      increaseMinDuration: "增加最短时长 1 分钟",
      toggleActivityDetails: (expanded: boolean, appName: string) => (
        `${expanded ? "收起" : "展开"} ${appName} 的活动详情`
      ),
    },
    settings: {
      toggleTrackingPaused: "切换暂停追踪",
      toggleMinimizeToWidget: "切换最小化到挂件",
      toggleCloseToTray: "切换关闭到托盘",
      toggleLaunchAtLogin: "切换开机自启动",
      toggleStartMinimized: "切换启动时最小化",
      colorScheme: "配色方案",
    },
    color: {
      color: "颜色",
      eyedropper: "取色器",
      eyedropperUnsupported: "当前环境不支持取色器",
      colorPicker: "颜色选择器",
      colorFormat: "颜色格式",
    },
  },
  toast: {
    releaseNotesOpenFailed: "无法打开发布说明链接。",
    feedbackOpenFailed: "无法打开反馈链接。",
    settingsRuntimeSyncPartial: "设置已保存，部分运行时同步将在下次刷新后生效。",
    cleanupSuccess: "历史数据已清理。",
    cleanupFailed: "历史数据清理失败，请稍后重试。",
    backupExportSuccess: (path: string) => `备份已创建：${path}`,
    backupExportFailed: "备份失败，请检查路径后重试。",
    backupIncompatible: (reason?: string | null) => `备份不兼容：${reason ?? "无法确认兼容性"}`,
    backupPreviewFailed: "无法预览备份文件，请确认文件后重试。",
    backupRestoreSuccess: "备份已恢复，正在刷新界面。",
    backupRestoreFailed: "备份恢复失败，已自动回滚，不会破坏当前数据。",
  },
  date: {
    today: "今天",
    yesterday: "昨天",
    weekdaysShort: ["一", "二", "三", "四", "五", "六", "日"],
    heatmapWeekdays: ["一", "", "三", "", "五", "", "日"],
    monthLabel: (month: number) => `${month}月`,
    yearMonthLabel: (year: number, month: number) => `${year} 年 ${month} 月`,
  },
  dashboard: {
    title: "今天",
    tracking: (activeAppName: string) => `正在追踪：${activeAppName}`,
    trackingPaused: "追踪已暂停",
    idle: "暂无活动",
    afk: "无操作",
    active: "当前活跃",
    paused: "已暂停",
    focusShare: "专注分布",
    total: "总计",
    comparedWithYesterday: (deltaLabel: string, direction: "increase" | "decrease" | "same") => {
      if (direction === "same") return "与昨天持平";
      return `比昨天${direction === "increase" ? "增加" : "减少"} ${deltaLabel}`;
    },
    hourlyActivity: "今日活动",
    activeMinutes: "活跃",
    topApps: "应用排行",
    topAppsBadge: (count: number) => `前 ${count} 项`,
    emptyState: "暂无今日记录",
    sharePrefix: "占比",
  },
  history: {
    title: "历史",
    sessionCount: (count: number) => `${count} 段会话`,
    pastSevenDays: "近 7 天",
    dailyHourlyActivity: "当日活动",
    appDistribution: "应用分布",
    noData: "暂无数据",
    timeline: "时间线",
    loading: "加载中...",
    emptyDay: "这一天暂无记录",
    mergedCount: (count: number) => `${count} 段活动`,
    untilNow: "至今",
  },
  data: {
    title: "数据",
    subtitle: "查看趋势与长期变化",
    pastSevenDays: "近 7 天",
    activityTrend: "活动趋势",
    weeklyTotal: "7 日总时长",
    dailyAverage: "日均时长",
    dailyAverageHint: "按近 7 天计算",
    appTrend: "应用趋势",
    appTrendHint: "查看各应用的每日时长",
    appSearchPlaceholder: "搜索应用",
    appTrendAppList: "应用列表",
    appTrendEmpty: "当前范围暂无应用数据",
    appTrendNoMatch: "没有匹配的应用",
    appTrendTotal: "总时长",
    appTrendAverage: "日均",
    appTrendActiveDays: "活跃天数",
    appTrendPeakDay: "峰值日",
    appTrendUsage: "应用时长",
    appTrendDayBreakdown: "每日明细",
    activityHeatmap: "活动热力图",
    activityHeatmapHint: "每日活动强度",
    recentYear: "近一年",
    pastThirtyDays: "近 30 天",
    trendTotal: (range: 7 | 30 | 365) => (
      range === 7 ? "7 日总时长" : range === 30 ? "30 日总时长" : "近一年总时长"
    ),
    yearlyAverage: "月均时长",
    yearlyAverageHint: "按近一年月份计算",
    rangeAverageHint: (rangeLabel: string) => `按${rangeLabel}计算`,
    notStarted: "未开始",
    duration: "时长",
    monthlyAverage: "月均",
    less: "少",
    more: "多",
  },
  about: {
    title: "关于",
    subtitle: "版本、更新与反馈",
    sectionTitle: "关于",
    appInfo: "应用信息",
    currentVersion: (version: string) => `当前版本：v${version}`,
    description: "查看发布说明，或提交反馈。",
  },
  settings: {
    loading: "正在获取配置...",
    title: "设置",
    subtitle: "调整追踪、常驻、数据和外观设置",
    saving: "正在保存...",
    saved: "配置已更新",
    saveFailed: "配置保存失败，请稍后重试。",
    unsaved: "有未保存更改",
    idle: "已保存",
    save: "保存",
    cancel: "取消",
    cancelled: "已撤销本次编辑",
    tracking: "追踪",
    idleTimeoutLabel: "持续计入时间",
    idleTimeoutHint: "当前应用有音频等持续信号时，继续计入这段时间。",
    timelineMergeGapLabel: "合并间隔",
    timelineMergeGapHint: "短暂离开后在此时间内返回，仍合并为同一段活动。",
    minSessionLabel: "时间线最短时长",
    minSessionHint: "只影响时间线展示；排行、分布和总时长仍按真实活动统计。",
    performance: "性能",
    refreshLabel: "刷新间隔",
    refreshHint: "前端界面从后端拉取最新数据的时间间隔。",
    refreshWarning: "较短的刷新频率会增加一定的 CPU 开销。如果你发现界面有些卡顿，建议设置为 5s 及以上。",
    cleanup: "数据管理",
    cleanupTitle: "清理历史记录",
    cleanupHint: "删除所选时间以前的记录，数据无法恢复。",
    cleanupRunning: "正在清理...",
    cleanupNow: "清理",
    cleanupConfirmTitle: "清理历史数据",
    cleanupConfirmDetail: (label: string) => `将删除 ${label} 及更早的记录。`,
    restoreConfirmTitle: "恢复备份",
    restoreConfirmDetail: (path: string, summary: string, strategy: string) => `恢复策略：${strategy}\n目标文件：${path}\n\n${summary}`,
    otherReviewTitle: "未分类应用",
    otherReviewHint: "这里只显示你真实出现过的未分类应用，可轻量指定类别。",
    otherReviewToggle: "查看未分类应用",
    otherReviewEmpty: "最近没有需要人工判定的未分类应用。",
    otherReviewReset: "恢复自动识别",
    otherReviewClearAll: "清空手动覆盖",
    otherReviewApplying: "正在应用...",
    otherReviewCategoryLabel: "类别",
    confirmRangeFallback: "所选时间",
    confirmCleanup: (label: string) => `确定要清理 ${label} 及更早的所有记录吗？此操作无法撤销。`,
    cleanupRangeLabels: {
      180: "180 天前",
      90: "90 天前",
      60: "60 天前",
      30: "30 天前",
      15: "15 天前",
      7: "7 天前",
    } as Record<number, string>,
    refreshPresets: {
      1: "实时 (1s)",
      3: "平衡 (3s)",
      5: "省电 (5s)",
      10: "低频 (10s)",
    } as Record<number, string>,
    minutePresets: {
      60: "1 分钟",
      180: "3 分钟",
      300: "5 分钟",
      600: "10 分钟",
    } as Record<number, string>,
    trackingPanelTitle: "追踪",
    trackingPausedLabel: "暂停追踪",
    trackingPausedHint: "暂停后不再写入新记录，恢复后继续计时。",
    residentTitle: "常驻",
    minimizeToWidgetLabel: "最小化到挂件",
    minimizeToWidgetHint: "开启后，点最小化时隐藏主窗口并显示侧边挂件。",
    closeToTrayLabel: "关闭到托盘",
    closeToTrayHint: "开启后，点关闭时隐藏窗口并继续后台运行。",
    launchAtLoginLabel: "开机自启动",
    launchAtLoginHint: "开启后，系统登录时自动启动应用。",
    startMinimizedLabel: "启动时最小化",
    startMinimizedHint: "仅对自启动生效：启动时按当前最小化行为收起。",
    appearanceTitle: "外观",
    themeModeOptions: {
      light: "浅色",
      dark: "深色",
      system: "跟随系统",
    },
    themeLibraryOptions: {
      light: "浅色主题",
      dark: "深色主题",
    },
    themeModeLabel: "主题模式",
    themeModeHint: "选择浅色、深色，或跟随系统外观自动切换。",
    languageLabel: "语言",
    languageHint: "选择界面显示语言。",
    languageOptions: {
      zhCN: "中文",
      enUS: "English",
    },
    colorSchemeLabel: "配色方案",
    colorSchemeHint: "分别设置浅色和深色主题的整体配色。",
    colorSchemeDialogFallbackTitle: "主题",
    colorSchemeDialogDescription: "选择后会即时预览，保存后生效。",
    colorSchemeSaving: "保存中",
    dataSafetyTitle: "数据安全",
    backupRestoreTitle: "备份与恢复",
    backupRestoreHint: "包含会话数据、设置项和图标缓存。恢复策略决定如何处理当前数据。",
    backupExportTitle: "备份",
    backupExportHint: "备份当前数据快照",
    backupExporting: "备份中...",
    backupExportAction: "备份",
    backupRestoreActionTitle: "恢复",
    backupRestoreActionHint: "从备份恢复数据",
    restoreStrategyLabel: "恢复策略",
    restoreStrategyHint: "选择恢复时如何处理当前数据。",
    restoreStrategyOptions: {
      replace: "覆盖",
      merge: "兼容",
    },
    backupRestoring: "恢复中...",
    backupRestoreAction: "恢复",
    minuteValue: (minutes: number) => `${minutes} 分钟`,
    decreaseMinute: (label: string) => `${label}减少 1 分钟`,
    increaseMinute: (label: string) => `${label}增加 1 分钟`,
  },
  mapping: {
    title: "应用",
    subtitle: "按应用设置分类、颜色与标题记录",
    saving: "正在保存...",
    saved: "已保存",
    idle: "已保存",
    unsaved: "有未保存更改",
    save: "保存",
    cancel: "取消",
    categoryControl: "管理分类",
    loading: "加载中...",
    emptyState: "当前筛选下暂无应用",
    createCategoryTitle: "新建自定义分类",
    createCategoryDescription: "请输入自定义分类名称（最多 4 个字）。",
    createCategoryPlaceholder: "例如：学习",
    deleteCategoryTitle: "删除分类",
    deleteCategoryDetail: (label: string) => `目标分类：${label}`,
    deleteCategory: (label: string) => `删除分类：${label}`,
    deleteAppSessionsTitle: "删除应用记录",
    deleteAppSessionsDetail: (label: string) => `目标应用：${label}`,
    filters: {
      all: "全部",
      other: "未分类",
      classified: "已分类",
    },
    categoryDialogTitle: "管理分类",
    categoryDialogDescription: "新建分类，调整分类颜色",
    createCategoryAction: "新建分类",
    editAppName: "修改应用名称",
    color: "颜色",
    restoreDefaultColor: "恢复默认颜色",
    noStats: "不计入统计",
    statsEnabled: "计入统计",
    titleNotRecorded: "不记录标题",
    titleRecorded: "记录标题",
    disableTitleCapture: "不记录该应用窗口标题",
    enableTitleCapture: "恢复记录该应用窗口标题",
    disableTracking: "将该应用排除出统计",
    enableTracking: "重新计入统计",
    restoreDefaultApp: "恢复默认识别",
    deleteAppRecords: "删除应用记录",
    autoCategory: "自动识别",
  },
  update: {
    appUpdate: "应用更新",
    sidebarEntry: "更新",
    releaseNotes: "更新说明",
    feedback: "问题反馈",
    later: "稍后",
    manualDownload: "手动下载",
    downloadInstaller: "下载安装包",
    redownloadInstaller: "重新下载安装包",
    installAgain: "再次安装",
    checkAgain: "重新检查",
    checkUpdates: "检查更新",
    checkingUpdates: "正在检查更新...",
    checking: "检查中...",
    downloading: "正在下载更新...",
    installing: "正在安装更新...",
    processing: "处理中...",
    foundVersion: (version: string) => `发现新版本：${version}`,
    unknownVersion: "未知版本",
    updateReadyDetail: "新版本可用。确认后开始下载。",
    downloadNow: "立即下载",
    downloadedTitle: (version: string) => `更新已下载：${version}`,
    downloadedDetail: "更新包已下载。确认后重启安装。",
    restartInstall: "重启安装",
    targetVersion: (version: string) => `目标版本：${version}`,
    preparingPackage: "正在准备更新包。",
    installRestartDetail: "安装完成后应用会自动重启。",
    upToDate: "已是最新版本",
    notChecked: "未检查更新",
    checkFailed: "无法检查更新",
    downloadFailed: "无法下载安装包",
    installFailed: "更新安装失败",
    updateFailed: "更新失败",
    checkFailedDialog: "无法检查更新",
    downloadFailedDialog: "下载更新失败",
    installFailedDialog: "安装更新失败",
    updateFailedDialog: "更新失败",
    checkErrorDetail: "无法访问更新清单。当前网络可能无法连接 GitHub，你可以稍后重试，或手动下载。",
    downloadErrorDetail: "已发现新版本，但自动下载安装包失败。你可以手动下载。",
    installErrorDetail: "更新包已下载，但安装没有完成。你可以再次安装，或重新下载。",
    genericErrorDetail: "更新流程未能完成。你可以稍后重试。",
    errorDetailWithSummary: (prefix: string, summary: string) => `${prefix} 详细信息：${summary}`,
    downloadedBytes: (value: string) => `已下载 ${value}`,
    progressPending: "正在获取进度",
    packageDownloaded: (value?: string) => value ? `更新包 ${value} 已下载` : "更新包已下载",
    installingProgress: "正在安装更新，应用将很快重启",
    dialogInstalling: "正在安装更新",
    dialogDownloading: "正在下载更新",
    dialogDownloaded: "更新已下载",
    dialogAvailable: "发现新版本",
    dialogInstallingDetail: "更新安装已开始。请保持应用开启，完成后会自动重启。",
    dialogDownloadingDetail: "更新包正在下载，完成后会切换到安装确认。",
    dialogDownloadedDetail: "更新包已下载。确认后重启并完成安装。",
    dialogAvailableDetail: "新版本可用。确认后先下载更新包，下载完成后再确认安装。",
    updateProcessFailed: "更新流程未能完成。",
  },
  backup: {
    versionLabel: (version: number) => `备份版本：v${version}`,
    schemaLabel: (schemaVersion: number) => `Schema ${schemaVersion}`,
    exportedAt: (value: string) => `导出时间：${value}`,
    appVersion: (version: string) => `应用版本：${version}`,
    restoreSafety: (message: string) => `恢复提示：${message}`,
    itemCounts: (sessionCount: number, settingCount: number, iconCacheCount: number) => (
      `会话数：${sessionCount}，设置项：${settingCount}，图标缓存：${iconCacheCount}`
    ),
  },
  categories: {
    ai: "AI",
    custom: "自定义",
    short: {
      development: "开发",
      office: "办公",
      browser: "浏览",
      communication: "通讯",
      video: "视频",
      music: "音乐",
      game: "游戏",
      design: "设计",
      utility: "工具",
      other: "未分类",
      system: "系统",
    },
    development: "开发编码",
    office: "办公协作",
    browser: "浏览阅读",
    communication: "即时通讯",
    video: "视频内容",
    music: "音乐音频",
    game: "游戏",
    design: "设计创作",
    utility: "工具效率",
    system: "系统工具",
    other: "其他应用",
  },
};

export type UiLanguage = "zh-CN" | "en-US";
type WidenCopyValue<T> =
  T extends (...args: infer Args) => infer Return
    ? (...args: Args) => WidenCopyValue<Return>
    : T extends string
      ? string
      : T extends number
        ? number
        : T extends boolean
          ? boolean
          : T extends readonly (infer Item)[]
            ? WidenCopyValue<Item>[]
            : T extends Record<PropertyKey, unknown>
              ? { [Key in keyof T]: WidenCopyValue<T[Key]> }
              : T;
export type UiText = WidenCopyValue<typeof ZH_CN_UI_TEXT>;

const EN_US_UI_TEXT: UiText = {
  ...ZH_CN_UI_TEXT,
  common: {
    ...ZH_CN_UI_TEXT.common,
    confirm: "Confirm",
    cancel: "Cancel",
    close: "Close",
    save: "Save",
    saving: "Saving...",
    saved: "Saved",
    loading: "Loading...",
    processing: "Processing...",
    default: "Default",
  },
  dialog: {
    confirm: "Confirm",
    cancel: "Cancel",
    confirmDanger: "Continue",
  },
  app: {
    loadingView: "Loading view...",
    mappingUpdated: "App settings updated.",
    historyDeleted: "App history deleted.",
    unsavedConfirmTitle: "Save changes",
    unsavedConfirmBody: "This page has unsaved changes. Save before switching pages.",
    unsavedConfirmSave: "Save",
  },
  widget: {
    tracking: "Tracking",
    sustainedTracking: "Sustained",
    currentApp: "Current app",
    currentActivityRecording: "Current activity is being recorded",
    currentSustainedRecording: "Sustained activity is being recorded",
    pause: "Pause",
    resume: "Resume",
    error: "Error",
    trackingService: "Tracking service",
    trackingNotSynced: "Tracking status is not synced yet",
    paused: "Paused",
    trackingPaused: "Tracking paused",
    clickToResume: "Click to resume tracking",
    idle: "Idle",
    currentlyIdle: "Currently idle",
    currentAppNotTracked: "Current app is not tracked",
    noTrackableActivity: "No trackable activity",
    windowExcluded: "Current window will not be recorded",
    loadingStatus: "Loading",
    loadingAppName: "Widget",
    loadingHelper: "Syncing status",
    pauseTracking: "Pause tracking",
  },
  accessibility: {
    titleBar: {
      minimize: "Minimize window",
      maximize: "Maximize window",
      restore: "Restore window",
      close: "Close window",
    },
    widget: {
      currentApp: (appName: string) => `Current app: ${appName}`,
      openMainWindow: "Open main window",
      collapse: "Collapse widget",
      expand: "Expand widget",
      toggle: (expanded: boolean, statusTitle: string) => `${expanded ? "Collapse widget" : "Expand widget"}, ${statusTitle}`,
    },
    data: {
      trendSummary: "Trend summary",
      trendRange: "Select trend range",
      shorterTrendRange: "Show shorter trend range",
      longerTrendRange: "Show longer trend range",
      heatmapRange: "Select heatmap range",
      earlierRange: "Show earlier range",
      newerRange: "Show newer range",
      appTrendRange: "Select app trend range",
      shorterAppTrendRange: "Show shorter app trend range",
      longerAppTrendRange: "Show longer app trend range",
    },
    history: {
      previousMonth: "Previous month",
      nextMonth: "Next month",
      decreaseMinDuration: "Decrease minimum duration by 1 minute",
      increaseMinDuration: "Increase minimum duration by 1 minute",
      toggleActivityDetails: (expanded: boolean, appName: string) => (
        `${expanded ? "Collapse" : "Expand"} activity details for ${appName}`
      ),
    },
    settings: {
      toggleTrackingPaused: "Toggle pause tracking",
      toggleMinimizeToWidget: "Toggle minimize to widget",
      toggleCloseToTray: "Toggle close to tray",
      toggleLaunchAtLogin: "Toggle launch at login",
      toggleStartMinimized: "Toggle start minimized",
      colorScheme: "Color scheme",
    },
    color: {
      color: "Color",
      eyedropper: "Eyedropper",
      eyedropperUnsupported: "Eyedropper is unavailable",
      colorPicker: "Color picker",
      colorFormat: "Color format",
    },
  },
  toast: {
    releaseNotesOpenFailed: "Could not open release notes.",
    feedbackOpenFailed: "Could not open feedback link.",
    settingsRuntimeSyncPartial: "Settings were saved. Some runtime changes will apply after the next refresh.",
    cleanupSuccess: "History records cleared.",
    cleanupFailed: "Could not clear history records. Try again later.",
    backupExportSuccess: (path: string) => `Backup created: ${path}`,
    backupExportFailed: "Could not create backup. Check the path and try again.",
    backupIncompatible: (reason?: string | null) => `Backup is incompatible: ${reason ?? "compatibility could not be confirmed"}`,
    backupPreviewFailed: "Could not preview this backup file. Check the file and try again.",
    backupRestoreSuccess: "Backup restored. Refreshing view.",
    backupRestoreFailed: "Backup restore failed. Changes were rolled back and current data is safe.",
  },
  date: {
    today: "Today",
    yesterday: "Yesterday",
    weekdaysShort: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    heatmapWeekdays: ["Mon", "", "Wed", "", "Fri", "", "Sun"],
    monthLabel: (month: number) => new Date(2020, month - 1, 1).toLocaleString("en-US", { month: "short" }),
    yearMonthLabel: (year: number, month: number) => `${new Date(year, month - 1, 1).toLocaleString("en-US", { month: "long" })} ${year}`,
  },
  dashboard: {
    title: "Today",
    tracking: (activeAppName: string) => `Tracking: ${activeAppName}`,
    trackingPaused: "Tracking paused",
    idle: "No activity",
    afk: "Idle",
    active: "Active now",
    paused: "Paused",
    focusShare: "Focus share",
    total: "Total",
    comparedWithYesterday: (deltaLabel: string, direction: "increase" | "decrease" | "same") => {
      if (direction === "same") return "Same as yesterday";
      return `${direction === "increase" ? "Up" : "Down"} ${deltaLabel} from yesterday`;
    },
    hourlyActivity: "Today's Activity",
    activeMinutes: "Active",
    topApps: "Top Apps",
    topAppsBadge: (count: number) => `Top ${count}`,
    emptyState: "No records today",
    sharePrefix: "Share",
  },
  history: {
    title: "History",
    sessionCount: (count: number) => `${count} sessions`,
    pastSevenDays: "Last 7 days",
    dailyHourlyActivity: "Daily Activity",
    appDistribution: "App Distribution",
    noData: "No data",
    timeline: "Timeline",
    loading: "Loading...",
    emptyDay: "No records for this day",
    mergedCount: (count: number) => `${count} activities`,
    untilNow: "until now",
  },
  data: {
    title: "Data",
    subtitle: "Review trends and long-term changes",
    pastSevenDays: "Last 7 days",
    activityTrend: "Activity Trend",
    weeklyTotal: "7-day total",
    dailyAverage: "Daily avg.",
    dailyAverageHint: "Based on last 7 days",
    appTrend: "App Trends",
    appTrendHint: "View daily time by app",
    appSearchPlaceholder: "Search apps",
    appTrendAppList: "App list",
    appTrendEmpty: "No app data in this range",
    appTrendNoMatch: "No matching apps",
    appTrendTotal: "Total",
    appTrendAverage: "Daily avg.",
    appTrendActiveDays: "Active days",
    appTrendPeakDay: "Peak day",
    appTrendUsage: "App time",
    appTrendDayBreakdown: "Daily details",
    activityHeatmap: "Activity Heatmap",
    activityHeatmapHint: "Daily activity intensity",
    recentYear: "Past year",
    pastThirtyDays: "Last 30 days",
    trendTotal: (range: 7 | 30 | 365) => (
      range === 7 ? "7-day total" : range === 30 ? "30-day total" : "Past year total"
    ),
    yearlyAverage: "Monthly avg.",
    yearlyAverageHint: "Based on months in the past year",
    rangeAverageHint: (rangeLabel: string) => `Based on ${rangeLabel}`,
    notStarted: "Not started",
    duration: "Duration",
    monthlyAverage: "Monthly avg.",
    less: "Less",
    more: "More",
  },
  about: {
    title: "About",
    subtitle: "Version, updates, and feedback",
    sectionTitle: "About",
    appInfo: "App info",
    currentVersion: (version: string) => `Current version: v${version}`,
    description: "View release notes or send feedback.",
  },
  settings: {
    ...ZH_CN_UI_TEXT.settings,
    loading: "Loading settings...",
    title: "Settings",
    subtitle: "Adjust tracking, resident, data, and appearance settings",
    saving: "Saving...",
    saved: "Settings updated",
    saveFailed: "Could not save settings. Try again later.",
    unsaved: "Unsaved changes",
    idle: "Saved",
    save: "Save",
    cancel: "Cancel",
    cancelled: "Edits discarded",
    tracking: "Tracking",
    idleTimeoutLabel: "Continue counting",
    idleTimeoutHint: "When the current app has audio or similar signals, keep counting this time.",
    timelineMergeGapLabel: "Merge gap",
    timelineMergeGapHint: "If you return within this time, it stays in the same activity segment.",
    minSessionLabel: "Timeline minimum",
    minSessionHint: "Only affects timeline display; rankings, distribution, and totals still use real activity.",
    performance: "Performance",
    refreshLabel: "Refresh interval",
    refreshHint: "How often the interface pulls fresh data from the backend.",
    refreshWarning: "Shorter refresh intervals can increase CPU usage. Use 5s or above if the UI feels slow.",
    cleanup: "Data management",
    cleanupTitle: "Clear history records",
    cleanupHint: "Delete records older than the selected range. Data cannot be restored.",
    cleanupRunning: "Clearing...",
    cleanupNow: "Clear",
    cleanupConfirmTitle: "Clear history",
    cleanupConfirmDetail: (label: string) => `Records from ${label} and earlier will be deleted.`,
    restoreConfirmTitle: "Restore backup",
    restoreConfirmDetail: (path: string, summary: string, strategy: string) => `Restore strategy: ${strategy}\nTarget file: ${path}\n\n${summary}`,
    otherReviewTitle: "Unclassified apps",
    otherReviewHint: "Only apps that have appeared on this device are shown here.",
    otherReviewToggle: "View unclassified apps",
    otherReviewEmpty: "No recent unclassified apps need review.",
    otherReviewReset: "Restore auto detection",
    otherReviewClearAll: "Clear manual overrides",
    otherReviewApplying: "Applying...",
    otherReviewCategoryLabel: "Category",
    confirmRangeFallback: "selected range",
    confirmCleanup: (label: string) => `Clear all records from ${label} and earlier? This cannot be undone.`,
    cleanupRangeLabels: {
      180: "180 days ago",
      90: "90 days ago",
      60: "60 days ago",
      30: "30 days ago",
      15: "15 days ago",
      7: "7 days ago",
    } as Record<number, string>,
    refreshPresets: {
      1: "Realtime (1s)",
      3: "Balanced (3s)",
      5: "Battery saver (5s)",
      10: "Low frequency (10s)",
    } as Record<number, string>,
    minutePresets: {
      60: "1 minute",
      180: "3 minutes",
      300: "5 minutes",
      600: "10 minutes",
    } as Record<number, string>,
    trackingPanelTitle: "Tracking",
    trackingPausedLabel: "Pause tracking",
    trackingPausedHint: "Paused tracking will stop writing new records. Resume to continue.",
    residentTitle: "Resident",
    minimizeToWidgetLabel: "Minimize to widget",
    minimizeToWidgetHint: "When minimized, hide the main window and show the side widget.",
    closeToTrayLabel: "Close to tray",
    closeToTrayHint: "When closed, hide the window and keep running in the background.",
    launchAtLoginLabel: "Launch at login",
    launchAtLoginHint: "Start the app automatically when Windows signs in.",
    startMinimizedLabel: "Start minimized",
    startMinimizedHint: "Only applies to launch at login. Starts with the current minimize behavior.",
    appearanceTitle: "Appearance",
    themeModeOptions: {
      light: "Light",
      dark: "Dark",
      system: "System",
    },
    themeLibraryOptions: {
      light: "Light theme",
      dark: "Dark theme",
    },
    themeModeLabel: "Theme mode",
    themeModeHint: "Use light, dark, or follow the system appearance.",
    languageLabel: "Language",
    languageHint: "Choose the interface language.",
    languageOptions: {
      zhCN: "中文",
      enUS: "English",
    },
    colorSchemeLabel: "Color scheme",
    colorSchemeHint: "Set the overall color style for light and dark themes.",
    colorSchemeDialogFallbackTitle: "Theme",
    colorSchemeDialogDescription: "Preview now. Save to apply.",
    colorSchemeSaving: "Saving",
    dataSafetyTitle: "Data safety",
    backupRestoreTitle: "Backup and restore",
    backupRestoreHint: "Includes sessions, settings, and cached icons. The restore strategy decides how current data is handled.",
    backupExportTitle: "Back up",
    backupExportHint: "Create a backup of current data",
    backupExporting: "Backing up...",
    backupExportAction: "Back up",
    backupRestoreActionTitle: "Restore",
    backupRestoreActionHint: "Restore data from a backup",
    restoreStrategyLabel: "Restore strategy",
    restoreStrategyHint: "Choose how restore handles current data.",
    restoreStrategyOptions: {
      replace: "Replace",
      merge: "Merge",
    },
    backupRestoring: "Restoring...",
    backupRestoreAction: "Restore",
    minuteValue: (minutes: number) => `${minutes} min`,
    decreaseMinute: (label: string) => `Decrease ${label} by 1 minute`,
    increaseMinute: (label: string) => `Increase ${label} by 1 minute`,
  },
  mapping: {
    ...ZH_CN_UI_TEXT.mapping,
    title: "Apps",
    subtitle: "Set category, color, and title recording per app",
    saving: "Saving...",
    saved: "Saved",
    idle: "Saved",
    unsaved: "Unsaved changes",
    save: "Save",
    cancel: "Cancel",
    categoryControl: "Manage categories",
    loading: "Loading...",
    emptyState: "No apps match the current filter",
    createCategoryTitle: "New custom category",
    createCategoryDescription: "Enter a custom category name, up to 4 characters.",
    createCategoryPlaceholder: "Example: Study",
    deleteCategoryTitle: "Delete category",
    deleteCategoryDetail: (label: string) => `Target category: ${label}`,
    deleteCategory: (label: string) => `Delete category: ${label}`,
    deleteAppSessionsTitle: "Delete app records",
    deleteAppSessionsDetail: (label: string) => `Target app: ${label}`,
    filters: {
      all: "All",
      other: "Unclassified",
      classified: "Classified",
    },
    categoryDialogTitle: "Manage categories",
    categoryDialogDescription: "Create categories and adjust category colors",
    createCategoryAction: "New category",
    editAppName: "Edit app name",
    color: "Color",
    restoreDefaultColor: "Restore default color",
    noStats: "Excluded",
    statsEnabled: "Included",
    titleNotRecorded: "No title",
    titleRecorded: "Record title",
    disableTitleCapture: "Stop recording this app's window titles",
    enableTitleCapture: "Resume recording this app's window titles",
    disableTracking: "Exclude this app from statistics",
    enableTracking: "Include this app in statistics",
    restoreDefaultApp: "Restore default",
    deleteAppRecords: "Delete records",
    autoCategory: "Auto",
  },
  update: {
    appUpdate: "App updates",
    sidebarEntry: "Update",
    releaseNotes: "Release notes",
    feedback: "Feedback",
    later: "Later",
    manualDownload: "Manual download",
    downloadInstaller: "Download installer",
    redownloadInstaller: "Download again",
    installAgain: "Install again",
    checkAgain: "Check again",
    checkUpdates: "Check updates",
    checkingUpdates: "Checking for updates...",
    checking: "Checking...",
    downloading: "Downloading update...",
    installing: "Installing update...",
    processing: "Processing...",
    foundVersion: (version: string) => `New version: ${version}`,
    unknownVersion: "unknown version",
    updateReadyDetail: "A new version is available. Confirm to start downloading.",
    downloadNow: "Download now",
    downloadedTitle: (version: string) => `Update downloaded: ${version}`,
    downloadedDetail: "The update package is downloaded. Confirm to restart and install.",
    restartInstall: "Restart to install",
    targetVersion: (version: string) => `Target version: ${version}`,
    preparingPackage: "Preparing the update package.",
    installRestartDetail: "The app will restart after installation.",
    upToDate: "You are up to date",
    notChecked: "Not checked",
    checkFailed: "Could not check updates",
    downloadFailed: "Could not download installer",
    installFailed: "Update installation failed",
    updateFailed: "Update failed",
    checkFailedDialog: "Could not check updates",
    downloadFailedDialog: "Download failed",
    installFailedDialog: "Install failed",
    updateFailedDialog: "Update failed",
    checkErrorDetail: "Could not access the update manifest. Your current network may not be able to reach GitHub. Try again later or download manually.",
    downloadErrorDetail: "A new version was found, but automatic download failed. You can download manually.",
    installErrorDetail: "The update package was downloaded, but installation did not finish. Try installing again or redownload it.",
    genericErrorDetail: "The update flow could not finish. Try again later.",
    errorDetailWithSummary: (prefix: string, summary: string) => `${prefix} Details: ${summary}`,
    downloadedBytes: (value: string) => `Downloaded ${value}`,
    progressPending: "Getting progress",
    packageDownloaded: (value?: string) => value ? `Package ${value} downloaded` : "Package downloaded",
    installingProgress: "Installing update. The app will restart soon.",
    dialogInstalling: "Installing update",
    dialogDownloading: "Downloading update",
    dialogDownloaded: "Update downloaded",
    dialogAvailable: "New version available",
    dialogInstallingDetail: "Installation has started. Keep the app open; it will restart when finished.",
    dialogDownloadingDetail: "The update package is downloading. Installation confirmation appears when it finishes.",
    dialogDownloadedDetail: "The update package is ready. Confirm to restart and finish installation.",
    dialogAvailableDetail: "A new version is available. Download first, then confirm installation.",
    updateProcessFailed: "The update flow could not finish.",
  },
  backup: {
    versionLabel: (version: number) => `Backup version: v${version}`,
    schemaLabel: (schemaVersion: number) => `Schema ${schemaVersion}`,
    exportedAt: (value: string) => `Exported at: ${value}`,
    appVersion: (version: string) => `App version: ${version}`,
    restoreSafety: (message: string) => `Restore status: ${message}`,
    itemCounts: (sessionCount: number, settingCount: number, iconCacheCount: number) => (
      `Sessions: ${sessionCount}, settings: ${settingCount}, cached icons: ${iconCacheCount}`
    ),
  },
  categories: {
    ai: "AI",
    custom: "Custom",
    short: {
      development: "Dev",
      office: "Office",
      browser: "Browser",
      communication: "Chat",
      video: "Video",
      music: "Music",
      game: "Games",
      design: "Design",
      utility: "Tools",
      other: "Other",
      system: "System",
    },
    development: "Development",
    office: "Office",
    browser: "Browser",
    communication: "Communication",
    video: "Video",
    music: "Music",
    game: "Games",
    design: "Design",
    utility: "Utilities",
    system: "System",
    other: "Other apps",
  },
};

export const COPY: Record<UiLanguage, UiText> = {
  "zh-CN": ZH_CN_UI_TEXT,
  "en-US": EN_US_UI_TEXT,
};

export const SUPPORTED_UI_LANGUAGES = Object.keys(COPY) as UiLanguage[];

let activeUiLanguage: UiLanguage = "zh-CN";
let activeUiText: UiText = ZH_CN_UI_TEXT;

export function getUiText(language: UiLanguage): UiText {
  return COPY[language] ?? ZH_CN_UI_TEXT;
}

export function getUiTextLanguage(): UiLanguage {
  return activeUiLanguage;
}

export function getUiLocale(): UiLanguage {
  return activeUiLanguage;
}

export function setUiTextLanguage(language: UiLanguage): void {
  activeUiLanguage = COPY[language] ? language : "zh-CN";
  activeUiText = getUiText(activeUiLanguage);
}

export const UI_TEXT: UiText = new Proxy({} as UiText, {
  get(_target, property: keyof UiText) {
    return activeUiText[property];
  },
});
