export const UI_TEXT = {
  dialog: {
    confirm: "确认",
    cancel: "取消",
    confirmDanger: "继续",
  },
  app: {
    loadingView: "正在加载界面...",
    mappingUpdated: "应用映射已更新。",
    historyDeleted: "应用历史已删除。",
    unsavedConfirmTitle: "保存未保存修改",
    unsavedConfirmBody: "当前页面有未保存更改。保存后将自动切换到目标页面。",
    unsavedConfirmSave: "保存",
  },
  date: {
    today: "今天",
    yesterday: "昨天",
  },
  dashboard: {
    title: "概览",
    tracking: (activeAppName: string) => `正在追踪: ${activeAppName}`,
    trackingPaused: "追踪已暂停",
    idle: "静候活动中",
    afk: "处于挂机状态",
    active: "当前活跃",
    paused: "已暂停",
    focusShare: "专注分布",
    total: "总计",
    hourlyActivity: "今日能量脉冲",
    activeMinutes: "活跃",
    topApps: "应用排行",
    topAppsBadge: (count: number) => `前 ${count} 位`,
    emptyState: "先去专注一会儿吧...",
    sharePrefix: "占比",
  },
  history: {
    title: "历史概览",
    sessionCount: (count: number) => `${count} 段会话`,
    pastSevenDays: "近 7 天",
    appDistribution: "应用分布",
    noData: "暂无数据",
    timeline: "专注时间流",
    loading: "加载中...",
    emptyDay: "当天暂无记录",
    mergedCount: (count: number) => `${count} 次活动`,
    untilNow: "至今",
  },
  settings: {
    loading: "正在获取配置...",
    title: "系统设置",
    subtitle: "定制你的追踪偏好与数据行为",
    saving: "正在保存...",
    saved: "配置已更新",
    saveFailed: "配置保存失败，请稍后重试。",
    unsaved: "有未保存更改",
    idle: "已保存",
    save: "保存",
    cancel: "取消",
    cancelled: "已撤销本次编辑",
    tracking: "追踪策略",
    idleTimeoutLabel: "自动挂机判定 (AFK)",
    idleTimeoutHint: "超过这个时间未操作时，会在最后一次输入时结束当前记录。",
    timelineMergeGapLabel: "时间流合并窗口",
    timelineMergeGapHint: "切到其他应用后，如果在这个时间内回到同一应用，会合并成一条连续时间流。",
    minSessionLabel: "专注时间流最少时长",
    minSessionHint: "仅用于专注时间流展示过滤；应用排行、应用分布和总时长始终按真实活跃时长统计。",
    performance: "性能与同步",
    refreshLabel: "UI 刷新频率",
    refreshHint: "前端界面从后端拉取最新数据的时间间隔。",
    refreshWarning: "较短的刷新频率会增加一定的 CPU 开销。如果你发现界面有些卡顿，建议设置为 5s 及以上。",
    cleanup: "数据管理",
    cleanupTitle: "按时间范围清理历史数据",
    cleanupHint: "删除早于所选天数的记录，例如选择“30 天前”会清理 30 天前及更早的数据。",
    cleanupRunning: "正在清理...",
    cleanupNow: "立即清理记录",
    cleanupConfirmTitle: "清理历史数据",
    cleanupConfirmDetail: (label: string) => `将删除 ${label} 及更早的记录。`,
    restoreConfirmTitle: "恢复备份",
    restoreConfirmDetail: (path: string, summary: string) => `恢复会覆盖当前统计、应用映射和缓存图标。\n目标文件：${path}\n\n${summary}`,
    otherReviewTitle: "未分类应用微调",
    otherReviewHint: "这里只显示你真实出现过的未分类应用，可轻量指定类别。",
    otherReviewToggle: "查看未分类应用",
    otherReviewEmpty: "最近没有需要人工判定的未分类应用。",
    otherReviewReset: "恢复自动识别",
    otherReviewClearAll: "清空手动覆盖",
    otherReviewApplying: "正在应用...",
    otherReviewCategoryLabel: "类别",
    confirmRangeFallback: "所选时间",
    confirmCleanup: (label: string) => `确定要清理 ${label} 及更早的所有记录吗？此操作无法撤销。`,
    cleanupRangeLabels: {
      180: "180 天前",
      90: "90 天前",
      60: "60 天前",
      30: "30 天前",
      15: "15 天前",
      7: "7 天前",
    } as Record<number, string>,
    refreshPresets: {
      1: "实时 (1s)",
      3: "平衡 (3s)",
      5: "省电 (5s)",
      10: "低频 (10s)",
    } as Record<number, string>,
    minutePresets: {
      60: "1 分钟",
      180: "3 分钟",
      300: "5 分钟",
      600: "10 分钟",
    } as Record<number, string>,
  },
  mapping: {
    title: "应用美化与隐私",
    subtitle: "按应用设置分类、颜色与标题记录",
    saving: "正在保存...",
    saved: "已保存",
    idle: "已保存",
    unsaved: "有未保存更改",
    save: "保存",
    cancel: "取消",
    categoryControl: "分类控制",
    loading: "加载中...",
    emptyState: "当前筛选下暂无应用",
    createCategoryTitle: "新建自定义分类",
    createCategoryDescription: "请输入自定义分类名称（最多 4 个字）。",
    createCategoryPlaceholder: "例如：学习",
    deleteCategoryTitle: "删除分类",
    deleteCategoryDetail: (label: string) => `目标分类：${label}`,
    deleteAppSessionsTitle: "删除应用记录",
    deleteAppSessionsDetail: (label: string) => `目标应用：${label}`,
  },
  categories: {
    development: "开发编码",
    office: "办公协作",
    browser: "浏览阅读",
    communication: "即时通讯",
    meeting: "会议语音",
    video: "视频内容",
    music: "音乐音频",
    game: "游戏",
    design: "设计创作",
    reading: "阅读研究",
    finance: "金融交易",
    utility: "工具效率",
    system: "系统工具",
    other: "其他应用",
  },
} as const;
